app/react/Forms/components/MultiSelect.js, app/react/Forms/components/specs/MultiSelect.spec.js, app/react/Forms/components/specs/__snapshots__/MultiSelect.spec.js.snap
Fixes issue #1944 
PR checklist:
QA checklist:
=> grouped option label will now not show undefined

app/api/search/routes.js, app/api/search/specs/__snapshots__/routes.spec.js.snap
Fixes issue #
PR checklist:
QA checklist:
=> search endpoint validation schema fix

app/api/documents/documents.js, app/api/entities/entities.js, app/api/entities/specs/entities.spec.js, app/api/entities/specs/fixtures.js, app/api/upload/PDF.js, app/api/upload/specs/PDF.spec.js, app/react/Settings/actions/specs/navlinksActions.spec.js
Fixes issue #1946
PR checklist:
QA checklist:
=> 1946 delete thumbnails

app/api/entities/entities.js, app/api/entities/specs/entities.spec.js, app/api/search/specs/search.spec.js, app/api/utils/error_handling_middleware.js, app/api/utils/handleError.js, app/api/utils/specs/error_handling_middleware.spec.js, app/api/utils/specs/handleError.spec.js, app/server.js
Fixes issue #1871 
PR checklist:
QA checklist:
=> 1871 debug info on errors

app/react/App/App.js, app/react/App/GoogleAnalytics.js, app/react/App/Root.js, app/react/App/specs/GoogleAnalytics.spec.js
Fixes issue #1973 
PR checklist:
QA checklist:
=> moved GA code to head tag

app/api/users/routes.js, app/api/users/specs/__snapshots__/routes.spec.js.snap, app/api/users/specs/users.spec.js, app/api/users/users.js, app/api/utils/mailer.js, app/react/App/scss/modules/_login.scss, app/react/Notifications/actions/notificationsActions.js, app/react/Notifications/actions/specs/notificationsActions.spec.js, app/react/Notifications/components/Notifications.js, app/react/Users/Login.js, app/react/Users/ResetPassword.js, nightmare/paths/publishDocument.spec.js, nightmare/paths/publishEntity.spec.js
Fixes issues #1997 #1986 #1825
PR checklist:
QA checklist:
=> 1997 login fixes

package.json, yarn.lock
Fixes issue #
PR checklist:
QA checklist:
=> upgrade underscore.string@3.0.3

app/api/users/routes.js, app/api/users/specs/__snapshots__/routes.spec.js.snap, nightmare/helpers/nightmare.js, nightmare/paths/userCreation.spec.js
Fixes issue #2027 
PR checklist:
QA checklist:
=> new user endpoint now accepts password, basic e2e for user creation

app/api/search/metadataMatchers.js, app/api/search/specs/search.spec.js
Fixes issue #1999 
PR checklist:
QA checklist:
=> fixed error search when and: true is sent without values

app/server.js
Fixes issue #2047 Partially #1985
PR checklist:
QA checklist:
=> Added localhost only option to env vars

app/react/App/scss/modules/_settings.scss, app/react/Markdown/components/Map.js, app/react/Markdown/components/specs/Map.spec.js, app/react/Pages/PageView.js, app/react/Pages/components/PageCreator.js, app/react/Pages/specs/PageView.spec.js, nightmare/paths/pages.spec.js
Fixes issue #1979
PR checklist:
QA checklist:
=> Show documents in sidepanel when clicking map markers in pages

app/api/utils/languageMiddleware.js, app/api/utils/specs/languageFixtures.js, app/api/utils/specs/languageMiddleware.spec.js, app/react/App/App.js, app/react/App/Menu.js, app/react/App/Provider.js, app/react/App/Root.js, app/react/App/RouteHandler.js, app/react/App/specs/RouteHandler.spec.js, app/react/I18N/components/I18NMenu.js, app/react/I18N/components/specs/I18NMenu.spec.js, app/react/I18N/specs/utils.spec.js, app/react/I18N/utils.js, app/react/ServerRouter.js
Fixes issue #2029, #1423
PR checklist:
QA checklist:
=> detect browser language and use it in case no cookie is set

package.json
Fixes issue #
PR checklist:
QA checklist:
=> yarn blank-state now migrates to set the state of the db properly

app/api/entities/routes.js, app/api/entities/specs/routes.spec.js, app/react/Entities/EntitiesAPI.js, app/react/Entities/EntityView.js, app/react/Entities/specs/EntitiesAPI.spec.js, app/react/Entities/specs/EntityView.spec.js
Fixes issue #2065 
PR checklist:
QA checklist:
=> entityView requests entity without unnecessary relationships

app/react/Metadata/components/MetadataFormFields.js
Fixes issue #2073 
PR checklist:
QA checklist:
=> changed media Field to textarea

app/react/App/App.js, app/react/App/scss/elements/_map.scss, app/react/Library/components/specs/__snapshots__/MapView.spec.js.snap, app/react/Map/Map.js, app/react/Markdown/components/Map.js, app/react/Markdown/components/specs/__snapshots__/Map.spec.js.snap, app/react/Routes.js
Fixes issue #2102 
PR checklist:
QA checklist:
=> Added navigation and scroll control

app/react/App/App.js
Fixes issue #
PR checklist:
QA checklist:
=> Fixed so that library does not have a className with "_" in it.

app/react/Markdown/components/SearchBox.js, app/react/Markdown/components/specs/__snapshots__/SearchBox.spec.js.snap
Fixes issue #
PR checklist:
QA checklist:
=> Added btn classes to search box component

app/react/App/App.js
Fixes issue #
PR checklist:
QA checklist:
=> only add page className on PageView section

app/api/templates/routes.js, app/api/templates/specs/__snapshots__/routes.spec.js.snap
Fixes issue #2078 
PR checklist:
QA checklist:
=> content now is allowed as empty

app/api/i18n/routes.js, app/api/migrations/migrations/8-page-languages/index.js, app/api/migrations/migrations/8-page-languages/specs/8-page-languages.spec.js, app/api/migrations/migrations/8-page-languages/specs/fixtures.js, app/api/pages/index.js, app/api/pages/pages.js, app/api/pages/specs/fixtures.js, app/api/pages/specs/pages.spec.js
Fixes issue #2107 
PR checklist:
QA checklist:
=> 2107 languages pages

app/api/settings/settingsModel.js, app/react/Settings/components/FiltersForm.js, app/react/Settings/components/specs/FiltersForm.spec.js
Fixes issue #2112 
PR checklist:
QA checklist:
=> Fixed server validation error when saving filters

app/react/App/scss/elements/_item.scss, app/react/Layout/DocumentsList.js, app/react/Layout/specs/DocumentsList.spec.js, nightmare/helpers/selectors.js
Fixes issue #1421 
PR checklist:
QA checklist:
=> Library and Uploads Load more buttons are now links

app/api/attachments/routes.js, app/react/Viewer/components/Viewer.js
Fixes issue friday hot deploy
PR checklist:
QA checklist:
=> fixed error with paths when deleting documents

app/api/entities/entities.js, app/api/thesauris/specs/thesauris.spec.js, app/api/thesauris/thesauris.js, app/react/Documents/components/SearchText.js, app/react/Documents/components/specs/__snapshots__/SearchText.spec.js.snap, app/react/Metadata/helpers/formater.js, app/react/Metadata/helpers/specs/fixtures.js, app/react/Viewer/components/Connection.js, app/react/Viewer/components/specs/__snapshots__/Connection.spec.js.snap
Fixes issue #2122 
PR checklist:
QA checklist:
=> Fixed how thesauri links are generated

app/react/Metadata/actions/actions.js, app/react/Metadata/actions/specs/actions.spec.js
Fixes issue #1456 
PR checklist:
QA checklist:
=> changing template of an entityy no longer resets the existing data

app/react/Forms/components/MultiSelect.js
Fixes issue #1959 
PR checklist:
QA checklist:
=> Multiselect render selected groups  at the top when colapsed

app/api/migrations/migrator.js, app/server.js, yarn.lock
Fixes issue #2063 
PR checklist:
QA checklist:
=> The server now automatically migrates

app/react/Layout/DocumentsList.js, app/react/Layout/specs/DocumentsList.spec.js
Fixes issue #2119 
PR checklist:
QA checklist:
=> Clicking load more documents wont reload the page anymore

app/react/Relationships/components/LoadMoreRelationshipsButton.js
Fixes issue #2121 
PR checklist:
QA checklist:
=> Fixed css for load more button in relationships

app/api/auth/passport_conf.js, app/api/users/routes.js, app/api/users/specs/__snapshots__/routes.spec.js.snap, app/api/users/specs/__snapshots__/users.spec.js.snap, app/api/users/specs/routes.spec.js, app/api/users/specs/users.spec.js, app/api/users/users.js, app/api/users/usersModel.js, app/react/Auth/actions.js, app/react/Auth/specs/actions.spec.js, app/react/Routes.js, app/react/Users/UnlockAccount.js, app/react/Users/specs/UnlockAccount.spec.js
Fixes issue #2129 
PR checklist:
QA checklist:
=> Account lock after 3 failed login attempts

app/react/ServerRouter.js
Fixes issue #2061 
PR checklist:
QA checklist:
=> random page after base url will now redirect to 404

app/api/attachments/routes.js, app/api/attachments/specs/__snapshots__/routes.spec.js.snap, app/api/documents/routes.js, app/api/documents/specs/__snapshots__/routes.spec.js.snap, package.json, yarn.lock
Fixes issue #2062
PR checklist:
QA checklist:
=> validate _id in documents and attachments download

app/api/attachments/routes.js, app/api/attachments/specs/__snapshots__/routes.spec.js.snap
Fixes issue #
PR checklist:
QA checklist:
=> added AllLanguages property validation to attachments upload endpoint

app/api/api.js, app/api/contact/contact.js, app/api/contact/routes.js, app/api/contact/specs/__snapshots__/routes.spec.js.snap, app/api/contact/specs/contact.spec.js, app/api/contact/specs/fixtures.js, app/api/contact/specs/routes.spec.js, app/api/settings/routes.js, app/api/settings/settingsModel.js, app/api/settings/specs/__snapshots__/routes.spec.js.snap, app/react/Markdown/components/ContactForm.js, app/react/Markdown/components/index.js, app/react/Markdown/components/specs/ContactForm.spec.js, app/react/Markdown/components/specs/__snapshots__/ContactForm.spec.js.snap, app/react/Settings/components/CollectionSettings.js
Fixes issue #2153
PR checklist:
QA checklist:
=> Contact form

app/react/UI/Icon/library.js
Fixes issue #
PR checklist:
QA checklist:
=> added some icons

app/api/relationships/relationships.js
Fixes issue #
PR checklist:
QA checklist:
=> metadata now showing in connections

app/api/documents/specs/__snapshots__/routes.spec.js.snap, app/api/entities/endpointSchema.js, app/api/entities/specs/__snapshots__/routes.spec.js.snap
Fixes issue #
PR checklist:
QA checklist:
=> fixed endpoint validation for entities

app/api/utils/handleError.js, app/api/utils/specs/__snapshots__/handleError.spec.js.snap, app/api/utils/specs/handleError.spec.js
Fixes issue #
PR checklist:
QA checklist:
=> Hidded username and password in the error log

app/api/documents/specs/__snapshots__/routes.spec.js.snap, app/api/entities/endpointSchema.js, app/api/entities/specs/__snapshots__/routes.spec.js.snap
Fixes issue #2172
PR checklist:
QA checklist:
=> added DateRange validation to endpoint schema

app/api/documents/specs/__snapshots__/routes.spec.js.snap, app/api/entities/endpointSchema.js, app/api/entities/specs/__snapshots__/routes.spec.js.snap, app/react/App/scss/elements/_linkField.scss, app/react/App/scss/styles.scss, app/react/Forms/components/LinkField.js, app/react/Forms/components/specs/LinkField.spec.js, app/react/Forms/index.js, app/react/Metadata/actions/actions.js, app/react/Metadata/components/MetadataFormFields.js, app/react/Metadata/helpers/formater.js, app/react/ReactReduxForms/index.js, app/react/Templates/components/Icons.js, app/react/Templates/components/MetadataProperty.js, app/react/Templates/components/TemplateCreator.js, app/react/Templates/components/specs/__snapshots__/Icons.spec.js.snap, app/react/Templates/components/specs/__snapshots__/TemplateCreator.spec.js.snap, app/react/utils/fontawesomeIcons.js
Fixes issue #2088 
PR checklist:
QA checklist:
=> Link field

.codeclimate.yml
Fixes issue #2189 
PR checklist:
QA checklist:
=> new config file for codeclimate

app/api/documents/specs/__snapshots__/routes.spec.js.snap, app/api/entities/endpointSchema.js, app/api/entities/specs/__snapshots__/routes.spec.js.snap, app/api/templates/utils.js, app/api/thesauris/specs/fixtures.js, app/api/thesauris/specs/thesauris.spec.js, app/api/thesauris/thesauris.js, app/react/Metadata/components/MetadataForm.js
Fixes issue #2208 
PR checklist:
QA checklist:
=> 2208 remove values from entities

app/api/documents/specs/__snapshots__/routes.spec.js.snap, app/api/entities/endpointSchema.js, app/api/entities/specs/__snapshots__/routes.spec.js.snap, app/api/entities/specs/entities.spec.js
Fixes issue #2222 
PR checklist:
QA checklist:
=> Fix validation error when publishing entity when empty select fields

app/react/ServerRouter.js, nightmare/paths/login.spec.js
routes
Fixes issue #2188 
PR checklist:
QA checklist:
=> ServerRouter now sets the user into the store before matching the react

app/api/documents/specs/__snapshots__/routes.spec.js.snap, app/api/entities/endpointSchema.js, app/api/entities/specs/__snapshots__/routes.spec.js.snap
Fixes issue #2201 
PR checklist:
QA checklist:
=> allow null as value for date fields

app/api/migrations/migrations/12-add-RTL-to-settings-languages/index.js, app/api/migrations/migrations/12-add-RTL-to-settings-languages/specs/12-add-RTL-to-settings-languages.spec.js
Fixes issue #
PR checklist:
QA checklist:
=> Removed double export from migration.

app/react/Markdown/components/PayPalDonateLink.js, app/react/Markdown/components/specs/PayPalDonateLink.spec.js, app/react/Markdown/components/specs/__snapshots__/PayPalDonateLink.spec.js.snap
Fixes issue #2190 
PR checklist:
QA checklist:
=> Open PayPal donation link in new tab.

app/react/Thesauris/components/ThesauriForm.js, app/react/Thesauris/components/specs/ThesauriForm.spec.js
Fixes issue #2207
PR checklist:
QA checklist:
=> Allow creating and updating thesarus with similar name as template

app/api/documents/specs/__snapshots__/routes.spec.js.snap, app/api/entities/endpointSchema.js, app/api/entities/specs/__snapshots__/routes.spec.js.snap
Fixes issue #2238 
PR checklist:
QA checklist:
=> Fix validation error when saving entity with attachments property

app/api/users/specs/users.spec.js, app/api/users/users.js
Fixes issue #2245
PR checklist:
QA checklist:
=> updating a user will no longer set password to null

app/api/auth/privateInstanceMiddleware.js, app/api/auth/specs/privateInstanceMiddleware.spec.js
Fixes issue #2247 
PR checklist:
QA checklist:
=> allow unlockaccount route for private instances

app/api/socketio/middleware.js, app/api/socketio/specs/middleware.spec.js, app/api/upload/routes.js, app/api/upload/specs/routes.spec.js
Fixes issue #2229 
PR checklist:
QA checklist:
=> Fix error when updating session sockets on multiple clients concurrently

app/api/entities/entities.js, app/api/entities/specs/entities.spec.js
Fixes issue #2260 
PR checklist:
QA checklist:
=> addLanguage now waits until thumbnails are created before continuing to the next batch

app/api/entities/specs/fixtures.js, app/api/relationships/relationships.js, app/api/relationships/relationshipsHelpers.js, app/api/relationships/specs/fixtures.js, app/api/relationships/specs/relationships.spec.js, app/react/Timeline/components/TimelineViewer.js
Fixes issue #2249, #2255
PR checklist:
QA checklist:
=> 2249 purged relationships

app/react/Pages/actions/pageActions.js, app/react/Pages/actions/specs/pageActions.spec.js, app/react/Pages/components/PagesList.js, app/react/Pages/components/specs/PagesList.spec.js
Fixes issue #2252 
PR checklist:
QA checklist:
=> Remove page from page list when deleted

app/api/migrations/migrations/13-geolocation-arrays/index.js, app/api/migrations/migrations/13-geolocation-arrays/specs/__snapshots__/13-geolocation-arrays.spec.js.snap, app/api/migrations/migrations/13-geolocation-arrays/specs/fixtures.js
Fixes issue #
PR checklist:
QA checklist:
=> migration will not fail when an entity has no metadata

app/react/Forms/components/Geolocation.js, app/react/Forms/components/specs/Geolocation.spec.js, app/react/Metadata/components/GeolocationViewer.js, app/react/Metadata/components/specs/GeolocationViewer.spec.js, app/react/Metadata/components/specs/__snapshots__/GeolocationViewer.spec.js.snap
Fixes issue #2277
PR checklist:
QA checklist:
=> 2277 geolocation nulls

README.md
Fixes issue #
PR checklist:
QA checklist:
=> Added e2e troubleshooting instructions

app/api/relationships/relationships.js, app/api/relationships/relationshipsHelpers.js, app/api/relationships/routes.js, app/api/relationships/specs/relationships.spec.js, app/api/relationships/specs/routes.spec.js, app/react/App/scss/layout/_sidepanel.scss
Fixes issue #2279 
PR checklist:
QA checklist:
=> References of unpublished entities wont show anymore

app/react/Map/Map.js, app/react/Map/specs/Map.spec.js
Fixes issue #2283 
PR checklist:
QA checklist:
=> fixed a bug when updating markers the map wont refresh

.codeclimate.yml, .eslintrc, app/api/attachments/specs/attachments.spec.js, app/api/attachments/specs/fixtures.js, app/api/csv/csvLoader.js, app/api/csv/index.js, app/api/csv/specs/csvLoader.spec.js, app/api/csv/specs/fixtures.js, app/api/csv/specs/test.csv, app/api/csv/specs/typeParsers.spec.js, app/api/csv/typeParsers.js, app/api/entities/entitiesModel.js, app/api/entities/specs/entities.spec.js, app/api/entities/specs/fixtures.js, app/api/i18n/index.js, app/api/templates/index.js, app/api/templates/utils.js, app/api/thesauris/index.js, app/api/upload/specs/routes.spec.js, app/api/utils/filters.js, app/shared/templateTypes.js, database/import_csv.js, package.json, yarn.lock
Fixes issue #2243 
PR checklist:
QA checklist:
=> Import csv

app/react/Pages/PageView.js, app/react/Pages/specs/PageView.spec.js
fixes #2209 
PR checklist:
QA checklist:
=> PageView now clears the page state on unmount

app/react/Map/Map.js, app/react/Map/specs/Map.spec.js
fixes #2269 
PR checklist:
QA checklist:
=> Map now always autocenters the first load even if autoCenter is false

app/react/App/Footer.js
fixes #
PR checklist:
QA checklist:
=> update Library footer link

app/api/attachments/routes.js, app/react/Attachments/actions/actions.js, app/react/Attachments/actions/specs/actions.spec.js, app/react/Attachments/components/AttachmentsList.js, app/react/Attachments/components/UploadAttachment.js, app/react/Attachments/components/specs/UploadAttachment.spec.js, app/react/Attachments/components/specs/__snapshots__/AttachmentsList.spec.js.snap, app/react/Metadata/actions/actions.js, app/react/Metadata/actions/specs/actions.spec.js, app/react/Metadata/components/UploadButton.js
fixes #2200 
PR checklist:
QA checklist:
=> fixed bug when uploading an attachment the wrong id was beign use

package.json, yarn.lock
fixes #2301
PR checklist:
QA checklist:
=> cssnano package is not being used, removed

app/api/i18n/translations.js
fixes #2265 
PR checklist:
QA checklist:
=> removed spread operator on a reduce function for performance reasons

app/api/search/routes.js, app/api/search/search.js, app/api/search/specs/__snapshots__/search.searchGeolocations.spec.js.snap, app/api/search/specs/fixturesInheritance.js, app/api/search/specs/routes.spec.js, app/api/search/specs/search.searchGeolocations.spec.js, app/react/App/scss/elements/_map.scss
Fixes issue #
PR checklist:
QA checklist:
=> Inherit geolocation map route

app/react/App/sockets.js, app/react/App/specs/sockets.spec.js, app/react/Connections/actions/specs/actions.spec.js, app/react/Notifications/actions/notificationsActions.js, app/react/Notifications/actions/specs/notificationsActions.spec.js, app/react/index.js, app/react/socket.js
Fixes issue #2183 
PR checklist:
QA checklist:
=> Showing a permanent notification when the connection with

app/api/templates/routes.js, app/api/templates/specs/templates.spec.js, app/api/templates/validateTemplate.js, app/react/Templates/components/FormConfigRelationship.js, app/react/Templates/components/MetadataProperty.js, app/react/Templates/components/MetadataTemplate.js, app/react/Templates/components/ValidateTemplate.js, app/react/Templates/components/specs/MetadataProperty.spec.js, app/react/Templates/components/specs/ValidateTemplate.spec.js, app/react/Templates/components/specs/__snapshots__/MetadataProperty.spec.js.snap
fixes #2306 
PR checklist:
QA checklist:
=> Added validation to templates to prevent duplicated relationship fields

app/api/entities/entities.js, app/api/entities/specs/fixtures.js, app/react/Metadata/helpers/formater.js, app/react/Templates/actions/specs/templateActions.spec.js, app/react/Templates/actions/templateActions.js, app/react/Templates/components/FormConfigRelationship.js, app/react/Templates/components/specs/FormConfigRelationship.spec.js, app/react/Templates/components/specs/__snapshots__/FormConfigRelationship.spec.js.snap
fixes #2312
PR checklist:
QA checklist:
=> 2312 inherit issues

app/react/Map/Map.js, app/react/Map/specs/Map.spec.js
fixes #2316 
PR checklist:
QA checklist:
=> removed map animation on load or when markers change

.gitignore, app/api/config/paths.js, app/api/migrations/migrations/14-separate-custom-uploads-from-documents/index.js, app/api/migrations/migrations/14-separate-custom-uploads-from-documents/specs/14-separate-custom-uploads-from-documents.spec.js, app/api/migrations/migrations/14-separate-custom-uploads-from-documents/specs/fixtures.js, app/api/upload/routes.js, app/api/upload/specs/routes.spec.js, app/api/upload/specs/storageConfig.spec.js, app/api/upload/specs/uploads.spec.js, app/api/upload/storageConfig.js, app/api/upload/uploads.js, app/api/utils/async-fs.js, app/react/Settings/components/CustomUploads.js, app/react/Settings/components/specs/__snapshots__/CustomUploads.spec.js.snap, app/server.js
fixes #2224 
PR checklist:
QA checklist:
=> Separate documents and custom uploads and make documents folder inaccessible

app/api/templates/specs/templates.spec.js, app/react/Metadata/actions/actions.js, app/react/Metadata/actions/specs/actions.spec.js, app/react/Notifications/actions/specs/notificationsActions.spec.js, nightmare/paths/publishDocument.spec.js, nightmare/paths/uploads.spec.js
fixes #2253
PR checklist:
QA checklist:
=> requesting entity before editing

app/api/entities/entities.js
fixes #2318 
PR checklist:
QA checklist:
=> Refactored multiupdate to do it consecutively instead of all at once

app/react/Markdown/components/EntityInfo.js, app/react/Markdown/components/index.js, app/react/Markdown/components/specs/EntityInfo.spec.js, app/react/Markdown/components/specs/__snapshots__/EntityInfo.spec.js.snap, yarn.lock
fixes #2326
PR checklist:
QA checklist:
=> 2326 entity info

app/api/csv/specs/typeParsers.spec.js, app/api/csv/typeParsers.js
fixes #2329 
PR checklist:
QA checklist:
=> date parser now properly parses as UTC

app/api/templates/routes.js, app/api/templates/specs/__snapshots__/routes.spec.js.snap, app/api/templates/specs/templates.spec.js, app/api/templates/validateTemplate.js, app/react/Templates/components/FormConfigRelationship.js, app/react/Templates/components/ValidateTemplate.js, app/react/Templates/components/specs/ValidateTemplate.spec.js
fixes #2328 
PR checklist:
QA checklist:
=> Added validation for required inherit property when property is inherit

app/api/entities/entities.js, app/api/entities/routes.js, app/api/entities/routes.ref.js, app/api/entities/specs/__snapshots__/routes.spec.js.snap, app/api/entities/specs/entities.spec.js, app/api/entities/specs/routes.spec.js, app/api/search/search.js, app/api/search/specs/index.spec.js, app/react/Entities/EntitiesAPI.js, app/react/Entities/specs/EntitiesAPI.spec.js
fixes #1806 
PR checklist:
QA checklist:
=> 1806 delete multiple as post

app/react/Templates/actions/specs/templateActions.spec.js, app/react/Templates/actions/templateActions.js
fixes #2297 
PR checklist:
QA checklist:
=> Clear template form errors when removing field

app/react/Forms/components/MultiSelect.js, app/react/Forms/components/Select.js, app/react/Forms/components/specs/MultiSelect.spec.js, app/react/Forms/components/specs/Select.spec.js, app/react/Metadata/components/MetadataFormFields.js, nightmare/helpers/selectors.js, nightmare/paths/entity.spec.js, nightmare/paths/multiEdit.spec.js, nightmare/paths/publishEntity.spec.js, nightmare/paths/searchFilters.spec.js
fixes #2126
PR checklist:
QA checklist:
=> Thesauri sorting in Select and MultiSelect fields

app/api/templates/routes.js, app/api/templates/specs/__snapshots__/routes.spec.js.snap, app/api/templates/templatesModel.js, app/react/App/scss/elements/_colorpicker.scss, app/react/App/scss/styles.scss, app/react/Forms/components/ColorPicker.js, app/react/Forms/components/specs/ColorPicker.spec.js, app/react/Forms/components/specs/__snapshots__/ColorPicker.spec.js.snap, app/react/Layout/TemplateLabel.js, app/react/Layout/specs/TemplateLabel.spec.js, app/react/Templates/components/MetadataTemplate.js, app/react/Templates/components/specs/MetadataTemplate.spec.js, app/react/Templates/components/specs/__snapshots__/MetadataTemplate.spec.js.snap, app/react/utils/colors.js, package.json, yarn.lock
fixes #2235 #1338 
PR checklist:
QA checklist:
=> Template colors

app/react/App/scss/modules/_markdown.scss, app/react/Markdown/MarkdownViewer.js, app/react/Markdown/components/MarkdownMedia.js, app/react/Markdown/components/specs/MarkdownMedia.spec.js, app/react/Markdown/components/specs/__snapshots__/MarkdownMedia.spec.js.snap, app/react/Markdown/specs/__snapshots__/MarkdownViewer.spec.js.snap, app/react/Metadata/components/Metadata.js, app/react/Metadata/components/specs/__snapshots__/Metadata.spec.js.snap, yarn.lock
fixes #2069
PR checklist:
QA checklist:
=> Show media controls in metadata panel

app/react/BasicReducer/reducer.js, app/react/BasicReducer/specs/reducer.spec.js, app/react/Library/actions/libraryActions.js, app/react/Library/actions/specs/libraryActions.spec.js
fixes #2305
PR checklist:
QA checklist:
=> Update map view when document is updated

app/api/i18n/systemKeys.js, app/react/Forms/components/MultiSelect.js, app/react/Forms/components/specs/MultiSelect.spec.js, app/react/Forms/components/specs/__snapshots__/MultiSelect.spec.js.snap, app/react/Metadata/components/MetadataFormFields.js
fixes #2270
PR checklist:
QA checklist:
=> Display 'no options found' message in empty Multiselect fields

app/api/upload/PDF.js, app/api/upload/routes.js, app/api/upload/specs/1invalid.test.pdf, app/api/upload/specs/PDF.spec.js
fixes #2226
PR checklist:
QA checklist:
=> Proper error logging for failed pdf conversions

app/api/i18n/systemKeys.js, app/react/Library/actions/libraryActions.js, app/react/Library/components/SortButtons.js, app/react/Library/components/specs/SortButtons.spec.js, app/react/Library/components/specs/__snapshots__/SortButtons.spec.js.snap
fixes #1365 
PR checklist:
QA checklist:
=> Hide "sort by relevance" when not in full text search

app/react/App/sockets.js, app/react/App/specs/sockets.spec.js
fixes #2356 
PR checklist:
QA checklist:
=> Increased time from disconnect till message from 3 seconds to 8

app/react/Markdown/components/Counter.js, app/react/Markdown/components/specs/Counter.spec.js, app/react/Markdown/markdownDatasets.js, app/react/Markdown/specs/markdownDatasets.spec.js, package.json, yarn.lock
fixes #1804
PR checklist:
QA checklist:
=> 1804 multiple counter values

app/react/Metadata/helpers/formater.js, app/react/Metadata/helpers/specs/fixtures.js
fixes #2369 
PR checklist:
QA checklist:
=> ignore blank metadata on relationships when formatting inherit values

app/api/csv/typeParsers.js, app/api/csv/typeParsers/geolocation.js, app/api/csv/typeParsers/specs/geolocation.spec.js
fixes #
PR checklist:
QA checklist:
=> geolocation parser for csv import

app/api/search/search.js, app/api/search/specs/__snapshots__/search.searchGeolocations.spec.js.snap, app/api/search/specs/fixturesInheritance.js, app/api/search/specs/search.searchGeolocations.spec.js
fixes #
PR checklist:
QA checklist:
=> will not throw an error when inherited entity does not exist

app/api/search/search.js, app/api/search/specs/__snapshots__/search.searchGeolocations.spec.js.snap, app/api/search/specs/fixturesInheritance.js
fixes #
PR checklist:
QA checklist:
=> prevent crash when inherited entity has no metadata object

app/react/Metadata/helpers/formater.js, app/react/Metadata/helpers/specs/formater.spec.js
fixes #2369 
PR checklist:
QA checklist:
=> when entity metadata has an undefined property, inherit will not throw an error

app/react/Map/helper.js
fixes #2364 
PR checklist:
QA checklist:
=> hack to prevent app crash, this needs a more complex solution

app/api/search/search.js, app/api/search/specs/index.spec.js
fixes #
PR checklist:
QA checklist:
=> Throwing an error when there is an indexation error instead of a console

app/react/Library/components/Doc.js, app/react/Library/components/ViewDocButton.js, app/react/Library/components/specs/Doc.spec.js, app/react/Library/components/specs/ViewDocButton.spec.js, app/react/Library/components/specs/__snapshots__/Doc.spec.js.snap, app/react/Library/components/specs/__snapshots__/ViewDocButton.spec.js.snap, app/react/Relationships/components/LeftRelationship.js, app/react/Relationships/components/RightRelationship.js, app/react/Relationships/components/specs/LeftRelationship.spec.js, app/react/Relationships/components/specs/RightRelationship.spec.js, app/react/Relationships/components/specs/__snapshots__/LeftRelationship.spec.js.snap, app/react/Relationships/components/specs/__snapshots__/RightRelationship.spec.js.snap, app/react/Viewer/ViewDocument.js, app/react/Viewer/actions/specs/uiActions.spec.js, app/react/Viewer/actions/uiActions.js, app/react/Viewer/components/Document.js, app/react/Viewer/components/specs/Document.spec.js, app/react/Viewer/specs/ViewDocument.spec.js
fixes #2237 and #687
PR checklist:
QA checklist:
=> Scroll to text reference when document opened in relationships view

app/api/settings/routes.js, app/api/settings/settingsModel.js, app/api/settings/specs/__snapshots__/routes.spec.js.snap, app/react/App/App.js, app/react/App/Cookiepopup.js, app/react/App/scss/elements/_alerts.scss, app/react/App/specs/Cookiepopup.spec.js, app/react/App/specs/__snapshots__/Cookiepopup.spec.js.snap, app/react/Forms/components/RadioButtons.js, app/react/Forms/components/specs/RadioButtons.spec.js, app/react/Notifications/components/Notification.js, app/react/Notifications/components/specs/Notification.spec.js, app/react/Settings/components/CollectionSettings.js, app/react/Settings/components/specs/CollectionSettings.spec.js, nightmare/helpers/selectors.js
fixes #2372 
PR checklist:
QA checklist:
=> cookie popup

README.md
fixes #
PR checklist:
QA checklist:
=> Updated need for libpng-dev library if yarn install fails.

app/react/App/App.js, app/react/App/Menu.js, app/react/App/RouteHandler.js, app/react/App/specs/RouteHandler.spec.js, app/react/Entities/specs/EntityView.spec.js, app/react/I18N/components/I18NMenu.js, app/react/I18N/components/specs/I18NMenu.spec.js, app/react/I18N/components/specs/__snapshots__/I18NMenu.spec.js.snap, app/react/I18N/specs/utils.spec.js, app/react/I18N/utils.js, app/react/Library/specs/Library.spec.js, app/react/Library/specs/LibraryMap.spec.js, app/react/Pages/specs/EditPage.spec.js, app/react/Pages/specs/NewPage.spec.js, app/react/Pages/specs/PageView.spec.js, app/react/Pages/specs/Pages.spec.js, app/react/RelationTypes/specs/EditRelationType.spec.js, app/react/RelationTypes/specs/NewRelationType.spec.js, app/react/ServerRouter.js, app/react/Settings/components/specs/CustomUploads.spec.js, app/react/Templates/specs/EditTemplate.spec.js, app/react/Templates/specs/NewTemplate.spec.js, app/react/Thesauris/specs/EditThesauri.spec.js, app/react/Thesauris/specs/NewThesauri.spec.js, app/react/Uploads/specs/UploadsRoute.spec.js, app/react/Users/specs/Login.spec.js, app/react/Users/specs/ResetPassword.spec.js, app/react/Users/specs/UnlockAccount.spec.js, app/react/Users/specs/Users.spec.js, app/react/Viewer/specs/ViewDocument.spec.js
fixes #2368 (partially)
PR checklist:
QA checklist:
=> 2368 language flow

app/api/migrations/migrations/15-remove_orphan_relations/index.js, app/api/migrations/migrations/15-remove_orphan_relations/specs/15-remove_orphan_relations.spec.js, app/api/migrations/migrations/15-remove_orphan_relations/specs/fixtures.js, app/api/relationships/relationships.js, app/api/relationships/specs/relationships.spec.js
fixes #2377 
PR checklist:
QA checklist:
=> 2377 orphan relations

app/api/search/metadataAggregations.js, app/react/Forms/components/NestedMultiselect.js, app/react/Library/components/NestedFilter.js
fixes #2336 
PR checklist:
QA checklist:
=> deleted missleading icon, and removed the missing aggregation by default

app/react/Pages/NewPage.js, app/react/ServerRouter.js, app/react/Settings/components/CustomUploads.js, app/react/Settings/components/specs/__snapshots__/CustomUploads.spec.js.snap, app/react/Templates/NewTemplate.js, app/react/Templates/specs/NewTemplate.spec.js, app/react/Users/ResetPassword.js, app/react/Users/specs/ResetPassword.spec.js
fixes #2405
PR checklist:
QA checklist:
=> setpassword route is broken after text flow merge

app/react/Charts/utils/arrayUtils.js, app/react/Markdown/components/BarChart.js, app/react/Markdown/components/ListChart.js, app/react/Markdown/components/PieChart.js, app/react/Markdown/components/PieChartLabel.js, app/react/Markdown/components/index.js, app/react/Markdown/components/specs/BarChart.spec.js, app/react/Markdown/components/specs/PieChart.spec.js, app/react/Markdown/components/specs/PieChartLabel.spec.js, app/react/Markdown/components/specs/__snapshots__/BarChart.spec.js.snap, app/react/Markdown/components/specs/__snapshots__/PieChart.spec.js.snap, app/react/Markdown/components/specs/__snapshots__/PieChartLabel.spec.js.snap, app/react/Markdown/markdownDatasets.js, app/react/Markdown/specs/markdownDatasets.spec.js
PieChart support to show labels instead of tooltip via showLabels="true" prop
PieChart accepts innerRadius and outerRadius props
PieChart automatically filters '0' values
PieChart/BarChart support for max categories to show via maxCategories prop
BarChart vertical layout support via layout='vertical' prop
PR checklist:
QA checklist:
=> Charts enhancements

app/react/App/sockets.js, app/react/App/specs/sockets.spec.js
fixes #2397
PR checklist:
QA checklist:
=> when socket reconnects just after disconnect, do not show disconnect message

app/api/csv/specs/typeParsers.spec.js, app/api/csv/typeParsers.js, app/api/csv/typeParsers/multiselect.js, app/api/csv/typeParsers/select.js, app/api/csv/typeParsers/specs/multiselect.spec.js, app/api/csv/typeParsers/specs/select.spec.js
fixes #2323 
PR checklist:
QA checklist:
=> csv import do not duplicate thesaurus with diferent casing

app/react/Charts/utils/arrayUtils.js, app/react/Markdown/components/BarChart.js, app/react/Markdown/components/ListChart.js, app/react/Markdown/components/PieChart.js, app/react/Markdown/components/specs/BarChart.spec.js, app/react/Markdown/components/specs/ListChart.spec.js, app/react/Markdown/components/specs/__snapshots__/BarChart.spec.js.snap, app/react/Markdown/components/specs/__snapshots__/ListChart.spec.js.snap
=> ListChart and BarChart filterZero prop support.

app/api/entities/entities.js, app/api/templates/specs/fixtures.js, app/api/templates/specs/templates.spec.js, app/api/templates/templates.js
fixes #2349 
PR checklist:
QA checklist:
=> Throwing an error when trying to save a template with swaped names

app/api/users/specs/users.spec.js, app/api/users/users.js
fixes #2422 
PR checklist:
QA checklist:
=> Increase max failed login attempts to 6

app/react/App/scss/layout/_app.scss, app/react/App/scss/layout/_header.scss
fixes #2431 
PR checklist:
QA checklist:
=> css print allow overflowed content to be printed

app/api/csv/specs/typeParsers.spec.js, app/api/csv/typeParsers.js, app/api/csv/typeParsers/relationship.js, app/api/csv/typeParsers/specs/relationship.spec.js
fixes #2437 
PR checklist:
QA checklist:
=> removed regexp title matching for relation import

.eslintrc, app/api/templates/specs/fixtures.js, app/api/templates/specs/templates.spec.js, app/api/templates/templates.js, app/api/templates/validateTemplate.js, app/react/Documents/components/SnippetList.js, app/react/Documents/components/specs/SnippetList.spec.js, app/react/Documents/components/specs/__snapshots__/SnippetList.spec.js.snap, app/react/Layout/ItemSnippet.js, app/react/Layout/specs/ItemSnippet.spec.js, app/react/Metadata/components/MetadataForm.js, app/react/Metadata/components/specs/MetadataForm.spec.js, app/react/Metadata/components/specs/__snapshots__/MetadataForm.spec.js.snap, app/react/Templates/components/FormConfigCommon.js, app/react/Templates/components/MetadataProperty.js, app/react/Templates/components/MetadataTemplate.js, app/react/Templates/components/ValidateTemplate.js, app/react/Templates/components/specs/FormConfigCommon.spec.js, app/react/Templates/components/specs/MetadataProperty.spec.js, app/react/Templates/components/specs/ValidateTemplate.spec.js, app/react/Templates/components/specs/__snapshots__/MetadataProperty.spec.js.snap, app/react/Templates/utils/getFieldLabel.js, app/react/Templates/utils/specs/getFieldLabel.spec.js
fixes #2333
PR checklist:
QA checklist:
=> Allow the label of "Title" field to be changed

app/react/Attachments/components/specs/Attachment.spec.js, app/react/Templates/components/specs/FilterSuggestions.spec.js
=> fixed 2 red tests

app/react/App/scss/modules/_markdown.scss, app/react/Markdown/components/MarkdownMedia.js, app/react/Markdown/components/specs/__snapshots__/MarkdownMedia.spec.js.snap, package.json, yarn.lock
fixes #2391 and #1686
PR checklist:
QA checklist:
=> Fix video player css

app/react/App/scss/elements/_item.scss, app/react/App/scss/layout/_app.scss, app/react/App/scss/layout/_content.scss
fixes #2431 
PR checklist:
QA checklist:
=> fix printing overflow elements on firefox

app/react/App/scss/modules/_document.scss
fixes #2430 
PR checklist:
QA checklist:
=> added inertia on mobile for browsers that support it 

app/react/Settings/components/FiltersForm.js, app/react/Settings/components/specs/FiltersForm.spec.js
fixes #2448 
PR checklist:
QA checklist:
=> do not allow nesting groups on filters

app/api/entities/routes.js, app/api/entities/specs/routes.spec.js, app/api/search/search.js, app/api/search/specs/__snapshots__/search.searchGeolocations.spec.js.snap, app/api/search/specs/fixturesInheritance.js, app/api/search/specs/search.searchGeolocations.spec.js
fixes #2324  #2313 
PR checklist:
QA checklist:
=> Remove private entities from inherited properties when the user is not logged in

app/api/templates/specs/fixtures.js, app/api/templates/specs/templates.spec.js, app/api/templates/templates.js, app/react/Settings/components/EntityTypesList.js, app/react/Templates/actions/templatesActions.js, app/shared/templateTypes.js
fixes #2429 
PR checklist:
QA checklist:
=> deleting a template deletes also references on other template properties

app/react/Viewer/utils/Scroller.js, app/react/Viewer/utils/specs/Scroller.spec.js
fixes #2432 
PR checklist:
QA checklist:
=> Fix page visibility detection and refactor Scroller

app/react/Library/components/FiltersFromProperties.js, app/react/Library/components/SelectFilter.js, app/react/Library/components/specs/SelectFilter.spec.js, app/react/Library/components/specs/__snapshots__/FiltersFromProperties.spec.js.snap, app/react/Library/components/specs/__snapshots__/SelectFilter.spec.js.snap
fixes #2447
PR checklist:
QA checklist:
=> Sort items in multiselect filters when expanded

app/react/Timeline/components/TimelineViewer.js, app/react/Timeline/utils/timelineFixedData.js
fixes #
PR checklist:
QA checklist:
=> Hearings in timelines

app/react/Charts/utils/arrayUtils.js, app/react/Markdown/components/BarChart.js, app/react/Markdown/components/PieChart.js, app/react/Markdown/components/specs/BarChart.spec.js, app/react/Markdown/components/specs/PieChart.spec.js, app/react/Markdown/components/specs/__snapshots__/BarChart.spec.js.snap, app/react/Markdown/components/specs/__snapshots__/PieChart.spec.js.snap
fixes #2469 
PR checklist:
QA checklist:
=> others on charts deactivated by default.

app/api/upload/routes.js, app/api/upload/specs/routes.spec.js
fixes #2472 
PR checklist:
QA checklist:
=> Removed user from public form instance saving.

server.js
fixes #
PR checklist:
QA checklist:
=> activate babel/register cache

app/react/Settings/actions/navlinksActions.js, app/react/Settings/actions/specs/navlinksActions.spec.js, nightmare/helpers/extensions.js, nightmare/helpers/navlinksDSL.js, nightmare/paths/navlinks.spec.js
fixes #2497 
PR checklist:
QA checklist:
=> 2497 menu creation fix

app/react/Markdown/markdownDatasets.js, app/react/Markdown/specs/fixtures.js, app/react/Markdown/specs/markdownDatasets.spec.js, app/react/Pages/PageView.js, app/react/Pages/specs/PageView.spec.js
fixes #2508, fixes #2509
PR checklist:
QA checklist:
=> Page reload and Page Chart issues

app/react/Forms/components/MultiSelect.js, app/react/Forms/components/specs/MultiSelect.spec.js, app/react/Forms/components/specs/__snapshots__/MultiSelect.spec.js.snap, nightmare/paths/searchFilters.spec.js
fixes #2481
PR checklist:
QA checklist:
=> Sort thesauri filters by aggregated count

app/react/Charts/utils/arrayUtils.js, app/react/Charts/utils/specs/arrayUtils.spec.js, app/react/Library/helpers/specs/libraryFilters.spec.js
fixes #2455 
PR checklist:
QA checklist:
=> 2455 fix chart context crash

app/react/Metadata/actions/actions.js, app/react/Viewer/ViewDocument.js, app/react/Viewer/components/Viewer.js, app/react/Viewer/components/specs/Viewer.spec.js, app/react/Viewer/specs/ViewDocument.spec.js
fixes #
PR checklist:
QA checklist:
=> Document reload (server-side render) and Document reupload issues

app/react/Metadata/actions/actions.js, app/react/Metadata/actions/specs/actions.spec.js, app/react/ServerRouter.js
fixes #2515
PR checklist:
QA checklist:
=> 2515 superagent language

app/react/Settings/components/FiltersForm.js, app/react/Settings/components/specs/FiltersForm.spec.js
fixes #2477 
PR checklist:
QA checklist:
=> Fixed bug when adding a filter to the root of the filters configuration

app/react/App/RouteHandler.js
fixes #
PR checklist:
QA checklist:
=> HotFix for not executing getClientState on server side rendering.

app/api/activitylog/activitylogParser.js, app/api/activitylog/specs/activitylogParser.spec.js
fixes #2520
PR checklist:
QA checklist:
=> 2520 activity log bug

app/react/Routes.js
fixes #
PR checklist:
QA checklist:
=> Critical Fix.

app/react/App/Root.js, app/react/Settings/actions/settingsActions.js, app/react/Settings/actions/specs/settingsAction.spec.js, app/react/Timeline/components/TimelineViewer.js
fixes #
PR checklist:
QA checklist:
=> Critical api call fixes

app/react/Map/Map.js, package.json, yarn.lock
fixes #2546
PR checklist:
QA checklist:
=> Revert changes, functionality broken after PR.

nightmare/helpers/commonTests.js, nightmare/helpers/extensions.js, nightmare/helpers/nightmare.js, nightmare/helpers/selectors.js, nightmare/paths/customHomePage.spec.js, nightmare/paths/customHomePageAndStyles.spec.js, nightmare/paths/filters.spec.js, nightmare/paths/metadata.spec.js, nightmare/paths/mobileSidePanels.spec.js, nightmare/paths/pages.spec.js, nightmare/paths/publishDocument.spec.js, nightmare/paths/publishEntity.spec.js, nightmare/paths/smokePrivateInstance.spec.js, nightmare/paths/templates.spec.js, nightmare/paths/translations.spec.js
fixes #2525 
PR checklist:
QA checklist:
=> e2e tests for custom home page and styles

.circleci/config.yml
fixes #
PR checklist:
QA checklist:
=> Update CI config.yml with test performance improvements

app/react/Metadata/components/Metadata.js, app/react/Metadata/components/specs/Metadata.spec.js, app/react/Metadata/components/specs/__snapshots__/Metadata.spec.js.snap
fixes #2362 
PR checklist:
QA checklist:
=> Display icon for relationship fields on cards

app/react/App/scss/layout/_content.scss, app/react/App/scss/layout/_sidepanel.scss, app/react/App/scss/modules/_entity.scss, app/react/Entities/components/EntityViewer.js, app/react/Entities/components/ShowSidepanelMenu.js, app/react/Entities/components/specs/EntityViewer.spec.js, app/react/Entities/components/specs/ShowSidepanelMenu.spec.js, app/react/Entities/components/specs/__snapshots__/ShowSidepanelMenu.spec.js.snap, nightmare/helpers/selectors.js
fixes #2462 
PR checklist:
QA checklist:
=> Allow entity viewer side panel to be closed

.gitignore, app/api/pages/routes.js, app/api/pages/specs/routes.spec.js, app/react/Pages/PageView.js, app/react/Pages/PagesAPI.js, app/react/Pages/specs/PageView.spec.js, app/react/Pages/specs/PagesAPI.spec.js, app/react/Pages/specs/__snapshots__/PageView.spec.js.snap
fixes #2533 
PR checklist:
QA checklist:
Acceptance criteria:
=> 2533 error when wrong id page

app/api/settings/settings.js, app/api/settings/specs/settings.spec.js, app/api/templates/routes.js, app/api/templates/specs/routes.spec.js
=> 1552 name not changed on filters

app/react/Viewer/utils/Text.js, app/react/Viewer/utils/specs/Text.spec.js
fixes #2513 
PR checklist:
QA checklist:
=> Error with text selection when text is at the end of page.

README.md
fixes some pitfalls during installation.
PR checklist:
QA checklist:
=> Add hints to avoid pitfalls to Installation guide

app/react/Map/style.json
fixes #
PR checklist:
QA checklist:
=> Update map tiles url

database/admin_user.sh, database/blank_state.sh, database/dump_blank_state.sh, database/dump_sync_state.sh, database/sync_state.sh, nightmare/fixtures/dump.sh, nightmare/fixtures/restore.sh
fixes #2564
@fititnt @konzz @txau review?
=> Use $DBHOST (if set) instead 127.0.0.1 in database/*.sh (fixes #2564)

app/api/thesauris/specs/thesauris.spec.js, app/api/thesauris/validateThesauri.js
fixes #2490
PR checklist:
QA checklist:
=> Remove duplicity validation fot thesauris

app/api/activitylog/activitylogMiddleware.js, app/api/activitylog/activitylogParser.js, app/api/activitylog/helpers.js, app/api/activitylog/specs/activitylogMiddleware.spec.js, app/api/activitylog/specs/activitylogParser.spec.js, app/api/activitylog/specs/fixturesParser.js, app/react/SemanticSearch/SemanticSearchAPI.js, app/react/SemanticSearch/specs/SemanticSearchAPI.spec.js
fixes #2528 
PR checklist:
QA checklist:
=> Parse and beautify more routes in activity log

.eslintrc, app/api/entities/entities.js, app/api/entities/specs/entities.spec.js, app/api/migrations/migrations/3-fullText_to_per_page/index.js
fixes #2578 #2565
PR checklist:
QA checklist:
=> 2578 entity flaky

database/elastic_mapping.js
fixes #2597 
PR checklist:
QA checklist:
=> Removed non-existing Thai_stemmer

app/api/csv/csvLoader.js, app/api/csv/specs/csvLoader.spec.js, app/api/utils/handleError.js, app/api/utils/specs/handleError.spec.js
fixes #2531 
PR checklist:
QA checklist:
=> Handle mongoose validation errors

app/api/config/paths.js, app/server.js, database/blank_state.sh
1 - the new production build was not showing properly the image on login page, this is because public path was not configured properly.
2 - the blank state script was not using DATBASE_NAME env var.
PR checklist:
QA checklist:
=> Small tweaks

app/react/App/scss/modules/_semantic-search.scss, app/react/SemanticSearch/components/SemanticSearchPanel.js, app/react/SemanticSearch/components/specs/__snapshots__/SemanticSearchPanel.spec.js.snap
fixes #2583
PR checklist:
QA checklist:
=> Add navbar into the semantic search panel to solve close panel issue

app/api/attachments/specs/attachments.spec.js, app/api/attachments/specs/routes.spec.js, app/api/csv/importEntity.js, app/api/csv/specs/csvLoader.spec.js, app/api/csv/specs/csvLoaderLanguages.spec.js, app/api/csv/specs/csvLoaderZip.spec.js, app/api/csv/typeParsers/specs/relationship.spec.js, app/api/entities/entities.js, app/api/entities/specs/entities.spec.js, app/api/evidences_vault/specs/vaultSync.spec.js, app/api/search/entitiesIndex.js, app/api/search/search.js, app/api/search/specs/analyzers.spec.js, app/api/search/specs/fixtures_elastic.js, app/api/search/specs/index.spec.js, app/api/search/specs/search.searchGeolocations.spec.js, app/api/search/specs/search.spec.js, app/api/search/specs/searchDatesFilters.spec.js, app/api/sync/routes.js, app/api/sync/specs/routes.spec.js, app/api/upload/routes.js, app/api/upload/specs/routes.spec.js, app/api/utils/elastic_testing.js, database/reindex_elastic.js
fixes #2612 
PR checklist:
QA checklist:
=> search tests now instantiate its own search object

app/react/App/scss/modules/_document.scss, app/react/Viewer/scss/document.scss
fixes #2486 
PR checklist:
QA checklist:
=> References are now more visible

app/api/entities/entitySchema.js, app/api/entities/specs/entitySchema.spec.js
fixes #2641 
PR checklist:
QA checklist:
=> updated entity validation to allow removed icons

app/api/search/search.js, app/api/search/specs/search.spec.js
fixes #2604 
PR checklist:
QA checklist:
=> 2604 escape quotes

app/react/Library/actions/libraryActions.js, app/react/Library/actions/specs/libraryActions.spec.js, database/elastic_mapping.js
fixes #2603
PR checklist:
QA checklist:
=> 2603 # bug

app/react/Uploads/actions/uploadsActions.js, nightmare/helpers/LibraryDSL.js, nightmare/helpers/extensions.js, nightmare/paths/publishEntity.spec.js
fixes #2644 
PR checklist:
QA checklist:
=> unpublish entity actually sends published: false

app/api/entities/entitySchema.js, app/api/entities/metadataValidators.js, app/api/entities/specs/entities.spec.js, app/api/entities/specs/entitySchema.spec.js
fixes #2673 
PR checklist:
QA checklist:
=> metadata validation now returns error messages

app/api/search/search.js, app/api/search/specs/search.spec.js
fixes #2672
PR checklist:
QA checklist:
=> 2672 escape slash

app/api/entities/entitySchema.js, app/api/entities/specs/entitySchema.spec.js, app/api/utils/jsonSchemas.js, app/react/Timeline/utils/timelineFixedData.js
fixes #2658
PR checklist:
QA checklist:
=> Fexes for nested fields validation

app/api/migrations/migrations/16-sanitize-timestamps/index.js, app/api/migrations/migrations/16-sanitize-timestamps/specs/16-sanitize-timestamps.spec.js, app/api/migrations/migrations/16-sanitize-timestamps/specs/fixtures.js
fixes #2684
PR checklist:
QA checklist:
=> Migration to sanitize timnestamps from string to integers

app/react/Entities/actions/actions.js, app/react/Entities/containers/EntityForm.js, app/react/Metadata/components/MetadataForm.js
fixes #2611 
PR checklist:
QA checklist:
=> Reseting entityform when component is unmounted

app/api/templates/specs/fixtures.js, app/api/templates/specs/templateSchema.spec.js, app/api/templates/specs/templates.spec.js, app/api/templates/specs/validatorFixtures.js, app/api/templates/templateSchema.js, app/api/templates/templates.js
fixes #2668 
PR checklist:
QA checklist:
=> 2668 inheritance deletion bug

app/api/csv/specs/__snapshots__/importFile.spec.js.snap, app/api/csv/specs/csvLoader.spec.js, app/api/csv/specs/fixtures.js, app/api/csv/specs/importFile.spec.js, app/api/csv/specs/test.csv, app/api/csv/specs/typeParsers.spec.js, app/api/csv/typeParsers.js, app/react/Uploads/components/ImportProgress.js, app/react/Uploads/components/specs/ImportProgress.spec.js, app/react/Uploads/components/specs/__snapshots__/ImportProgress.spec.js.snap, app/react/components/Elements/StackTrace.js, app/react/components/Elements/specs/StackTrace.spec.js, app/react/components/Elements/specs/__snapshots__/StackTrace.spec.js.snap
fixes #2687
fixes #2688 
PR checklist:
QA checklist:
=> 2687 csv import numbers

README.md
fixes #
PR checklist:
QA checklist:
=> Removed further README conflicts.

app/react/Markdown/CustomHooks/components/CejilChart.js, app/react/Markdown/CustomHooks/components/CejilChart002.js, app/react/Markdown/CustomHooks/components/cejilChart001.js, app/react/Markdown/CustomHooks/components/specs/CejilChart002.spec.js
fixes #
PR checklist:
QA checklist:
=> Fixes cejil charts

app/react/Forms/components/Geolocation.js, app/react/Forms/components/specs/Geolocation.spec.js
fixes #
PR checklist:
QA checklist:
=> Geolocation field fix after metadata object

app/react/Metadata/components/Metadata.js, app/react/Metadata/components/specs/Metadata.spec.js, app/react/Metadata/components/specs/__snapshots__/Metadata.spec.js.snap, app/react/Metadata/helpers/formater.js, app/react/Metadata/helpers/specs/fixtures.js, app/react/Metadata/helpers/specs/formater.spec.js, app/react/Relationships/components/specs/HubRelationshipMetadata.spec.js, nightmare/paths/entity.spec.js
fixes #2707
PR checklist:
QA checklist:
=> Fixed link implementation in formatter.

app/api/swagger/swaggerconfig.js, package.json, yarn.lock
fixes #2649 
PR checklist:
QA checklist:
=> Fix assets path for swagger on production build

app/api/search/metadataAggregations.js, app/api/search/metadataMatchers.js, app/api/search/search.js, app/api/search/specs/fixtures_elastic.js, app/api/search/specs/search.spec.js
fixes #2715 
PR checklist:
QA checklist:
=> Fixed daterange filters

database/elastic_mapping.js
fixes #
PR checklist:
QA checklist:
=> Increased elasticsearch max index to 2k

app/api/search/documentQueryBuilder.js, app/api/search/specs/fixtures_elastic.js, app/api/search/specs/search.spec.js
fixes #2711 
PR checklist:
QA checklist:
=> Fixed sort function to work with new metadata structure

app/api/templates/specs/templateSchema.spec.js, app/api/templates/templateSchema.js
fixes #2717
fixed #2727
PR checklist:
QA checklist:
=> Fixed issue for id comparation

app/api/migrations/migrations/17-metadata-structured-object/index.js
fixes #2731
Does not address #2719 yet.
PR checklist:
QA checklist:
=> isolate migration 17

app/react/Timeline/utils/timelineFixedData.js
fixes #2713 
PR checklist:
QA checklist:
=> Added requested template id to timelineviewer

app/react/ServerRouter.js
solves an infinite load on server side rendering when a non 500/404 error occurs.
PR checklist:
QA checklist:
=> SSR now responds on all errors

.eslintrc
=> eslint rule to prevent focused tests from beign commited without notice

app/api/entities/entities.js
fixes #2743 
PR checklist:
QA checklist:
=> Decrease batch limit for creating entities in new language

app/react/PDF/components/PDFPage.js, app/react/Templates/components/PropertyOption.js, app/react/Templates/components/specs/PropertyOption.spec.js
fixes #2660
PR checklist:
QA checklist:
=> 2660 disable add relationship button 2

app/api/search/documentQueryBuilder.js, app/api/search/routes.js, app/api/search/specs/search.spec.js, app/react/Settings/Settings.js, app/react/Settings/utils/suggestions.ts, app/react/Thesauri/ThesaurusCockpit.tsx, app/react/Thesauri/reducers/reducer.js, app/react/Thesauri/specs/ThesaurusCockpit.spec.tsx, app/react/Thesauri/types/suggestionResultSchema.ts, app/react/Thesauri/types/suggestionResultType.d.ts, app/react/Thesauri/utils/suggestionQuery.ts, app/shared/types/commonTypes.d.ts, app/shared/types/templateType.d.ts
fixes #
PR checklist:
- [n/a ] Update READ.me ?
- [n/a] Update API documentation ?
QA checklist:
=> Suggestion query cleanup for "Review & Publish" button

.github/workflows/ciconfig.yml
=> github ci config

app/react/Review/scss/review.scss, app/react/Thesauri/Notice.tsx, app/react/Thesauri/ThesaurusCockpit.tsx
fixes #
PR checklist:
QA checklist:
=> Adding a notice box on the one up page

README.md
fixes #
PR checklist:
QA checklist:
=> Update README with new badge

app/api/auth/routes.js, app/api/files/jsRoutes.js, app/api/settings/routes.js, app/api/settings/settings.js, app/api/settings/settingsModel.js, app/api/settings/specs/settings.spec.js, app/api/sync/syncWorker.js
fixes #2540
PR checklist:
QA checklist:
=> sync not returned anymore by default on settings

app/api/csv/specs/__snapshots__/importFile.spec.js.snap, app/api/csv/specs/csvLoader.spec.js, app/api/csv/specs/fixtures.js, app/api/csv/specs/importFile.spec.js, app/api/csv/specs/test.csv, app/api/csv/typeParsers/geolocation.js, app/api/csv/typeParsers/specs/geolocation.spec.js
fixes #2739 
PR checklist:
QA checklist:
=> geolocation objects properly created on csv import

app/react/App/scss/elements/_item.scss, app/react/Layout/DocumentsList.js, app/react/Library/components/DocumentsList.js, app/react/Review/scss/review.scss, app/react/Thesauri/ThesaurusCockpit.tsx
fixes #
PR checklist:
QA checklist:
=> Adding select all to the documentslist and a back button to the multiEditThesaurus

app/react/Users/Login.js, app/react/Users/specs/__snapshots__/Login.spec.js.snap
fixes #1222 
PR checklist:
QA checklist:
=> login form only gets rendered on client

app/api/migrations/migrations/19-rename-uploads-to-files/index.js, app/api/migrations/migrations/19-rename-uploads-to-files/specs/19-rename-uploads-to-files.spec.js
fixes #2809 
PR checklist:
QA checklist:
=> migration 19 fix

app/api/sync/routes.js, app/api/sync/specs/fixtures.js, app/api/sync/specs/routes.spec.js, app/api/sync/specs/syncWorker.spec.js, app/api/sync/syncConfig.js, app/api/sync/synchronizer.js
fixes #2812 
PR checklist:
QA checklist:
=> sync now syncs files belonging to entities

app/react/Settings/components/RelationTypesList.js
fixes #2818
PR checklist:
QA checklist:
=> Fixed relationships section title

app/api/search/specs/search.spec.js, database/elastic_mapping.js, nightmare/paths/connections.spec.js
fixes #2808
PR checklist:
QA checklist:
- [x ] Smoke test the functionality described in the issue
- [x ] Test for side effects
=> Add shards and replicas to ES config

app/react/I18N/specs/t.spec.js, app/react/I18N/t.js
fixes #2831
PR checklist:
QA checklist:
=> translation throws warning instead of fatal error

nightmare/paths/metadataprops.spec.js
fixes metadataprops e2e failing on ci.
PR checklist:
QA checklist:
=> temporary patch for e2e ci

app/react/Charts/utils/arrayUtils.js, app/react/Charts/utils/specs/arrayUtils.spec.js, app/react/Markdown/components/BarChart.js, app/react/Markdown/components/specs/BarChart.spec.js, app/react/Markdown/components/specs/PieChart.spec.js, app/react/Markdown/components/specs/__snapshots__/BarChart.spec.js.snap, app/react/Markdown/components/specs/__snapshots__/PieChart.spec.js.snap
fixes #2839 
fixes #2434
fixes #1898
PR checklist:
QA checklist:
=> 1898 chart options

app/react/App/scss/layout/_header.scss
fixes #2806
PR checklist:
QA checklist:
=> Tweaked CSS for the side menu on mobile

app/react/Charts/utils/arrayUtils.js, app/react/Charts/utils/specs/arrayUtils.spec.js
fixes #2858
PR checklist:
QA checklist:
=> Sort fix for the 'any' aggregation.

app/api/migrations/migrations/24-fix_updatelogs_again/index.js, app/api/migrations/migrations/24-fix_updatelogs_again/specs/24-fix_udaptelogs.spec.js, app/api/migrations/migrations/24-fix_updatelogs_again/specs/fixtures.js, app/api/odm/model.ts, app/react/Charts/utils/arrayUtils.js, app/react/Charts/utils/specs/arrayUtils.spec.js, app/react/ServerRouter.js
fixes #2841
PR checklist:
QA checklist:
=> Proper handling of errors on server side rendering

app/react/ServerRouter.js
fixes #2869
PR checklist:
QA checklist:
=> fixed double response on ssr errors

app/react/Layout/DocumentsList.js, app/react/Layout/specs/DocumentsList.spec.js
fixes #2874 
PR checklist:
QA checklist:
=> Show Select All button only to logged users

app/api/files/routes.ts
=> require _id on files delete route

app/react/Metadata/helpers/formater.js, app/react/Metadata/helpers/specs/formater.spec.js
fixes #2880
PR checklist:
QA checklist:
=> Fix markdown format call from nested field

.gitignore, app/react/Markdown/CustomHooks/components/CejilChart.js, app/react/Markdown/CustomHooks/components/CejilChart002.js, app/react/Markdown/CustomHooks/components/cejilChart001.js
=> Exclude the 'any' keys on Cejil Charts.

app/react/Metadata/helpers/formater.js, app/react/Metadata/helpers/specs/formater.spec.js, nightmare/paths/metadataprops.spec.js
fixes #2884 
PR checklist:
QA checklist:
=> Dont display the preview field if no document associated

app/api/auth/routes.js, app/api/auth/specs/routes.spec.js
The captcha generates a math expression to be solved, it's been discussed that it may be problematic in certain situations.
PR checklist:
QA checklist:
=> Captcha as random letters and numbers instead of a math expresion

app/api/activitylog/activitylogParser.js, app/api/activitylog/helpers.js, app/api/activitylog/migrationsParser.js, app/api/activitylog/specs/activitylogParser.spec.js, app/api/activitylog/specs/migrationsParser.spec.js, app/api/migrations/logger.js, app/api/migrations/migrations/25-sanitize-string-geolocations/index.js, app/api/migrations/migrations/25-sanitize-string-geolocations/specs/25-sanitize-string-geolocations.spec.js, app/api/migrations/migrations/25-sanitize-string-geolocations/specs/fixtures.js, app/api/migrations/specs/logger.spec.js, app/react/Activitylog/components/ActivitylogRow.js, app/react/Activitylog/components/specs/ActivitylogRow.spec.js, app/react/Activitylog/components/specs/__snapshots__/ActivitylogRow.spec.js.snap
fixes #2838 
This pr also adds support for reporting to the activity log from the migrations.
PR checklist:
QA checklist:
=> 2838 migrate geolocation to numbers

app/react/ServerRouter.js
this is a general improvement but its here because of an error that we can not track produced by #2901, this is not a fix.
PR checklist:
QA checklist:
=> SSR error now with more detailed info

app/react/Markdown/components/PieChart.js, app/react/Markdown/components/specs/PieChart.spec.js
fixes #2846
PR checklist:
QA checklist:
=> 2846 extend pluckedcategories to piechart

app/api/auth2fa/routes.ts, app/api/csv/csvLoader.ts
fixes #2920 
PR checklist:
QA checklist:
=> Correct typings on auth2fa and csvloader

README.md
fixes #
PR checklist:
QA checklist:
=> Added fixed version for ES to 7.6.2

app/api/utils/Error.js, app/api/utils/specs/Error.spec.js
fixes #2915 
PR checklist:
QA checklist:
=> handling of normal JS Errors and added specs for createError

app/api/search/search.js, app/api/search/specs/fixtures_elastic.js
fixes #2951 
PR checklist:
QA checklist:
=> hot fix to prevent application crash.

app/api/search/deprecatedRoutes.js
fixes #
PR checklist:
QA checklist:
=> Changed the userSelectedSorting validation from string to boolean

app/api/search/search.js
fixes #
PR checklist:
QA checklist:
=> making sure missing aggregation is always returned

app/api/search/search.js
fixes #2969 
I'm not including tests because it was taking so long, and at this point we need to have this on place.
We can implement proper tests on the associated tech debt issue.
PR checklist:
QA checklist:
=> Prevent application failing if bucket not found

app/react/Viewer/actions/specs/routeActions.spec.js, app/react/Viewer/components/Viewer.js, app/react/Viewer/components/specs/Viewer.spec.js
fixes #2926 
PR checklist:
QA checklist:
=> 2926 opening newly uploaded file in new tab

package.json, yarn.lock
fixes #
PR checklist:
QA checklist:
=> Upgraded webpack bundle analyzer

app/api/csv/typeParsers/relationship.ts, app/api/csv/typeParsers/specs/relationship.spec.js
fixes #2981
PR checklist:
QA checklist:
=> Relationship parser now takes into account content

app/api/csv/csvExporter.ts
fixes #
PR checklist:
QA checklist:
=> HOTFIX CSV Export: error when entity without metadata

app/api/search/search.js
fixes #
PR checklist:
QA checklist:
=> Hot fix to prevent pushing undefined if bucket 'missing' is missing.

package.json
fixes #
PR checklist:
QA checklist:
=> Hotfix for Uwazi version name

app/api/odm/model.ts, app/api/search/entitiesIndex.js, app/api/search/search.js, app/api/search/specs/entitesIndex.spec.js, app/api/search/specs/entitiesIndex.spec.js, app/api/search/specs/fixtures_elastic_errors.js, app/api/search/specs/index.spec.js, app/api/utils/elastic_testing.js, database/reindex_elastic.js
fixes #2993
PR checklist:
QA checklist:
=> 2993 no stop on errors

app/api/search/entitiesIndex.js
fixes #
PR checklist:
QA checklist:
=> Put back errorLog until scripts report output correctly.

app/api/search/entitiesIndex.js, database/reindex_elastic.js
fixes #
PR checklist:
QA checklist:
=> Improved error logs to debug possible problems.

database/reindex_elastic.js
fixes #
PR checklist:
QA checklist:
=> Removed duplicate error log.

app/api/migrations/migrate.js, database/reindex_elastic.js
fixes #
PR checklist:
QA checklist:
=> Close graylog on standalone processes

app/react/Notifications/components/Notification.js, app/react/Notifications/components/specs/Notification.spec.js
fixes #3013
PR checklist:
QA checklist:
=> Fixed notification to be able to work with Nodes and not only strings.

app/react/App/scss/modules/_entity.scss, app/react/Metadata/components/SelectMultiplePanel.js, app/react/Metadata/components/specs/SelectMultiplePanel.spec.js
fixes #2994 
PR checklist:
QA checklist:
=> Added NeedAuthorization to buttons + tweaked the CSS

app/api/templates/specs/templateSchema.spec.ts, app/api/templates/specs/templates.spec.js, app/api/templates/templates.js, app/shared/types/templateSchema.ts
fixes #2988 
PR checklist:
QA checklist:
=> 2988 validate name duplication

app/react/Viewer/PDFView.js, app/react/Viewer/specs/PDFView.spec.js
fixes #3016
PR checklist:
QA checklist:
=> fixed bug on navigating to text reference from outside the document

.github/workflows/deploy_master.yml
This is a small addition so our deployments are easier to handle.
PR checklist:
QA checklist:
=> Add an extra step to master deploy so we always get a latest copy

package.json, yarn.lock
The intent of this PR is just to force cache recreation in CI/CD
PR checklist:
QA checklist:
=> Upgraded slint to force a cache rebuild in CI/CD

package.json, webpack/build.sh, yarn.lock
Yet another fix to master build + eslint upgrade to force cache rebuild
PR checklist:
QA checklist:
=> Yet another fix to master build + eslint upgrade to force cache rebuild

database/elastic_mapping/base_properties.js, database/elastic_mapping/text_sorting.js, database/reindex_elastic.js
fixes #1622 #2050 #3059
While reviewing our mappings testing some sorting issues I found fixing these issues is low hanging fruit.
PR checklist:
QA checklist:
=> Title sorting fixes

app/api/templates/specs/templateSchema.spec.ts, app/api/templates/specs/validatorFixtures.js, app/react/Templates/components/FilterSuggestions.tsx, app/react/Templates/components/SimilarProperty.tsx, app/react/Templates/components/specs/FilterSuggestions.spec.ts, app/shared/propertyTypes.ts, app/shared/types/templateSchema.ts
fixes #3077 
PR checklist:
QA checklist:
=> 3077 allow specific types share names

app/api/sync/specs/fixtures.js, app/api/sync/specs/syncWorker.spec.js, app/api/sync/syncConfig.js
fixes #3093
PR checklist:
QA checklist:
=> Fixed wrong fetch of timestamp

app/api/entities/entities.js, app/api/entities/specs/entities.spec.js, app/api/search/entitiesIndex.js, app/api/search/search.js, app/api/search/specs/entitiesIndex.spec.js
fixes #3100
PR checklist:
QA checklist:
=> reindex by query fix

package.json, run.js
the require throws a proper error if that is the case.
fixes #
PR checklist:
QA checklist:
=> run script now does not check if the file exists,

.github/workflows/deploy_master.yml
fixes #
PR checklist:
QA checklist:
=> package.json now is used to generate cache

.github/workflows/deploy_master.yml
fixes #3116 
PR checklist:
QA checklist:
=> Added run.js and server.js to build cache key

app/api/utils/specs/staticFilesMiddleware.spec.ts, app/api/utils/staticFilesMiddleware.ts, app/server.js
fixes #3119 
PR checklist:
QA checklist:
=> fix url /uploaded_documents matches custom uploads

package.json
fixes #
PR checklist:
QA checklist:
=> version 1.7.0

app/api/migrations/migrations/28-remove_not_allowed_metadata_properties/index.js, app/api/migrations/migrations/28-remove_not_allowed_metadata_properties/specs/28-remove_not_allowed_metadata_properties.spec.js, app/api/migrations/migrations/28-remove_not_allowed_metadata_properties/specs/fixtures.js
fixes #3141
PR checklist:
QA checklist:
=> remove metadata ghost properties from entities

app/react/Layout/DocumentsList.js, app/react/Library/actions/libraryActions.js, app/react/Library/actions/specs/libraryActions.spec.js, app/react/Library/helpers/requestState.js, app/react/Library/helpers/specs/resquestState.spec.js, app/react/Markdown/MarkdownViewer.js, app/react/Markdown/components/ListChart.js, app/react/Markdown/components/SearchBox.js, app/react/Markdown/markdownDatasets.js, app/react/Pages/PageView.js, app/react/Pages/utils/pageItemLists.js, app/react/Uploads/UploadsRoute.js, app/react/Uploads/specs/UploadsRoute.spec.js, app/shared/JSONRequest.js, package.json, yarn.lock
fixes #
PR checklist:
QA checklist:
=> Upgrade rison

app/api/migrations/migrations/28-remove_not_allowed_metadata_properties/index.js, app/api/migrations/migrations/28-remove_not_allowed_metadata_properties/specs/28-remove_not_allowed_metadata_properties.spec.js, app/api/migrations/migrations/28-remove_not_allowed_metadata_properties/specs/fixtures.js
fixes migration 28 for current release branch.
PR checklist:
QA checklist:
=> migration 28 fix for when entity has no template

package.json, yarn.lock
fixes #
PR checklist:
QA checklist:
=> Changed react-redux-form repo to the author's original

app/react/App/scss/modules/_document.scss
fixes #3160 
PR checklist:
QA checklist:
=> Css fix for copy-from panel

app/api/odm/model.ts, app/api/odm/models.ts, app/api/odm/specs/model.spec.ts
fixes #3064 
PR checklist:
QA checklist:
=> updateMany for updateLogs now updates in batches

database/elastic_mapping/base_properties.js
fixes #3213
PR checklist:
QA checklist:
=> 3213 Accents insensitive search

app/react/Timeline/components/TimelineViewer.js
fixes #3183
PR checklist:
QA checklist:
=> Improved conditional to reflect that properties can be empty arrays.

app/react/Layout/Item.js, app/react/Layout/specs/Item.spec.js, app/react/Library/components/TableRow.tsx, app/react/Library/components/specs/TableRow.spec.ts, app/react/Metadata/components/Metadata.js, app/react/Metadata/components/specs/__snapshots__/Metadata.spec.js.snap
fixes #3252
PR checklist:
QA checklist:
=> 3252 card and row namespacing

app/api/files/jsRoutes.js, app/api/files/specs/jsRoutes.spec.js, app/api/odm/specs/model_multi_tenant.spec.ts, app/api/tenants/tenantContext.ts
fixes #3258 
PR checklist:
QA checklist:
=> 3258 remove tenant remotepublic

app/react/App/scss/modules/_metadata-view.scss, app/react/Documents/components/DocumentSidePanel.js, app/react/Entities/components/EntityViewer.js, app/react/Map/Map.js, app/react/Map/specs/Map.spec.js, app/react/Metadata/components/GeolocationViewer.js, app/react/Metadata/components/GroupedGeolocationViewer.tsx, app/react/Metadata/components/Metadata.js, app/react/Metadata/components/Pill.tsx, app/react/Metadata/components/ShowMetadata.js, app/react/Metadata/components/specs/GeolocationViewer.spec.js, app/react/Metadata/components/specs/GroupedGeolocationViewer.spec.tsx, app/react/Metadata/components/specs/Metadata.spec.js, app/react/Metadata/components/specs/Pill.spec.tsx, app/react/Metadata/components/specs/__snapshots__/GeolocationViewer.spec.js.snap, app/react/Metadata/components/specs/__snapshots__/ShowMetadata.spec.js.snap, app/react/Metadata/containers/specs/__snapshots__/FormatMetadata.spec.js.snap, app/react/Metadata/helpers/formater.js, app/react/Templates/components/FormConfigInput.js, app/react/Templates/components/FormConfigRelationship.js, app/react/Templates/scss/templates.scss
fixes #3098 
PR checklist
QA checklist:
=> 3098 group geolocations

app/react/Library/actions/libraryActions.js, app/react/Library/actions/specs/libraryActions.spec.js, app/react/Library/components/LibraryModeToggleButtons.js
fixes #3244
PR checklist:
QA checklist:
=> 3244 rison decoding errors

app/react/Settings/components/AccountSettings.js, app/react/Settings/components/specs/AccountSettings.spec.js
fixes #3260
PR checklist:
QA checklist:
=> 3260-email-field-not-editable

database/elastic_mapping/mappings.ts
fixes #3276
PR checklist:
QA checklist:
=> made markdowns use same mapping as text fields

app/api/users/specs/users.spec.js, app/api/users/users.js, app/react/Attachments/components/FileList.tsx, app/react/Attachments/components/specs/FileList.spec.tsx
fixes #3229 
PR checklist:
QA checklist:
=> Added support for ordering files by language and updated tests

app/react/Forms/components/MultiSelect.tsx, app/react/Forms/components/specs/MultiSelect.spec.js, app/react/Forms/components/specs/MultiSelectTristate.spec.tsx
fixes #2942 
fixes #3215 
fixes #3280 
fixes #3001 
fixes your cousin's car
PR checklist:
QA checklist:
=> Fixed bug when deselecting an option from the multiselect

app/react/App/Menu.js, app/react/App/specs/Menu.spec.js, app/react/Library/components/LibraryModeToggleButtons.js, app/react/Routes.js, app/react/Settings/components/CollectionSettings.js, app/react/Settings/components/specs/CollectionSettings.spec.js, app/shared/types/settingsSchema.ts, e2e/suites/default-library-view.test.ts
fixes #3269 
PR checklist:
QA checklist:
=> 3269 configure default library view

app/api/auth/routes.js, app/api/config.ts
=> session secret as an env var on production

app/api/contact/contact.js, app/api/contact/specs/contact.spec.js, app/api/users/specs/__snapshots__/users.spec.js.snap, app/api/users/specs/users.spec.js, app/api/users/users.js, app/api/utils/mailer.js, app/react/Settings/components/CollectionSettings.js, app/shared/types/settingsSchema.ts, app/shared/types/settingsType.d.ts
fixes #2912 
PR checklist:
QA checklist:
=> Added support for sender email

app/api/csv/specs/typeFormatters.spec.ts, app/api/csv/typeFormatters.ts
fixes #3272 
PR checklist:
QA checklist:
=> Map date-fns format to momentjs on csv export

app/api/utils/Error.js, app/api/utils/handleError.js, app/api/utils/specs/Error.spec.js, app/api/utils/specs/__snapshots__/handleError.spec.js.snap, app/api/utils/specs/handleError.spec.js
fixes #3296 
PR checklist:
QA checklist:
=> 3296 augment error log

app/api/utils/parseQueryMiddleware.ts, app/api/utils/specs/parseQueryMiddleware.spec.ts
fixes #3265 
PR checklist:
QA checklist:
=> Avoid JSON.parse-ing the search term on the query

app/api/search/search.js
fixes #
PR checklist:
QA checklist:
=> improve aggregations postprocess performance

app/react/App/scss/modules/_document.scss
fixes #3338 
PR checklist:
QA checklist:
=> Fixed scroll on library

app/react/Forms/components/NumericRange.js, app/react/Forms/components/specs/NumericRange.spec.js
fixes #3004 
fixes #2978
PR checklist:
QA checklist:
=> Fix empty limit set to empty string on numeric range

.github/workflows/ci_e2e_puppeteer.yml, .github/workflows/ci_e2e_suite1.yml, .github/workflows/ci_e2e_suite2.yml, .github/workflows/ci_unit_tests.yml
fixes #
PR checklist:
QA checklist:
=> Trying to fix poppler install on CI

.github/workflows/ci_e2e_puppeteer.yml, .github/workflows/ci_e2e_suite1.yml, .github/workflows/ci_e2e_suite2.yml, .github/workflows/ci_unit_tests.yml, README.md
fixes #
PR checklist:
QA checklist:
=> Upgrade elastic

app/api/csv/specs/typeFormatters.spec.ts, app/api/csv/typeFormatters.ts, app/api/entities/metadataValidators.js, app/api/entities/specs/entitySchema.spec.ts, app/react/App/scss/elements/_controls.scss, app/react/Forms/components/Numeric.js, app/react/Forms/components/specs/Numeric.spec.js, app/react/Metadata/components/Metadata.js, app/react/Metadata/helpers/formater.js
fixes #3331 
PR checklist:
QA checklist:
=> Change numeric field input type to numeric, add support for value 0

app/api/search/entitiesIndex.js, app/api/search/specs/entitiesIndex.spec.js
fixes #3357 
PR checklist:
QA checklist:
=> Fixed error when adding a property to a blank state uwazi

app/react/App/scss/modules/_usergroups.scss
fixes #
PR checklist:
QA checklist:
=> hide temporarily user groups tab

app/react/App/scss/modules/_usergroups.scss, package.json
This includes the hiding of the user groups on DEV after being merged to RELEASE
PR checklist:
QA checklist:
=> Hide user groups to DEVELOPMENT

.github/workflows/ci_e2e_puppeteer.yml, .github/workflows/ci_e2e_suite1.yml, .github/workflows/ci_e2e_suite2.yml, .github/workflows/ci_eslint.yml, .github/workflows/ci_ts_types.yml, .github/workflows/ci_unit_tests.yml, .github/workflows/security_audit.yml
this is a test to trigger github actions on PRs coming from forks
=> trigger github actions on PR

app/react/Templates/actions/specs/templateActions.spec.js, app/react/Templates/actions/templateActions.js
fixes #3387
PR checklist:
QA checklist:
=> Removed inserting property of template properties

app/api/activitylog/activitylogMiddleware.js, app/api/users/specs/users.spec.js, app/api/users/users.js
fixes #3209
PR checklist:
QA checklist:
=> [HOTFIX] password update

package.json
fixes #
PR checklist:
QA checklist:
=> Updated hotfix version.

app/api/settings/settings.ts, app/react/Routes.js, app/react/Settings/SettingsAPI.ts
fixes #3268 
PR checklist:
QA checklist:
=> Fix infinite redirect when home_page has been set to /

.github/workflows/ci_e2e_puppeteer.yml, .github/workflows/ci_e2e_suite1.yml, .github/workflows/ci_e2e_suite2.yml, .github/workflows/ci_eslint.yml, .github/workflows/ci_ts_types.yml, .github/workflows/ci_unit_tests.yml, .github/workflows/security_audit.yml
=> only run on pull_request, except main branches

app/api/entities/specs/entitySchema.spec.ts, app/api/templates/routes.js, app/api/templates/specs/routes.spec.js, app/api/templates/specs/templates.spec.js, app/api/templates/templates.ts, e2e/suites/copy-from.test.ts, package.json
fixes #3394 
PR checklist:
QA checklist:
=> moved update mapping to after the reindex of update template

app/api/entities/specs/entitySchema.spec.ts, app/api/templates/routes.js, app/api/templates/specs/routes.spec.js, app/api/templates/specs/templates.spec.js, app/api/templates/templates.ts, e2e/suites/copy-from.test.ts, package.json
fixes #3394
PR checklist:
QA checklist:
=> 3394 update mapping bug

app/shared/types/userGroupSchema.ts, app/shared/types/userGroupType.d.ts
fixes #
PR checklist:
QA checklist:
=> Fix usergroup id property type

database/reindex_elastic.js
fixes #
PR checklist:
QA checklist:
=> Reduced batch size.

nightmare/helpers/connectionsDSL.js, nightmare/suite1/connections.spec.js
fixes e2e connections flaky test
PR checklist:
QA checklist:
=> more specific dom search text to match results

app/api/migrations/migrate.ts, app/api/odm/DB.ts, database/reindex_elastic.js
Largely fixes #3365 (though more robust error handling and messages would still be a good idea).
PR checklist:
QA checklist:
=> Made migration script use DB authentication and host if available

.github/workflows/ci_e2e_puppeteer.yml
fixes #3410 
PR checklist:
QA checklist:
=> Fixes checking out the submodules on CI

app/api/search/deprecatedRoutes.js, app/api/search/search.js, app/api/search/specs/index.spec.js, app/api/search/specs/routes.spec.js, app/api/search/specs/search.spec.js, database/reindex_elastic.js, package.json
fixes #
PR checklist:
QA checklist:
=> Hotfix snippets search into Release

app/api/users/specs/users.spec.js, app/api/users/users.js
fixes #3426 
PR checklist:
QA checklist:
=> 3426 new user without password error

app/api/search/entitiesIndex.js, app/api/utils/error_handling_middleware.js
fixes #3440 
PR checklist:
QA checklist:
=> updateMapping and reindex error now will be a 500

app/react/Library/components/LibraryModeToggleButtons.js, app/react/Library/components/MapView.js, app/react/Map/Map.js, app/react/Map/Markers.js, app/react/Map/helper.js, app/react/Map/specs/Markers.spec.js, app/react/Map/specs/__snapshots__/helper.spec.js.snap, app/react/Map/specs/helper.spec.js, app/react/Markdown/components/Map.js, app/react/Markdown/components/specs/__snapshots__/Map.spec.js.snap, package.json, yarn.lock
fixes #3466 
PR checklist:
QA checklist:
=> Removed toJS calls on getMarkers and unnecessary find calls

app/api/migrations/migrator.js, app/api/migrations/specs/checkMigrationsNumber.spec.js
fixes #
PR checklist:
QA checklist:
=> Test to check that the migrations have unique deltas

app/react/Library/components/specs/TableRow.spec.ts
fixes #3502
PR checklist:
QA checklist:
=> Fixed failing test according to timezone

app/react/Templates/components/Icons.js, app/react/Templates/components/specs/__snapshots__/Icons.spec.js.snap
fixes #2519 
PR checklist:
QA checklist:
=> Changed relationship icon from link to exchange-alt

app/api/files/routes.ts, app/api/files/specs/routes.spec.ts, app/react/App/Footer.js, app/react/Attachments/components/Attachment.js, app/react/Attachments/components/AttachmentsList.js, app/react/Attachments/components/File.tsx, app/react/Attachments/components/FileList.tsx, app/react/Attachments/components/specs/Attachment.spec.js, app/react/Attachments/components/specs/AttachmentsList.spec.js, app/react/Attachments/components/specs/File.spec.tsx, app/react/Attachments/components/specs/FileList.spec.tsx, app/react/Attachments/components/specs/__snapshots__/AttachmentsList.spec.js.snap, app/react/Auth/components/NeedAuthorization.tsx, app/react/Auth/components/specs/NeedAuthorization.spec.js, app/react/Documents/components/DocumentSidePanel.js
fixes #3507
PR checklist:
QA checklist:
=> Enable supporting files to collaborator role

app/api/search/documentQueryBuilder.js, app/api/search/specs/permissionsFilters.spec.ts, app/api/search/specs/permissionsFiltersFixtures.ts
fixes #3540
PR checklist:
QA checklist:
=> 3540 type aggregations based on read access to entities

app/react/Documents/components/DocumentSidePanel.js, app/react/Documents/components/scss/toc.scss
fixes #3535 
Recreated from: #3545
PR checklist:
QA checklist:
=> Added styles to fix copy from layout on entity metadata (recreated)

app/api/entities/routes.js, app/api/entities/specs/__snapshots__/deprecatedRoutes.spec.js.snap, app/api/entities/specs/deprecatedRoutes.spec.js, app/api/entities/specs/routes.spec.ts, app/api/search/documentQueryBuilder.js, app/api/search/search.js, app/api/search/specs/permissionsFilters.spec.ts, app/react/Connections/actions/actions.js, app/react/Connections/actions/specs/actions.spec.js, app/react/Documents/specs/DocumentsAPI.spec.js, app/react/Entities/EntitiesAPI.js, app/react/Entities/specs/EntitiesAPI.spec.js, app/react/Metadata/components/SearchEntities.tsx, app/react/Metadata/components/specs/SearchEntities.spec.tsx, app/react/Relationships/actions/actions.js, app/react/Relationships/actions/specs/actions.spec.js, app/react/Search/SearchAPI.js, app/react/Search/specs/SearchAPI.spec.js, app/react/Uploads/actions/uploadsActions.js, app/react/Viewer/actions/documentActions.js, app/react/Viewer/actions/specs/documentActions.spec.js, app/react/utils/RequestParams.ts, app/shared/types/searchParams.d.ts, app/shared/types/searchParams.ts
fixes #3541
PR checklist:
QA checklist:
=> search does not return permissions by default

app/api/settings/settings.ts, app/api/settings/specs/settings.spec.ts
fixes #3506 
fixes #3363
PR checklist:
QA checklist:
=> Adjust default value for map starting point

app/api/entities/entities.js, app/api/entities/entitiesModel.ts, app/api/entities/specs/entities.spec.js, app/api/entities/specs/entitiesModel.spec.js, app/api/entities/specs/fixtures.js, app/api/odm/ModelWithPermissions.ts, app/api/odm/specs/ModelWithPermissions.spec.ts, app/api/permissions/specs/entitiesPermissions.spec.ts
fixes #3587
PR checklist:
QA checklist:
=> 3587 collaborator removes relationships error

app/react/App/scss/layout/_modal.scss
fixes #3591 
PR checklist:
QA checklist:
=> Added scroll to language translation modal

app/api/permissions/routes.ts, app/api/permissions/specs/routes.spec.ts, app/react/Permissions/PermissionsAPI.ts, app/react/Permissions/specs/PermissionsAPI.spec.ts, app/react/utils/api.js
fixes #3589
PR checklist:
QA checklist:
=> 3589 get permissions for thousands entities

app/api/entities/entities.js, app/api/entities/specs/entities.spec.js, app/api/permissions/entitiesPermissions.ts, app/api/permissions/specs/entitiesPermissions.spec.ts, app/api/permissions/specs/routes.spec.ts, app/react/App/scss/modules/_share-modal.scss, app/react/Metadata/components/MetadataFormButtons.js, app/react/Metadata/components/SelectMultiplePanel.js, app/react/Metadata/components/specs/MetadataFormButtons.spec.js, app/react/Permissions/actions/actions.ts, app/react/Permissions/actions/specs/actions.spec.ts, app/react/Permissions/components/MemberListItemPermission.tsx, app/react/Permissions/components/MembersList.tsx, app/react/Permissions/components/ShareEntityModal.tsx, app/react/Permissions/components/specs/MemberList.spec.tsx, app/react/Permissions/components/specs/ShareEntityModal.spec.tsx, app/react/Uploads/actions/specs/uploadsActions.spec.js, app/react/Uploads/actions/uploadsActions.js, app/shared/types/connectionType.d.ts, app/shared/types/entityType.d.ts, app/shared/types/permissionSchema.ts, app/shared/types/permissionType.d.ts, e2e/suites/share-publicly.test.ts, nightmare/helpers/extensions.js, nightmare/helpers/selectors.js, nightmare/suite1/multiEdit.spec.js, nightmare/suite1/publishDocument.spec.js, nightmare/suite2/publishEntity.spec.js
fixes #3570 
fixes #3573 
PR checklist:
QA checklist:
=> 3570 remove publish buttons

app/react/Metadata/components/MetadataFormButtons.js
fixes #3528
PR checklist:
QA checklist:
=> Replace copy from icon in library

app/api/activitylog/helpers.js, app/api/activitylog/specs/activitylogParser.spec.js
fixes #3615
PR checklist:
QA checklist:
=> Consider public type in activity log

.github/workflows/ci_ts_emit_check.yml, emitSchemaTypes.js
fixes #
PR checklist:
QA checklist:
=> GH check for emit-types

app/react/Documents/components/DocumentSidePanel.js, app/react/Documents/components/specs/DocumentSidePanel.spec.js, app/react/Entities/components/EntityViewer.js, app/react/Entities/components/specs/EntityViewer.spec.js, app/react/Relationships/utils/relationshipsUtils.ts, app/react/Relationships/utils/specs/relationshipsUtils.spec.ts, app/react/Users/components/PermissionsList.tsx
fixes #3632
PR checklist:
QA checklist:
=> 3632 Filtering relationships based on hubs - PDF View

app/api/entities/entities.js, app/api/entities/specs/entities.spec.js
fixes #3606 
PR checklist:
QA checklist:
=> 3606 disallow permissions setting entities api

app/react/Metadata/components/ShowMetadata.js, app/react/Metadata/components/specs/ShowMetadata.spec.js, app/react/Metadata/components/specs/__snapshots__/ShowMetadata.spec.js.snap
fixes #3616 
PR checklist:
QA checklist:
=> Allow hidding label in sidebar and entity view

app/api/auth/routes.js, e2e/helpers/elastichelpers.ts, e2e/suites/public-form.test.ts
fixes #
PR checklist:
QA checklist:
=> Public form e2e

app/react/App/scss/elements/_tooltip.scss, app/react/App/scss/modules/_settings-metadata.scss
fixes #3530 
PR checklist:
QA checklist:
=> Style tooltip

app/api/migrations/migrations/38-denormalize-inherited/index.js, app/api/migrations/migrations/38-denormalize-inherited/specs/38-denormalize-inherited.spec.js, app/api/migrations/migrations/38-denormalize-inherited/specs/fixtures.js, package.json
fixes #
PR checklist:
QA checklist:
=> migration 38 hotfix

app/react/Templates/components/TemplateCreator.js, app/react/Templates/components/specs/__snapshots__/TemplateCreator.spec.js.snap, nightmare/suite1/metadataprops.spec.js
fixes #3659 
PR checklist:
QA checklist:
=> Hide unique-id field

e2e/suites/public-form.test.ts
fixes #3685
PR checklist:
QA checklist:
=> test public form without SSR

app/api/entities/entities.js, app/api/entities/entitiesModel.ts, app/api/entities/specs/entities.spec.js, app/api/migrations/migrations/41-default-metadata-object/index.js, app/api/migrations/migrations/41-default-metadata-object/specs/41-default-metadata-object.spec.js, app/api/migrations/migrations/41-default-metadata-object/specs/fixtures.js
fixes #3661 
PR checklist:
QA checklist:
=> 3661 default metadata

database/elastic_mapping/mappings.ts
fixes #3693 
PR checklist:
QA checklist:
=> 3693 hotfix for makrdown mapping

.codeclimate.yml
fixes #
PR checklist:
QA checklist:
=> changed eslint on codeclimate config to 7

.eslintrc, package.json, yarn.lock
fixes #
PR checklist:
QA checklist:
=> eslint ecma 2020 in favor of babel/eslint-parser

e2e/suites/copy-from.test.ts
fixes #3660 
PR checklist:
QA checklist:
=> copy-from e2e remove waitFor specific times

app/api/entities/entities.js, app/api/entities/index.js, app/api/entities/specs/entities.spec.js, app/api/entities/specs/validateEntity.spec.ts, app/api/entities/validateEntity.ts, app/api/entities/validation/metadataValidators.js, app/api/entities/validation/validateEntityData.ts, app/api/entities/validation/validateEntitySchema.ts, app/api/entities/validation/validateMetadataField.ts, app/shared/types/entitySchema.ts
fixes #3472 
PR checklist:
QA checklist:
=> separation of schema and data validations

database/elastic_mapping/elasticMapFactory.ts, database/reindex_elastic.js
fixes #3701
PR checklist:
QA checklist:
=> 3701 Elastic mapping improvements

app/api/utils/specs/staticFilesMiddleware.spec.ts, app/api/utils/staticFilesMiddleware.ts
fixes #3729
PR checklist:
QA checklist:
=> 3729 - Old file routes should return a 404

app/react/App/scss/elements/_item.scss, app/react/Layout/Item.js
fixes #3713
PR checklist:
QA checklist:
=> 3713 lengthy name of template overflows card

app/react/PDF/components/PDF.js, app/react/PDF/components/specs/PDF.spec.js, webpack/config.js
fixes #3723 
PR checklist:
QA checklist:
=> 3723 korean letter rendering in legacy pdf format

app/api/entities/denormalize.ts, app/api/entities/entities.js, app/api/entities/specs/denormalization.spec.ts, app/api/i18n/specs/translations.spec.js, app/api/i18n/translations.js, app/api/migrations/migrations/44-default_null_inheritedValue_to_empty_array/index.js, app/api/migrations/migrations/44-default_null_inheritedValue_to_empty_array/specs/44-default_null_inheritedValue_to_empty_array.spec.js, app/api/migrations/migrations/44-default_null_inheritedValue_to_empty_array/specs/fixtures.js, app/api/search/search.js, app/api/templates/templates.ts, app/api/thesauri/index.js, app/api/thesauri/thesauri.js
fixes #3735 
PR checklist:
QA checklist:
=> 3735 denormalization followup

app/api/csv/csvExporter.ts, app/api/csv/specs/csvExporter.spec.ts, app/api/csv/specs/exportCsvFixtures.ts, app/api/csv/specs/typeFormatters.spec.ts, app/api/csv/typeFormatters.ts
fixes #3778
PR checklist:
QA checklist:
=> 3778 support for generatedId field type at exporting

app/react/Metadata/helpers/formater.js, app/react/Metadata/helpers/specs/fixtures.js
fixes #3759 
PR checklist:
QA checklist:
=> Add placeholder object to make indexes match on label lookup

app/react/Pages/EditPage.js, app/react/Pages/specs/EditPage.spec.js
fixes #3774 
PR checklist:
QA checklist:
=> 404 for missing pages

app/react/Library/components/TableCell.tsx, app/react/Library/components/specs/TableCell.spec.tsx
fixes #3793
PR checklist:
QA checklist:
=> 3793 generated id at table view

app/api/search/search.js, app/api/search/specs/fixtures_elastic.js, app/api/search/specs/routes.spec.ts, app/api/search/specs/search.spec.js, package.json
fixes #
PR checklist:
QA checklist:
=> Hotfix search lookup master

app/react/App/Footer.js
fixes #3810 
PR checklist:
QA checklist:
=> Changed lettercase on footer tooltip

app/api/config.ts
fixes #3806 
PR checklist:
QA checklist:
=> mongo uri support

app/react/App/Menu.js, app/react/App/scss/layout/_content.scss, app/react/Layout/DocumentCounter.tsx, app/react/Layout/DocumentsList.js, app/react/Layout/specs/DocumentCounter.spec.tsx, app/react/Library/components/FiltersForm.js, app/react/Library/components/LibraryFilters.js, app/react/Metadata/components/SelectMultiplePanel.js, app/react/Pages/components/PageCreator.tsx, app/react/SemanticSearch/components/SemanticSearchMultieditPanel.js, app/react/SemanticSearch/components/specs/__snapshots__/SemanticSearchMultieditPanel.spec.js.snap, app/react/Settings/components/EntityTypesList.js, app/react/Settings/components/FiltersForm.js, app/react/Templates/components/FormConfigMultimedia.js, app/react/Templates/components/FormConfigNested.js, app/react/Templates/components/PropertyConfigOptions.js, app/react/Templates/components/specs/__snapshots__/FormConfigMultimedia.spec.js.snap, app/react/Templates/components/specs/__snapshots__/PropertyConfigOptions.spec.js.snap, app/react/Uploads/components/UploadBox.js, app/react/Uploads/components/UploadsHeader.js, e2e/suites/default-library-view.test.ts, e2e/suites/entity.test.ts, e2e/suites/metadataprops.test.ts, e2e/suites/navlinks.test.ts, e2e/suites/public-form.test.ts, e2e/suites/share-publicly.test.ts, nightmare/helpers/selectors.js
fixes #3512
PR checklist:
QA checklist:
=> 3512 - Update UI to show entities as such and not as 'documents'

app/api/entities/routes.js, app/api/entities/specs/deprecatedRoutes.spec.js, app/api/search/search.js, app/api/thesauri/specs/fixtures.ts, app/api/thesauri/specs/thesauri.spec.js, app/api/thesauri/thesauri.js
fixes #3786
PR checklist:
QA checklist:
=> template to thesauri count now with elastic aggs

app/api/search/routes.ts, app/api/search/search.js, app/api/search/specs/routes.spec.ts, app/api/search/specs/search.spec.js, app/react/Metadata/actions/actions.js, app/react/Metadata/components/MetadataFormFields.js, database/elastic_mapping/base_properties.js, database/elastic_mapping/settings.js
fixes #3782
PR checklist:
QA checklist:
=> 3782 - Lookup not working for partial words in some scenarios

database/elastic_mapping/dynamic_templates.js
fixes #3807 
PR checklist:
QA checklist:
=> Disabled mappings

app/api/migrations/migrations/48-fix_migration_45_inherit_property/index.js, app/api/migrations/migrations/48-fix_migration_45_inherit_property/specs/48-fix_migration_45_inherit_property.spec.js, app/api/migrations/migrations/48-fix_migration_45_inherit_property/specs/fixtures.js
fixes #3824 
PR checklist:
QA checklist:
=> fix migration 45

app/api/utils/handleError.js, app/api/utils/specs/handleError.spec.js, app/shared/JSONRequest.js
fixes #3768 
PR checklist:
QA checklist:
=> sync error on 404 response

app/react/Metadata/helpers/formater.js, app/react/Metadata/helpers/specs/formater.spec.js
fixes #3842 
PR checklist:
QA checklist:
=> App crash on empty inherited value

app/react/App/Footer.js
fixes #3712 
PR checklist:
QA checklist:
=> Added link to settings account for settings button on the footer

app/api/migrations/migrations/49-add_system_key_translations/index.js, app/api/migrations/migrations/49-add_system_key_translations/specs/49-add_system_key_translations.spec.js, app/api/migrations/migrations/49-add_system_key_translations/specs/fixtures.js, app/api/migrations/migrations/49-add_system_key_translations/system_keys.csv, app/react/Pages/components/PageCreator.tsx
fixes #3836 
NOTE!: As part of this QA, it is necessary to look for feedback from the product team about the actual system keys we want to input, and modify the system_keys.csv accordingly.
PR checklist:
QA checklist:
=> Migration for missing system keys

app/api/odm/specs/DB.spec.ts, app/api/utils/createMongoInstance.js, app/api/utils/testing_db.ts, app/jest.server.config.js, app/jestServerGlobalSetup.js, database/download_mongo_prebuilt.js, package.json, yarn.lock
fixes #3766 
fixes having a specific mongo version for testing that can be changed instead of the default, we where using 4.0, in the readme we recomend 4.2, im using this oportunity to upgrade it to the latest 4 version 4.4.8
=> now in memory mongo has a fixed version

app/react/App/scss/modules/_search.scss, app/react/App/scss/vendor/_react-datepicker.scss, app/react/Forms/components/DateRange.js, app/react/Forms/components/MultiDateRange.js, app/react/Forms/components/NumericRange.js, app/react/Forms/components/specs/__snapshots__/DateRange.spec.js.snap
fixes #3911 
fixes #3903 
This fix affects Multi Date, Multi Date Range and Numeric fields and filters (where To and From inputs make sense).
PR checklist:
QA checklist:
=> 3911 stabilize date range css

app/react/Library/components/LibraryModeToggleButtons.js, app/react/Library/helpers/requestState.js, app/react/Library/helpers/specs/__snapshots__/resquestState.spec.js.snap, app/react/Library/helpers/specs/resquestState.spec.js
fixes #3897 
PR checklist:
QA checklist:
=> 3897 - Slow text search

app/react/I18N/components/I18NMenu.js, app/react/I18N/components/TranslateForm.js, app/react/I18N/components/specs/__snapshots__/I18NMenu.spec.js.snap, e2e/suites/inlineTranslate.test.ts
fixes #3931 
PR checklist:
QA checklist:
=> Stabilization Fix to release: Fixed inline translation submit button and e2e

app/react/Settings/components/CollectionSettings.tsx
fixes #4026 
PR checklist:
QA checklist:
=> Renamed Motomo to Matomo

app/api/utils/fixturesFactory.ts
=> Fixture factory - removed label from metadataValue 

package.json, yarn.lock
fixes #4051
PR checklist:
QA checklist:
=> Upped version of is-reachable due to security warnings

app/api/entities/specs/validateEntity.spec.ts, app/api/entities/validation/metadataValidators.js, app/api/entities/validation/validateEntityData.ts, app/react/Metadata/components/Metadata.js, app/react/Metadata/helpers/specs/validator.spec.js, app/react/Metadata/helpers/validator.js
fixes #3977 
PR checklist:
QA checklist:
=> Allow link without label  on Link properties

app/api/csv/arrangeThesauri.ts, app/api/csv/csvLoader.ts, app/api/csv/specs/__snapshots__/importFile.spec.ts.snap, app/api/csv/specs/arrangeThesauriTest.csv, app/api/csv/specs/csvLoaderFixtures.ts, app/api/csv/specs/csvLoaderSelects.spec.js, app/api/csv/specs/test.csv, app/api/csv/typeParsers/multiselect.ts, app/api/csv/typeParsers/select.ts
fixes #4059, #4087
For the PR, please note that there are two issues, and functional testing should cover both.
PR checklist:
QA checklist:
=> Csv import: column names and thesauri save fix

app/react/Viewer/components/ViewerDefaultMenu.js
fixes #4056 
PR checklist:
QA checklist:
=> Changed context menu view icon in pdf view

app/react/Viewer/actions/documentActions.js, app/react/Viewer/actions/specs/documentActions.spec.js
fixes #4084
PR checklist:
QA checklist:
=> 4084 - Upload supporting files while editing in PDF view

app/react/Map/Map.js, app/react/Map/specs/Map.spec.js
fixes #4043 
PR checklist:
QA checklist:
=> Ignored events that bubble from events from floating buttons on maps

.codeclimate.yml, app/api/csv/specs/csvExporter.spec.ts, app/api/csv/specs/exportCsvFixtures.ts, app/api/csv/specs/typeFormatters.spec.ts, app/api/csv/typeFormatters.ts, app/shared/types/commonSchemas.ts, app/shared/types/commonTypes.d.ts, app/shared/types/connectionType.d.ts
fixes #3945 
PR checklist:
QA checklist:
=> Export CSV respecting inherited values

app/api/entities/specs/denormalization.spec.ts, app/api/i18n/specs/translations.spec.js, app/api/i18n/translations.js, app/api/migrations/migrations/58-thesauri_translations_in_entity_metadata/index.js, app/api/migrations/migrations/58-thesauri_translations_in_entity_metadata/specs/58-thesauri_translations_in_entity_metadata.spec.js, app/api/migrations/migrations/58-thesauri_translations_in_entity_metadata/specs/fixtures.js
fixes #4062
PR checklist:
QA checklist:
=> 4062 - Thesauri values denormalized in entities' metadata

.github/workflows/ci_api_unit_tests.yml, .github/workflows/ci_app_unit_tests.yml, .github/workflows/ci_check_translations.yml, .github/workflows/ci_e2e_puppeteer.yml, .github/workflows/ci_e2e_suite1.yml, .github/workflows/ci_e2e_suite2.yml, .github/workflows/ci_eslint.yml, .github/workflows/ci_ts_emit_check.yml, .github/workflows/ci_ts_types.yml, .github/workflows/deploy_master.yml, .github/workflows/deploy_release.yml, .github/workflows/security_audit.yml, README.md
nodejs update to latest 14 to be able to update other dependencies that require this.
PR checklist:
QA checklist:
=> update nodejs 14.18.3

app/api/entities/specs/entities.spec.js
fixes #3832 
PR checklist:
QA checklist:
=> fixed flaky by properly awaiting on the previous test ?

package.json, yarn.lock
fixes #
PR checklist:
QA checklist:
=> updated node-fetch (security issue fix)

app/api/csv/specs/typeFormatters.spec.ts, app/api/csv/typeFormatters.ts
fixes #4169 
PR checklist:
QA checklist:
=> Check for empty array on inherited values for CSV export

.github/workflows/ci_api_unit_tests.yml, .github/workflows/ci_app_unit_tests.yml, .github/workflows/ci_check_translations.yml, .github/workflows/ci_e2e_puppeteer.yml, .github/workflows/ci_e2e_suite1.yml, .github/workflows/ci_e2e_suite2.yml, .github/workflows/ci_eslint.yml, .github/workflows/ci_ts_emit_check.yml, .github/workflows/ci_ts_types.yml, .github/workflows/deploy_master.yml, .github/workflows/deploy_release.yml
fixes #
PR checklist:
QA checklist:
=> stop concurrent ci runs

app/api/entities/entities.js, app/api/migrations/migrations/59-reindex-elastic-mappings-modifications/index.js, app/api/migrations/migrations/59-reindex-elastic-mappings-modifications/specs/59-reindex-elastic-mappings-modifications.spec.js, app/api/migrations/migrations/59-reindex-elastic-mappings-modifications/specs/fixtures.js, app/api/search.v2/buildQuery.ts, app/api/search.v2/queryHelpers.ts, app/api/search.v2/routes.ts, app/api/search.v2/specs/filters.spec.ts, app/api/search.v2/specs/metadataFilters.spec.ts, app/api/search.v2/specs/pagination.spec.ts, app/api/search.v2/specs/routes.spec.ts, app/api/search.v2/specs/setupTestingEnvironment.ts, app/api/search.v2/specs/sorting.spec.ts, app/api/search/elasticTypes.ts, app/api/search/specs/__snapshots__/entitiesIndex.spec.ts.snap, app/api/utils/fixturesFactory.ts, app/api/utils/validateRequest.js, app/shared/types/SearchQuerySchema.ts, app/shared/types/SearchQueryType.d.ts, database/elastic_mapping/base_properties.js, database/elastic_mapping/mappings.ts, package.json, yarn.lock
fixes #3550 
PR checklist:
QA checklist:
=> Mob programming: metadata filter query

app/api/migrations/migrate.ts, app/api/migrations/specs/migrate.spec.ts, install.sh, package.json, scripts/migrate_and_reindex.js
fixes #4205 
PR checklist:
QA checklist:
=> migrate-and-reindex script [HOTFIX]

app/api/odm/models.ts, app/api/topicclassification/specs/fixtures.ts, app/api/topicclassification/specs/sync.spec.ts, app/api/topicclassification/sync.ts, app/server.js
fixes #4215 
PR checklist:
QA checklist:
=> avoid using of skip for mongo pagination [HOTFIX]

app/react/Library/components/TableCell.tsx, app/react/Library/components/specs/TableCell.spec.tsx, app/react/Library/components/specs/__snapshots__/TableCell.spec.tsx.snap
fixes #4161 
fixes #4226 
PR checklist:
QA checklist:
=> Fixed display of nested values in table view

.github/workflows/ci_e2e_puppeteer.yml, app/api/socketio/setupSockets.ts, app/server.js, package.json
=> make sure socketio disconnects sockets on sigint [HOTFIX]

.github/workflows/deploy_master.yml, .github/workflows/deploy_release.yml, app/react/App/Root.js, app/react/config.js, app/react/index.js, package.json, webpack.production.config.js
=> client sentry dsn provided by SSR window variable

app/react/Entities/components/EntityViewer.js, app/react/Pages/components/PageViewer.js, app/react/Pages/components/specs/PageViewer.spec.js
fixes #4229
PR checklist:
QA checklist:
=> 4229 - Page helmet on entity view

app/api/search/search.js, app/api/search/specs/search.spec.js, package.json
fixes #
PR checklist:
QA checklist:
=> Filter by simple relationship property [HOTFIX]

app/api/search/search.js, app/api/search/specs/search.spec.js
fixes #
PR checklist:
QA checklist:
=> Filter by simple relationship property [hotfix merge]

webpack.production.config.js
fixes #
PR checklist:
QA checklist:
=> Production source maps

app/server.js
- Mongoose integration
- Capture errors only on the 5xx response codes.
PR checklist:
QA checklist:
=> Sentry tweaks

app/api/search/documentQueryBuilder.js, app/api/search/specs/fixtures_elastic.js, app/api/search/specs/search.spec.js
fixes #4227 
PR checklist:
QA checklist:
=> 4227 - Search return correct aggregations for templates

app/api/evidences_vault/specs/helpers.js, app/api/evidences_vault/specs/vaultSync.spec.js, app/api/evidences_vault/vaultSync.js, app/startLegacyServicesNoMultiTenant.js
=> evidences vault support for multiple tokens

app/api/entities/entitySavingManager.ts, app/api/entities/specs/entitySavingManager.spec.ts, package.json
fixes #4379
PR checklist:
QA checklist:
=> Hotfix for 4379

app/api/entities/entitySavingManager.ts, app/api/entities/specs/entitySavingManager.spec.ts, package.json
fixes #4379
PR checklist:
QA checklist:
=> Hotfix 4379 empty array on attachments

app/api/entities/entities.js, app/api/entities/specs/entities.spec.js, app/api/templates/templates.ts
Related to #4356 
PR checklist:
QA checklist:
=> Post api entities rework [3]

.github/workflows/deploy_master.yml, .github/workflows/deploy_release.yml, app/api/config.ts, app/react/App/Root.js, app/react/index.js, app/server.js, package.json, tsconfig.json
=> sentry log all errors and release info

app/api/services/twitterintegration/getTwitterImages.ts, app/api/services/twitterintegration/specs/TwitterIntegration.spec.ts, package.json
fixes #
PR checklist:
QA checklist:
=> Change attachments URL in twitter crawler

app/react/MetadataExtraction/SuggestionsTable.tsx, app/react/MetadataExtraction/specs/EntitySuggestions.spec.tsx, app/react/UI/BasicTable/Pagination.tsx, app/react/UI/BasicTable/specs/Pagination.spec.tsx, app/shared/types/suggestionSchema.ts
fixes #4321
PR checklist:
QA checklist:
=> 4321 - change suggestions page size
