app/react/Uploads/components/ConfirmDocumentDeleteModal.js

changed confirm message for delete document modal

---

app/react/Library/components/FiltersForm.js

Solves #67

---

app/api/users/routes.js
app/api/users/specs/routes.spec.js

when saving new password it will be saved with proper encryption

---

app/react/Documents/components/DocumentForm.js
app/react/Documents/components/specs/DocumentForm.spec.js
app/react/Viewer/components/specs/Document.spec.js

DocumentForm correctly sends/Renders select fields

---

app/react/Layout/SidePanel.js

Solves https://github.com/huridocs/uwazi/issues/130

Add sidebar width limit on mobile

---

app/react/App/scss/modules/_uploads.scss
app/react/Uploads/components/UploadBox.js

Solves https://github.com/huridocs/uwazi/issues/80 and https://github.com/huridocs/uwazi/issues/99

Add "supported formats" note below drag&drop box inside Uploads

---

app/react/Viewer/components/Viewer.js

Solves https://github.com/huridocs/uwazi/issues/119

Fix padding in scrollbar in document view

---

app/react/App/scss/modules/_search.scss
app/react/Library/components/LibraryFilters.js
app/react/Library/components/ViewMetadataPanel.js
app/react/Uploads/components/UploadsFormPanel.js
app/react/Viewer/components/ViewMetadataPanel.js

This solves https://github.com/huridocs/uwazi/issues/68 and https://github.com/huridocs/uwazi/issues/69, because I failed creating the new branch (I did it from 68_branch, so this PR contains both issues' commits).

Sidebar titles + Filters (68 + 69 issues)

---

app/react/App/Provider.js
app/react/App/RouteHandler.js
app/react/App/specs/RouteHandler.spec.js
app/react/App/specs/TestController.js
app/react/Library/Library.js
app/react/Metadata/Metadata.js
app/react/RelationTypes/EditRelationType.js
app/react/RelationTypes/NewRelationType.js
app/react/Router.js
app/react/Templates/EditTemplate.js
app/react/Templates/NewTemplate.js
app/react/Thesauris/NewThesauri.js
app/react/Uploads/UploadsRoute.js
app/react/Viewer/ViewDocument.js
app/react/Viewer/components/ViewReferencesPanel.js
app/react/Viewer/components/specs/Document.spec.js
app/react/Viewer/specs/ViewDocument.spec.js
app/react/Viewer/utils/Text.js
app/react/Viewer/utils/specs/Text.spec.js

RouteHanlder aware of route params changes

---

app/react/App/scss/layout/_aside.scss

Close icon with cursor:pointer

---

app/react/Uploads/components/UploadsFormPanel.js

Change edit metadata to just metadata

---

app/react/App/scss/fixes.scss
app/react/Viewer/actions/referencesActions.js
app/react/Viewer/actions/specs/referencesActions.spec.js
app/react/Viewer/components/ConfirmCloseReferenceForm.js
app/react/Viewer/components/CreateReferencePanel.js
app/react/Viewer/components/SourceDocument.js
app/react/Viewer/components/TargetDocumentHeader.js
app/react/Viewer/components/ViewReferencesPanel.js
app/react/Viewer/components/Viewer.js
app/react/Viewer/components/ViewerTextSelectedMenu.js
app/react/Viewer/components/specs/ConfirmCloseReferenceForm.spec.js
app/react/Viewer/components/specs/CreateReferencePanel.spec.js
app/react/Viewer/components/specs/TargetDocumentHeader.spec.js

Referencing tweaks

---

app/react/Layout/SidePanel.js
app/react/Layout/scss/sidepanel.scss
app/react/Library/components/DocumentsList.js
app/react/Uploads/components/UploadsSection.js
app/react/Viewer/components/Viewer.js

Sidebar width

---

app/react/App/scss/modules/_uploads.scss
app/react/Uploads/components/UploadBox.js

Drag and drop restyle

---

app/react/App/scss/config/_colors.scss
app/react/App/scss/elements/_base.scss
app/react/App/scss/elements/_item.scss
app/react/App/scss/fixes.scss
app/react/App/scss/modules/_metadata-view.scss
app/react/App/scss/modules/_uploads.scss
app/react/Layout/Lists.js
app/react/Layout/scss/sidepanel.scss
app/react/Library/components/Doc.js
app/react/Library/components/DocumentsList.js
app/react/Uploads/components/UploadDoc.js
app/react/Viewer/components/SearchResults.js
app/react/Viewer/components/ViewReferencesPanel.js
app/react/Viewer/scss/createmodal.scss

Fixed size for cards

---

app/react/App/scss/elements/_item.scss
app/react/App/scss/fixes.scss
app/react/Library/components/DocumentsList.js

fix bug with card and layouts

---

app/react/App/scss/elements/_item.scss
app/react/Library/components/Doc.js

Displaying dates in the library cards beside the document type is misleading

---

app/react/Layout/scss/sidepanel.scss

Remove glitch on folded corners

---

app/react/App/scss/modules/_search.scss

Solves https://github.com/huridocs/uwazi/issues/92

Remove fake scroll

---

app/react/Viewer/components/Document.js
app/react/components/Elements/Loader.js
app/react/components/Elements/scss/loader.scss

Loader in document viewer

---

app/api/documents/documentQueryBuilder.js
app/api/documents/documents.js
app/api/documents/specs/documents.spec.js
app/api/documents/specs/elasticResult.js
app/react/App/scss/elements/_item.scss
app/react/App/scss/modules/_document.scss
app/react/Library/actions/libraryActions.js
app/react/Library/components/DocumentsList.js
app/react/Library/specs/Library.spec.js
app/react/components/Elements/scss/loader.scss

Library pagination

---

app/react/Viewer/actions/documentActions.js
app/react/Viewer/actions/specs/documentActions.spec.js
app/react/Viewer/components/SourceDocument.js

fixes search results on create connection panel

---

app/react/Library/reducers/documentsReducer.js
app/react/Library/reducers/specs/documentsReducer.spec.js
package.json

default state of documents list changed to new document structure, changed version of react-redux-form

---

app/react/Library/components/Doc.js

fixed bug not showing document types in library

---

app/shared/JSONRequest.js

jsonRequest now uses data pased as immutable data

---

app/api/documents/routes.js
app/react/Library/components/LibraryMenu.js
app/react/Viewer/components/ViewerDefaultMenu.js
app/react/Viewer/components/specs/ViewerDefaultMenu.spec.js

Fixes issue #47
Depends on: #213 
PR check list:
QA check list:

Download document

---

app/react/Templates/actions/specs/templateActions.spec.js
app/react/Templates/actions/templateActions.js
app/react/Templates/components/FormConfigSelect.js
app/react/Templates/components/PropertyOption.js
app/react/Templates/components/specs/FormConfigSelect.spec.js
app/react/Templates/components/specs/PropertyOption.spec.js
nightmare/helpers/config.js

Fixes issue #155 
PR check list:
QA check list:

fixes some errors on drag n drop template creation, performance was good

---

app/react/Library/Library.js
app/react/Library/actions/libraryActions.js
app/react/Library/specs/Library.spec.js

Fixes issue #201 
PR check list:
QA check list:

Library requestState uses the same action to search as the searchForm

---

app/react/App/RouteHandler.js
app/react/App/specs/RouteHandler.spec.js

Fixes issue #193 
PR check list:
QA check list:

RouteHandler now has a default setReduxState

---

app/react/App/App.js
app/react/App/scss/layout/_header.scss
app/react/App/scss/layout/_nav.scss

Solves #90.
I discarded the new changes with the purpose to solve this card easier and get the track of the search bar improvement in https://github.com/huridocs/uwazi/issues/180.

Fix header

---

app/react/App/scss/fixes.scss
app/react/App/scss/modules/_admin.scss

Fix scroll inside admin

---

app/react/App/scss/modules/_document.scss
app/react/Layout/scss/sidepanel.scss

Fixes issue #202 
PR check list:
QA check list:

Main and sidebar width

---

app/react/Library/components/Doc.js

Add colour to labels and push them next to the card name

---

app/react/Router.js

Fixes issue #195 
PR check list:
QA check list:

added settings to the list of private pages

---

app/react/Viewer/components/SourceDocument.js
app/react/Viewer/components/specs/SourceDocument.spec.js

Fixes issue #221 
PR check list:
QA check list:

disabled create connection functionality when not logged in

---

app/react/Viewer/components/ViewReferencesPanel.js

Fixes issue #186 
PR check list:
QA check list:

removed link from connection title in document viewer connections

---

app/react/Templates/components/TemplateCreator.js

Fixes issue #224 
PR check list:
QA check list:

Removed checkbox and list from construction blocks in template creator

---

app/react/App/ShowIf.js
app/react/App/specs/ShowIf.spec.js
app/react/ContextMenu/reducers/contextMenuReducer.js
app/react/Viewer/actions/documentActions.js
app/react/Viewer/actions/referencesActions.js
app/react/Viewer/actions/specs/documentActions.spec.js
app/react/Viewer/actions/specs/referencesActions.spec.js
app/react/Viewer/actions/uiActions.js
app/react/Viewer/components/CreateReferencePanel.js
app/react/Viewer/components/MetadataPanelMenu.js
app/react/Viewer/components/TargetDocument.js
app/react/Viewer/components/TargetDocumentHeader.js
app/react/Viewer/components/ViewMetadataPanel.js
app/react/Viewer/components/ViewReferencesPanel.js
app/react/Viewer/components/Viewer.js
app/react/Viewer/components/ViewerDefaultMenu.js
app/react/Viewer/components/ViewerSaveTargetReferenceMenu.js
app/react/Viewer/components/specs/TargetDocument.spec.js
app/react/Viewer/components/specs/TargetDocumentHeader.spec.js
app/react/Viewer/components/specs/ViewMetadataPanel.spec.js
app/react/Viewer/components/specs/ViewReferencesPanel.spec.js
app/react/Viewer/components/specs/Viewer.spec.js
app/react/Viewer/components/specs/ViewerSaveTargetReferenceMenu.spec.js
app/react/Viewer/reducers/reducer.js
app/react/Viewer/scss/document.scss
app/react/Viewer/utils/Scroller.js
app/react/Viewer/utils/Text.js
app/react/Viewer/utils/specs/Scroller.spec.js
app/shared/JSONRequest.js

Fixes issue #206 
PR check list:
QA check list:

206 separate viewer documents

---

app/react/App/scss/fixes.scss
app/react/App/scss/modules/_search.scss

Fixes issue #109 
PR check list:
QA check list:

Remove grey boxes on metadata

---

app/react/App/Root.js
app/react/App/scss/config/_colors.scss
app/react/App/scss/config/_materials.scss
app/react/App/scss/config/_typography.scss
app/react/App/scss/elements/_base.scss
app/react/App/scss/elements/_item.scss
app/react/App/scss/elements/_panel.scss
app/react/App/scss/layout/_aside.scss
app/react/App/scss/layout/_header.scss
app/react/App/scss/modules/_document.scss
app/react/App/scss/modules/_metadata-view.scss
app/react/Layout/scss/sidepanel.scss

Fixes issue #239 
PR check list:
QA check list:

Change UI colors

---

app/react/Library/components/FiltersForm.js

Fixes issue #
PR check list:
QA check list:

fixed bugg with filters type select in the library

---

Procfile.ubuntu
README.md
app/api/references/references.js
app/api/references/routes.js
app/api/references/specs/fixtures.js
app/api/references/specs/references.spec.js
app/api/references/specs/routes.spec.js
app/api/upload/PDF.js
app/react/BasicReducer/reducer.js
app/react/BasicReducer/specs/reducer.spec.js
app/react/Viewer/ViewDocument.js
app/react/Viewer/actions/referencesActions.js
app/react/Viewer/actions/specs/referencesActions.spec.js
app/react/Viewer/components/Document.js
app/react/Viewer/components/SourceDocument.js
app/react/Viewer/components/TargetDocument.js
app/react/Viewer/components/TargetDocumentHeader.js
app/react/Viewer/components/ViewReferencesPanel.js
app/react/Viewer/components/Viewer.js
app/react/Viewer/components/specs/SourceDocument.spec.js
app/react/Viewer/components/specs/TargetDocumentHeader.spec.js
app/react/Viewer/components/specs/ViewReferencesPanel.spec.js
app/react/Viewer/components/specs/Viewer.spec.js
app/react/Viewer/reducers/reducer.js
app/react/Viewer/reducers/referencesReducer.js
app/react/Viewer/reducers/specs/referencesReducer.spec.js
app/react/Viewer/referencesAPI.js
app/react/Viewer/specs/ViewDocument.spec.js
app/react/Viewer/utils/Text.js
app/react/Viewer/utils/specs/Text.spec.js

Fixes issue #140 
PR check list:
QA check list:

Render inbound connections

---

app/react/App/scss/layout/_aside.scss
app/react/Layout/scss/sidepanel.scss

Fixes issue #247
PR check list:
QA check list:

Fix sidebar height on mobile

---

nightmare/helpers/config.js
nightmare/paths/references.spec.js
package.json

end to end tests for the references path which creates a connection between two document's words and then removes the connection afterwards.

Nightmare references path

---

app/react/Viewer/components/SourceDocument.js

Fixes issue #255
PR check list:
QA check list:

now you can create new connections when the connections panel is open

---

app/react/App/scss/config/_colors.scss

Fixes issue #273
PR check list:
QA check list:
…tion

Fix multiple layers on text-selection

---

app/react/App/scss/config/_materials.scss
app/react/App/scss/fixes.scss
app/react/App/scss/modules/_document.scss
app/react/App/scss/modules/_metadata-view.scss
app/react/App/scss/modules/_search.scss
app/react/Layout/scss/sidepanel.scss
app/react/Library/components/LibraryFilters.js
app/react/Library/components/ViewMetadataPanel.js
app/react/Uploads/components/UploadsFormPanel.js
app/react/Viewer/components/CreateReferencePanel.js
app/react/Viewer/components/ViewMetadataPanel.js
app/react/Viewer/components/ViewReferencesPanel.js

Fixes issue #286 
PR check list:
QA check list:

Sticky headers

---

app/react/Layout/scss/sidepanel.scss

Fixes issue #298 #300 #301
PR check list:
QA check list:

Fix conflict between header and sidebar

---

app/react/App/scss/elements/_item.scss
app/react/App/scss/modules/_document.scss
app/react/Layout/scss/sidepanel.scss
app/react/Viewer/components/TargetDocumentHeader.js
app/react/Viewer/scss/document.scss

Fixes issue #251 
PR check list:
QA check list:

Fix save button on targeting connections

---

nightmare/helpers/config.js
nightmare/helpers/login.js
nightmare/smokes/loggedin.smoke.spec.js

Fixes issue #317 
PR check list:
QA check list:

Fix smoke tests

---

app/api/thesauris/routes.js
app/react/utils/api.js
app/react/utils/specs/api.spec.js

Fixes issue #36 
PR check list:
QA check list:

Show error messages when the server responds with an error

---

app/react/Library/components/LibraryFilters.js

Fixes issue #334 
PR check list:
QA check list:

added search button to filters form

---

app/react/Viewer/components/ViewMetadataPanel.js

Fixes issue #337 #336 
PR check list:
QA check list:

solved bugs with tabs in document viewer

---

app/react/App/Root.js
app/react/App/scss/config/_typography.scss
app/react/App/scss/elements/_item.scss
app/react/App/scss/fixes.scss
app/react/Layout/Lists.js
app/react/Library/components/Doc.js

Fixes issue #295
PR check list:
QA check list:

Entity card design

---

app/react/App/scss/layout/_header.scss
app/react/App/scss/layout/_nav.scss
app/react/App/scss/modules/_entity.scss
app/react/Entities/components/EntityViewer.js
app/react/Layout/scss/sidepanel.scss
app/react/Library/components/Doc.js
app/react/Library/components/SearchBar.js
app/react/Library/components/ViewMetadataPanel.js
app/react/Viewer/components/ViewMetadataPanel.js

Improve tabs, fix header size, change open doc icon

---

app/react/Library/components/ViewMetadataPanel.js
app/react/Uploads/components/UploadsMenu.js

Fixes issue #355 
PR check list:
QA check list:

fixed bug when deleting documents or entities in library and uploads

---

app/react/Routes.js
app/react/Settings/components/ThesaurisList.js
app/react/Templates/EditEntity.js
app/react/Templates/NewEntity.js
app/react/Templates/components/MetadataTemplate.js
app/react/Templates/components/TemplateCreator.js
app/react/Templates/components/specs/MetadataTemplate.spec.js
app/react/Templates/components/specs/TemplateCreator.spec.js
app/react/Thesauris/components/ThesauriForm.js

Fixes issue #329
PR check list:
QA check list:

Diferent route Objects for new/edit entity

---

app/react/App/scss/elements/_item.scss
app/react/App/scss/modules/_document.scss
app/react/Entities/components/EntityViewer.js
app/react/Library/components/Doc.js
app/react/Viewer/components/ConnectionsList.js

Fixes issue #352 #353 #362 
PR check list:
QA check list:

Improve card design

---

app/react/App/scss/fixes.scss
app/react/Layout/scss/sidepanel.scss

Fixes issue #365 
PR check list:
QA check list:

Fix double scrollbar

---

app/react/App/scss/config/_colors.scss

Fixes issue #349 
PR check list:
QA check list:

Change opacity color on text selections

---

app/api/search/documentQueryBuilder.js
app/api/search/routes.js
app/api/search/search.js
app/api/search/specs/documentsQueryBuilder.spec.js
app/api/upload/specs/12345.test.optimized.pdf
app/react/Forms/components/MultiSelect.js
app/react/Library/Library.js
app/react/Library/actions/filterActions.js
app/react/Library/actions/libraryActions.js
app/react/Library/actions/specs/filterActions.spec.js
app/react/Library/actions/specs/libraryActions.spec.js
app/react/Library/components/Doc.js
app/react/Library/components/FiltersForm.js
app/react/Library/components/LibraryFilters.js
app/react/Library/components/LibraryMenu.js
app/react/Library/components/ViewMetadataPanel.js
app/react/Library/components/specs/Doc.spec.js
app/react/Library/components/specs/FiltersForm.spec.js
app/react/Library/components/specs/LibraryFilters.spec.js
app/react/Library/components/specs/ViewMetadataPanel.spec.js
app/react/Library/containers/DocumentForm.js
app/react/Library/containers/EntityForm.js
app/react/Library/helpers/libraryFilters.js
app/react/Library/helpers/specs/libraryFilters.spec.js
app/react/Library/reducers/filtersReducer.js
app/react/Library/reducers/reducer.js
app/react/Library/reducers/specs/filtersReducer.spec.js
app/react/Library/specs/Library.spec.js

Also fixes #383
PR check list:
QA check list:

Aggregations

---

app/react/Entities/components/EntityViewer.js
app/react/Library/components/ViewMetadataPanel.js
app/react/Metadata/components/ShowMetadata.js
app/react/Metadata/helpers/formater.js
app/react/Viewer/components/ViewMetadataPanel.js

Fixes issue #386
PR check list:
QA check list:

Fixed bug that prevented entity view with multiselect.

---

app/react/App/scss/modules/_search.scss
app/react/Forms/components/MultiSelect.js
app/react/Library/components/FiltersForm.js
app/react/Library/components/LibraryFilters.js

Fixes issue #384 
PR check list:
QA check list:

Fix sidepanel tweaks + facet browsing improvement

---

app/api/search/documentQueryBuilder.js
app/api/search/specs/documentsQueryBuilder.spec.js

Fixes issue #402 
PR check list:
QA check list:

now all aggregations are returned

---

app/api/search/search.js
app/react/App/Menu.js
app/react/App/Root.js
app/react/App/RouteHandler.js
app/react/App/specs/RouteHandler.spec.js
app/react/Library/Library.js
app/react/Library/actions/libraryActions.js
app/react/Library/actions/specs/libraryActions.spec.js
app/react/Library/components/SortButtons.js
app/react/Library/helpers/libraryFilters.js
app/react/Library/helpers/specs/libraryFilters.spec.js
app/react/Library/specs/Library.spec.js
app/react/Router.js
app/shared/JSONRequest.js
app/shared/JSONUtils.js
app/shared/specs/JSONUtils.spec.js

Fixes issue #394 
PR check list:
QA check list:

filters as url

---

app/react/App/scss/layout/_header.scss

Fixes issue #341
PR check list:
QA check list:

Fix text-overflow on collection title

---

app/react/App/scss/modules/_search.scss
app/react/Forms/components/MultiSelect.js

Fixes issue #382 
PR check list:
QA check list:

improve facet browsing

---

app/api/references/references.js
app/api/references/specs/references.spec.js

Fixes issue #438 
PR check list:
QA check list:

Fixed bug that prevented correct showing of connections upon creation.

---

app/react/Entities/components/EntityViewer.js
app/react/Layout/scss/sidepanel.scss
app/react/Library/components/ViewMetadataPanel.js
app/react/Metadata/actions/actions.js
app/react/Metadata/components/MetadataFormButtons.js
app/react/Metadata/components/specs/MetadataFormButtons.spec.js
app/react/Metadata/index.js
app/react/Uploads/components/UploadsFormPanel.js
app/react/Viewer/components/CreateReferencePanel.js
app/react/Viewer/components/ViewMetadataPanel.js
nightmare/helpers/selectors.js

Fixes issue #376 
PR check list:
QA check list:

376 entity cancel edit

---

app/api/thesauris/specs/routes.spec.js
app/api/thesauris/specs/thesauris.spec.js
app/api/thesauris/thesauris.js

Fixes issue #421 
PR check list:
QA check list:

dictionaries id now is saved as string

---

app/react/Library/components/SortButtons.js
app/react/Library/components/specs/SortButtons.spec.js
app/react/Templates/components/FormConfigInput.js
app/react/Templates/components/MetadataProperty.js
app/react/Templates/components/specs/FormConfigInput.spec.js
app/react/Templates/components/specs/MetadataProperty.spec.js

Fixes issue #442
PR check list:
QA check list:

442 order by metadata

---

app/api/search/documentQueryBuilder.js
app/react/App/scss/fixes.scss
app/react/Forms/components/FormField.js
app/react/Forms/components/MultiDate.js
app/react/Forms/components/MultiDateRange.js
app/react/Forms/components/specs/MultiDate.spec.js
app/react/Forms/components/specs/MultiDateRange.spec.js
app/react/Forms/index.js
app/react/Library/actions/libraryActions.js
app/react/Library/components/FiltersForm.js
app/react/Metadata/actions/actions.js
app/react/Metadata/components/MetadataForm.js
app/react/Metadata/components/ShowMetadata.js
app/react/Metadata/helpers/formater.js
app/react/Templates/components/Icons.js
app/react/Templates/components/MetadataProperty.js
app/react/Templates/components/PropertyOption.js
app/react/Templates/components/TemplateCreator.js

Fixes issue #
PR check list:
QA check list:

Custom fields cejil

---

app/api/search/documentQueryBuilder.js

Fixes issue #
PR check list:
QA check list:

fixed bug calculating nested aggregations

---

app/react/App/scss/config/_colors.scss
app/react/App/scss/config/_theme.scss
app/react/App/scss/layout/_header.scss
app/react/App/scss/styles.scss

Add custom theme option

---

app/react/Forms/components/IconSelector.js
app/react/Forms/components/specs/IconSelector.spec.js

Fixes issue #468
PR check list:
QA check list:

Added 'no-icon' option.

---

app/react/Entities/components/EntityViewer.js
app/react/Library/components/ViewMetadataPanel.js
app/react/Metadata/components/ShowMetadata.js
app/react/Viewer/components/ViewMetadataPanel.js

Fixes issue #467
PR check list:
QA check list:

Moved document title and type back to metadata show.

---

app/react/Entities/components/EntityViewer.js
app/react/Metadata/helpers/formater.js
app/react/Timeline/components/TimelineViewer.js
app/react/Timeline/scss/_timeline.scss

Fixes issue #431
PR check list:
QA check list:

431 timeline v2

---

app/react/App/scss/elements/_item.scss
app/react/App/scss/modules/_entity.scss
app/react/Entities/components/EntityViewer.js
app/react/Layout/scss/sidepanel.scss
app/react/Library/components/Doc.js
app/react/Metadata/components/ShowMetadata.js

Reduce font size and icons for titles

---

app/react/App/scss/elements/_item.scss
app/react/App/scss/fixes.scss
app/react/App/scss/layout/_header.scss
app/react/App/scss/modules/_document.scss
app/react/Layout/scss/sidepanel.scss

Fixes issue #444
PR check list:
QA check list:

Searchbox tweaks on tablet

---

app/react/App/scss/config/_colors.scss
app/react/App/scss/modules/_markdown.scss

Fixes issue #483 
PR check list:
QA check list:

Improve table rendering

---

app/react/Timeline/scss/_timeline.scss

Fixes issue #482 
PR check list:
QA check list:

Add lateral padding to render properly the milestone on timelines

---

app/react/App/Menu.js
app/react/App/scss/elements/_controls.scss
app/react/App/scss/elements/_item.scss
app/react/App/scss/layout/_header.scss
app/react/I18N/components/I18NMenu.js
app/react/I18N/components/specs/I18NMenu.spec.js
app/react/Layout/scss/sidepanel.scss
app/react/Viewer/scss/document.scss

Fixes issue #378 #458 #508 #509 #511 #513 
PR check list:
QA check list:

Hotfix for some CSS styles on sidepanel/items

---

app/react/Library/components/SearchBar.js

Fixes issue #443 
PR check list:
QA check list:

fixed quick search bugs

---

app/react/App/Menu.js
app/react/Router.js
app/react/Routes.js
app/react/Settings/components/CollectionSettings.js
app/react/Settings/components/specs/CollectionSettings.spec.js

Fixes issue #518 
PR check list:
QA check list:

Custom home page

---

app/react/Metadata/actions/actions.js
app/react/Metadata/actions/specs/actions.spec.js
app/react/Uploads/components/UploadDoc.js
app/react/Uploads/reducers/specs/uploadsReducer.spec.js
app/react/Uploads/reducers/uploadsReducer.js
package.json

Fixes issue #496, #528 
PR check list:
QA check list:

496 creation bug

---

couchdb/reset_elastic_index.sh

Fixes issue #531 
PR check list:
QA check list:

changed elastic configuration to fix sorting bug

---

app/react/App/scss/elements/_item.scss
app/react/Layout/Lists.js
app/react/Uploads/UploadsRoute.js
app/react/Uploads/components/UploadDoc.js
app/react/Uploads/components/UploadEntity.js
app/react/Uploads/components/UploadsMenu.js
app/react/Uploads/containers/DocumentForm.js
app/react/Uploads/containers/EntityForm.js
app/react/Uploads/specs/UploadsRoute.spec.js

Fixes issue #510 
PR check list:
QA check list:

Uploads style changes

---

app/react/Entities/components/EntityViewer.js
app/react/Entities/components/ReferencesGroup.js
app/react/Entities/components/specs/EntityViewer.spec.js
app/react/Entities/components/specs/ReferencesGroup.spec.js
app/react/Layout/scss/sidepanel.scss
app/react/utils/advancedSort.js
app/react/utils/specs/advancedSort.spec.js

Fixes issue #537 
PR check list:
QA check list:

Created reference collapse in EntityViewer.

---

app/react/Forms/components/MultiSelect.js
app/react/Forms/components/Nested.js
app/react/Forms/components/NestedMultiselect.js
app/react/Forms/components/specs/Nested.spec.js
app/react/Metadata/helpers/formater.js

Fixes issue #535 
PR check list:
QA check list:

535 custom field improvements

---

app/api/documents/documents.js
app/api/documents/specs/documents.spec.js
app/api/documents/specs/fixtures.js
app/react/App/Footer.js
app/react/Entities/components/EntityViewer.js
app/react/Forms/components/FormGroup.js
app/react/Forms/components/specs/FormGroup.spec.js
app/react/I18N/components/EditTranslationForm.js
app/react/Library/components/LibraryFilters.js
app/react/Library/components/ViewMetadataPanel.js
app/react/Library/components/specs/LibraryFilters.spec.js
app/react/Library/components/specs/ViewMetadataPanel.spec.js
app/react/Metadata/actions/actions.js
app/react/Metadata/components/MetadataForm.js
app/react/Uploads/components/UploadsFormPanel.js
app/react/Viewer/components/SourceDocument.js
app/react/Viewer/components/ViewMetadataPanel.js
app/react/Viewer/components/specs/MetadataPanelMenu.spec.js
app/react/Viewer/components/specs/ViewMetadataPanel.spec.js
package.json

Fixes issue #519
PR check list:
QA check list:

519 slow rendering

---

app/react/I18N/components/EditTranslationForm.js
app/react/RelationTypes/components/RelationTypeForm.js
app/react/Settings/components/NavlinksSettings.js
app/react/Thesauris/components/ThesauriForm.js

Fixes issue #309 
PR check list:
QA check list:

Fix margins on settings

---

app/react/App/scss/layout/_header.scss

Fixes issue #547 
PR check list:
QA check list:

Fix nav bug when searchbox is open

---

app/react/Templates/components/MetadataProperty.js

Fixes issue #543 
PR check list:
QA check list:

Fixed bug that made dragging template properties inconsistent.

---

app/react/Forms/components/Select.js
app/react/Forms/components/specs/Select.spec.js

Fixes issue #529 
PR check list:
QA check list:

Sorted selects alphabetically.

---

app/react/Forms/components/DatePicker.js
app/react/Forms/components/specs/DatePicker.spec.js
app/react/Library/Library.js
app/react/Library/helpers/libraryFilters.js
app/react/Library/helpers/specs/libraryFilters.spec.js
app/react/Routes.js
couchdb/migrations/date_fields_to_int.js
couchdb/migrations/run_migration.js

Fixes issue #544 
PR check list:
QA check list:

Migration to change date values from string to integer

---

app/react/App/Menu.js
app/react/Library/actions/libraryActions.js
app/react/Pages/components/ItemList.js
app/react/Pages/components/PageViewer.js
app/react/Pages/components/specs/ItemList.spec.js
app/react/Pages/components/specs/PageViewer.spec.js

Fixes issue #540 
PR check list:
QA check list:

PageLists link redirected to library

---

app/react/Library/components/LibraryFilters.js

Fixes issue #542 #557 
PR check list:
QA check list:

translations for library document types list

---

app/api/templates/specs/templates.spec.js
app/api/templates/templates.js
app/api/templates/utils.js
app/react/BasicReducer/reducer.js
app/react/BasicReducer/specs/reducer.spec.js
app/react/Templates/actions/specs/templateActions.spec.js
app/react/Templates/actions/templateActions.js

Fixes issue #546 
PR check list:
QA check list:

template propery name changes locked to the first name

---

app/react/Forms/components/Nested.js
app/react/Metadata/components/ShowMetadata.js

Fixes issue #530 
PR check list:
QA check list:

Dont render empty fields

---

app/react/App/scss/elements/_item.scss
app/react/App/scss/modules/_library.scss
app/react/App/scss/styles.scss
app/react/App/scss/utilities/_utilities.scss
app/react/Library/components/DocumentsList.js
app/react/Library/components/SortButtons.js
app/react/Library/components/specs/SortButtons.spec.js

Fixes issue #442 
PR check list:
QA check list:

Dropdown sort by

---

app/react/App/scss/modules/_document.scss

Fixes issue #514 
PR check list:
QA check list:

Css hack to allow text selection in some documents

---

app/react/Layout/TemplateLabel.js

Fixes issue #573 
PR check list:
QA check list:

Label translation for template labels

---

app/react/App/scss/elements/_controls.scss
app/react/App/scss/fixes.scss
app/react/App/scss/modules/_settings-metadata.scss
app/react/RelationTypes/components/RelationTypeForm.js
app/react/Thesauris/components/ThesauriForm.js

Fixes issue #292 
PR check list:
QA check list:

Fix "duplicated name" feedback position

---

app/react/I18N/components/I18NMenu.js
couchdb/migrations/migrate_to_i18n.js
couchdb/migrations/run_migration.js

Fixes issue #567 
PR check list:
QA check list:

567 i18n migration

---

app/react/Viewer/referencesAPI.js
app/react/Viewer/specs/referencesAPI.spec.js

Fixes issue #566
PR check list:
QA check list:

Delete reference now only sends ID and REV.

---

app/react/App/scss/modules/_entity.scss

Fixes issue #583
PR check list:
QA check list:

Fix create connection on entities

---

app/react/App/scss/config/_colors.scss
app/react/App/scss/elements/_item.scss
app/react/Layout/scss/sidepanel.scss

Fixes issue #593 
PR check list:
QA check list:

#593 - UI glitches

---

app/react/Layout/scss/sidepanel.scss

Fixes issue #600
PR check list:
QA check list:

#600 - Item type is not aligned properly on sidepanel

---

app/api/search/documentQueryBuilder.js
app/react/Library/components/DocumentsList.js

Fixes issue #
PR check list:
QA check list:

Increased the ammount of documents requested each time to 30

---

app/react/Library/components/FiltersForm.js
app/react/Library/components/SortButtons.js
app/react/Metadata/helpers/formater.js

Fixes issue #614 #623 #608 
PR check list:
QA check list:

added some missing or wrong translations

---

app/react/I18N/components/EditTranslationForm.js
app/react/I18N/components/specs/EditTranslationForm.spec.js

Fixes issue #606 
PR check list:
QA check list:

translations now appear in alphabetical order

---

app/react/Metadata/components/MetadataFormButtons.js

Fixes issue #616
PR check list:
QA check list:

#616 - Hide buttons when user is editing metadata

---

app/react/App/scss/modules/_markdown.scss

Fixes issue #620
PR check list:
QA check list:

#620 - Reduce rich text field font size on sidepanel

---

app/react/App/scss/modules/_entity.scss
app/react/App/scss/modules/_search.scss
app/react/Entities/components/ReferencesGroup.js
app/react/Forms/components/NestedMultiselect.js
app/react/Layout/Item.js
app/react/Layout/scss/sidepanel.scss
app/react/Library/components/DocumentTypesList.js
app/react/Viewer/components/ConnectionsList.js

Fixes issue #601 
PR check list:
QA check list:

#601 - UI glitches

---

app/api/references/references.js
app/api/references/specs/fixtures.js
app/api/references/specs/references.spec.js
app/api/upload/routes.js
app/api/upload/specs/routes.spec.js
app/react/App/scss/elements/_controls.scss
app/react/App/scss/elements/_item.scss
app/react/Attachments/components/AttachmentsList.js
app/react/Attachments/components/UploadAttachment.js
app/react/Attachments/components/specs/AttachmentsList.spec.js
app/react/Entities/components/EntityViewer.js
app/react/Metadata/actions/actions.js
app/react/Metadata/actions/specs/actions.spec.js
app/react/Metadata/components/MetadataFormButtons.js
app/react/Metadata/components/UploadButton.js
app/react/Metadata/components/specs/UploadButton.spec.js
app/react/PDF/components/PDF.js
app/react/PDF/components/specs/PDF.spec.js
app/react/Viewer/ViewDocument.js
app/react/Viewer/actions/documentActions.js
app/react/Viewer/actions/routeActions.js
app/react/Viewer/actions/specs/routeActions.spec.js
app/react/Viewer/components/Document.js
app/react/Viewer/components/ViewMetadataPanel.js
app/react/Viewer/specs/ViewDocument.spec.js

Fixes issue #576, #619, #554 
PR check list:
QA check list:

576 attachments

---

app/react/Viewer/scss/document.scss

Fixes issue #633
PR check list:
QA check list:

#633 - Fix document width

---

app/react/Viewer/scss/document.scss

Fixes issue #633
PR check list:
QA check list:

#633 - Hotfix Document size for mobile

---

app/react/App/scss/elements/_item.scss

Fixes issue #580
PR check list:
QA check list:

#580 - Card metadata info

---

app/react/Viewer/actions/documentActions.js
app/react/Viewer/actions/specs/documentActions.spec.js
app/react/Viewer/components/ViewMetadataPanel.js
app/react/Viewer/components/specs/ViewMetadataPanel.spec.js

Fixes issue #632
PR check list:
QA check list:

632 toc editing

---

app/react/Users/Login.js

Fixes issue #
PR check list:
QA check list:

Fixed Login serverside rendering

---

app/api/settings/settings.js
app/api/settings/specs/settings.spec.js
app/react/I18N/actions/I18NActions.js
app/react/I18N/components/EditTranslationForm.js
app/react/Router.js

Fixes issue #605
PR check list:
QA check list:

605 filter groups translations

---

app/react/App/scss/elements/_panel.scss
app/react/Templates/components/FormConfigInput.js
app/react/Templates/components/FormConfigNested.js
app/react/Templates/components/FormConfigSelect.js
app/react/Templates/components/MetadataProperty.js

Fixes issue #446
PR check list:
QA check list:

Moved the 'duplicated label' warning to a better position.

---

app/api/pages/pages.js
app/api/pages/specs/fixtures.js
app/api/pages/specs/pages.spec.js
app/react/Pages/actions/pageActions.js
app/react/Pages/actions/specs/pageActions.spec.js

Fixes issue #541
PR check list:
QA check list:

541 page saving

---

app/react/App/scss/config/_colors.scss
app/react/App/scss/elements/_item.scss
app/react/Layout/Item.js
app/react/Layout/TemplateLabel.js
app/react/Layout/specs/TemplateLabel.spec.js
app/react/Library/components/Doc.js

Fixes issue #638 #665
PR check list:
QA check list:

#638 - Improve "Open document" icon

---

app/react/Forms/components/NestedMultiselect.js
app/react/Library/components/DocumentTypesList.js

Fixes issue #648
PR check list:
QA check list:

#648 - Add highlight to group labels

---

app/react/Attachments/components/AttachmentsList.js

Fixes issue #649
PR check list:
QA check list:

#649 - Change "source document" to a more meaningful label

---

app/react/App/scss/fixes.scss
app/react/Forms/components/MultiDate.js
app/react/Forms/components/MultiDateRange.js
app/react/Forms/components/specs/MultiDate.spec.js
app/react/Forms/components/specs/MultiDateRange.spec.js

Fixes issue #655
PR check list:
QA check list:

#655 - Improve multidate styles

---

app/react/App/scss/elements/_tooltip.scss
app/react/App/scss/layout/_nav.scss
app/react/App/scss/styles.scss
app/react/Entities/components/EntityViewer.js
app/react/Library/components/ViewMetadataPanel.js
app/react/Uploads/components/UploadsFormPanel.js
app/react/Viewer/components/ViewMetadataPanel.js

Fixes issue #666 
PR check list:
QA check list:

#666 - Add tooltip to tabs

---

app/api/upload/PDF.js
app/api/upload/specs/PDF.spec.js
couchdb/reset_elastic_index.sh

Fixes issue #645 
PR check list:
QA check list:

indexation for long types

---

app/react/App/scss/elements/_tooltip.scss
app/react/App/scss/layout/_header.scss
app/react/App/scss/layout/_nav.scss
app/react/App/scss/modules/_document.scss
app/react/Layout/scss/sidepanel.scss

Fixes issue #650 
PR check list:
QA check list:

#650 - Fix tooltip on sidepanel

---

app/api/i18n/routes.js
app/api/i18n/specs/translations.spec.js
app/api/i18n/translations.js
app/react/App/RouteHandler.js
app/react/App/specs/RouteHandler.spec.js
app/react/Forms/components/DateRange.js
app/react/I18N/components/EditTranslationForm.js
app/react/I18N/index.js
app/react/I18N/specs/t.spec.js
app/react/I18N/t.js
app/react/Library/components/FiltersForm.js
app/react/Library/components/SearchBar.js

Fixes issue #654, #653, #652
PR check list:
QA check list:

Multiple fixes

---

app/react/App/scss/modules/_entity.scss

Fix entity view width

---

app/react/App/scss/layout/_header.scss
app/react/Entities/components/ReferencesGroup.js
app/react/Library/components/SearchBar.js
app/react/Uploads/components/UploadDoc.js
app/react/Uploads/components/UploadEntity.js
app/react/Viewer/components/ConnectionsList.js

Fixes issue #
PR check list:
QA check list:

Review Open document icon

---

app/react/App/scss/elements/_item.scss
app/react/Attachments/components/AttachmentsList.js
app/react/Entities/components/ReferencesGroup.js
app/react/Viewer/components/ConnectionsList.js

Fixes issue #684 
PR check list:
QA check list:

Change delete button backgrounds

---

app/react/App/scss/elements/_item.scss
app/react/Layout/Item.js
app/react/Layout/scss/sidepanel.scss
app/react/Uploads/components/UploadBox.js
app/react/Uploads/components/UploadDoc.js
app/react/Uploads/components/UploadEntity.js
app/react/Uploads/components/specs/UploadEntity.spec.js

Fixes issue #532 
PR check list:
QA check list:

#532 - Unpublished docs style

---

app/react/Templates/actions/specs/templateActions.spec.js
app/react/Templates/actions/templateActions.js

Fixes issue #701 
PR check list:
QA check list:

Fixed bug when creating new multiselect property on template.

---

app/react/Connections/actions/specs/actions.spec.js
app/react/Library/components/ViewMetadataPanel.js
app/react/Metadata/components/MetadataFormButtons.js
app/react/Metadata/components/specs/MetadataFormButtons.spec.js

Fixes issue #599 
PR check list:
QA check list:

599 view button

---

app/react/App/scss/elements/_item.scss
app/react/App/scss/styles.scss

Fixes issue #705 
PR check list:
QA check list:

705 Fix card tooltip: rendering in top of label

---

app/react/App/RouteHandler.js
app/react/Layout/PrintDate.js
app/react/Metadata/helpers/formater.js

Fixes issue #694 
PR check list:
QA check list:

route handle now sets the current locale to moment.js

---

app/react/Entities/components/EntityViewer.js
app/react/Entities/components/ReferencesGroup.js

Fixes issue #696 
PR check list:
QA check list:

entityViewer panel with group titles translated

---

app/react/App/scss/layout/_nav.scss

Fixes issue #716 
PR check list:
QA check list:

Fix closeSidepanel button position to not overlap other tabs

---

app/react/Forms/components/Nested.js
app/react/Forms/components/specs/Nested.spec.js
app/react/Metadata/helpers/formater.js

Fixes issue #695 
PR check list:
QA check list:

nested field improvements

---

app/react/Pages/specs/PageView.spec.js
app/react/Settings/actions/navlinksActions.js
app/react/Settings/actions/specs/navlinksActions.spec.js
package.json

Fixes issue #434 
PR check list:
QA check list:

Newly added links in /settings/menu are automatically open for edition

---

app/react/Templates/actions/specs/templateActions.spec.js
app/react/Templates/actions/templateActions.js
app/react/Templates/components/FormConfigNested.js
app/react/Templates/components/specs/FormConfigNested.spec.js

Fixes issue #565 
PR check list:
QA check list:

FormConfigNested bug fixes

---

app/api/i18n/systemKeys.js
app/react/App/scss/elements/_draggable.scss
app/react/App/scss/elements/_panel.scss
app/react/App/scss/elements/_tooltip.scss
app/react/I18N/components/EditTranslationForm.js
app/react/Templates/EditTemplate.js
app/react/Templates/components/FormConfigCommon.js
app/react/Templates/components/FormConfigInput.js
app/react/Templates/components/Icons.js
app/react/Templates/components/MetadataProperty.js
app/react/Templates/components/MetadataTemplate.js
app/react/Templates/components/PrioritySortingLabel.js
app/react/Templates/components/specs/FormConfigCommon.spec.js
app/react/Templates/components/specs/MetadataProperty.spec.js
app/react/Templates/components/specs/MetadataTemplate.spec.js
app/react/Templates/reducers/reducer.js
app/react/Templates/specs/EditTemplate.spec.js
app/react/Templates/utils/templateCommonProperties.js
app/react/utils/prioritySortingCriteria.js
app/react/utils/specs/prioritySortingCriteria.spec.js

Fixes issue #152 
PR check list:
QA check list:

152 common properties

---

app/react/Forms/components/MultiSelect.js
package.json

Fixes issue #735 
PR check list:
QA check list:

Normalized multiselects search string to match elements with accents

---

app/react/Documents/components/DocumentSidePanel.js
app/react/Entities/components/EntityViewer.js
app/react/Viewer/components/ViewerTextSelectedMenu.js

Fixes issue #699 
PR check list:
QA check list:

Rethink side panel icons

---

app/react/App/scss/modules/_search.scss
app/react/Library/components/SearchBar.js

Fixes issue #733 
PR check list:
QA check list:

Improve Searchbox

---

app/react/Documents/components/DocumentSidePanel.js

Fixes issue #755 #724 
PR check list:
QA check list:

added view document button to metadata panel when in library and not editing

---

app/react/Connections/components/CreateConnectionPanel.js

Fixes issue #750 
PR check list:
QA check list:

Creating a connection to an enetity no longer throws an error

---

app/react/App/scss/modules/_toc.scss
app/react/Documents/components/TocForm.js

Fixes issue #766
PR check list:
QA check list:

#766 - Fix TOC inputs styles

---

app/react/Routes.js
couchdb/reset_elastic_index.js
package.json

Fixes issue #525
PR check list:
QA check list:

Update react router

---

app/react/App/scss/modules/_markdown.scss

Fixes issue #733
PR check list:
QA check list:

#733 - Make tables with equal column width

---

app/react/App/scss/config/_materials.scss
app/react/App/scss/config/_typography.scss
app/react/App/scss/elements/_alerts.scss
app/react/App/scss/elements/_item.scss
app/react/App/scss/layout/_header.scss
app/react/App/scss/modules/_markdown.scss
app/react/App/scss/modules/_metadata-view.scss
app/react/Layout/TemplateLabel.js
app/react/Layout/scss/sidepanel.scss
app/react/Settings/components/TranslationsList.js

Improved styles on cards

---

app/react/App/scss/config/_materials.scss
app/react/App/scss/elements/_tooltip.scss
app/react/App/scss/modules/_search.scss
app/react/Timeline/scss/_timeline.scss

Style improvements

---

app/react/App/scss/elements/_tooltip.scss
app/react/App/scss/layout/_footer.scss
app/react/App/scss/modules/_metadata-view.scss
app/react/Timeline/scss/_timeline.scss

Quick fixes some css properties/variables

---

app/react/Thesauris/actions/specs/thesauriActions.spec.js
app/react/Thesauris/actions/specs/thesaurisActions.spec.js
app/react/Thesauris/actions/thesauriActions.js
app/react/Thesauris/actions/thesaurisActions.js
app/react/Thesauris/components/ThesauriForm.js

Fixes issue #368 
PR check list:
QA check list:

now the dictionaries properly disapear after deleting them

---

app/react/App/scss/elements/_item.scss
app/react/App/scss/modules/_search.scss

Improve CSS on filters and cards

---

app/react/App/scss/config/_typography.scss
app/react/App/scss/elements/_item.scss
app/react/App/scss/modules/_metadata-view.scss

We have improved the label readability those days but it was not enough improvement. This is another iteration made by @RafaPolit and me in order to get better label readability on little font sizes.
- - - - -
PR check list:
QA check list:

Improve label readability

---

app/api/documents/elastic.js

Fixes issue #350 
PR check list:
QA check list:

deleted unused and unecesary elastic file

---

app/react/App/scss/modules/_search.scss
app/react/Forms/components/DateRange.js
app/react/Forms/components/NumericRange.js

Fixes issue #
PR check list:
QA check list:

#808 - Numeric filters styles

---

app/react/Thesauris/scss/thesauris.scss

Fixes issue #824
PR check list:
QA check list:

#824 - Fix thesauris input width

---

app/react/App/scss/config/_typography.scss
app/react/App/scss/modules/_toc.scss

Fixes issue #813 
PR check list:
QA check list:

#813 - Improve TOC styling

---

app/react/App/scss/modules/_document.scss
app/react/Connections/components/CreateConnectionPanel.js

Fixes issue #819 
PR check list:
QA check list:

#819 Edit "Create connection" text + fix searchbox margin

---

app/react/App/scss/modules/_ContextMenu.scss
app/react/Uploads/components/UploadsMenu.js

Fixes issue #820
PR check list:
QA check list:

#820 - Add label to create Entity button

---

app/react/Library/components/FiltersForm.js
app/react/utils/debounce.js

Fixes issue #809 
PR check list:
QA check list:

Debounce library search

---

app/react/Forms/components/DateRange.js
app/react/I18N/t.js
app/react/Library/actions/specs/libraryActions.spec.js
app/react/Library/components/Doc.js
app/react/Router.js

Fixes issue #799 
PR check list:
QA check list:

Clicking on view entity, no longer selects the card in the library side panel

---

app/react/App/scss/modules/_toc.scss

Fixes issue #854 
PR check list:
QA check list:

#854 - Update font sizes on ToC

---

app/react/App/scss/modules/_markdown.scss
app/react/App/scss/utilities/_utilities.scss
app/react/Forms/components/MarkDown.js
app/react/Layout/Item.js
app/react/Metadata/components/ShowMetadata.js
app/react/Pages/components/PageViewer.js
app/react/utils/marked.js
app/react/utils/specs/marked.spec.js
package.json
yarn.lock

Fixes issue #
PR check list:
QA check list:

Added YouTube parser to the marked service.

---

app/api/attachments/routes.js
app/api/upload/routes.js
app/api/upload/specs/fixtures.js
app/api/upload/specs/routes.spec.js
app/react/App/scss/modules/_settings-metadata.scss
app/react/Attachments/components/AttachmentsList.js
app/react/Metadata/components/UploadButton.js

Fixes issue #889
PR check list:
QA check list:

889 reupload document

---

app/api/search/search.js
app/api/search/specs/search.spec.js

Fixes issue #875
PR check list:
QA check list:

Searching an empty term now returns empty suggestions.

---

app/api/entities/entities.js
app/api/entities/specs/entities.spec.js
app/api/entities/specs/fixtures.js
app/api/utils/error_handling_middleware.js
app/api/utils/specs/error_handling_middleware.spec.js

Fixes issue #899
PR check list:
QA check list:

changing a template of an entity now deletes all related metadata connections

---

app/react/App/scss/modules/_metadata-view.scss

Fixes issue #883 
PR check list:
QA check list:

883 - Styles not loaded properly on Entity viewer

---

app/react/Metadata/components/SelectMultiplePanel.js

Fixes issue #884 
PR check list:
QA check list:

884 - Change Save button position when editing multiple files

---

app/react/App/scss/elements/_item.scss

Fixes issue #885
PR check list:
QA check list:

885 - Make selection highlight stronger

---

app/react/App/scss/elements/_dropdown.scss

Fix dropdown position

---

app/react/App/scss/config/_colors.scss
app/react/App/scss/elements/_controls.scss
app/react/App/scss/elements/_item.scss
app/react/Attachments/components/AttachmentsList.js
app/react/Library/components/Doc.js
app/react/Metadata/components/UploadButton.js
app/react/Metadata/components/specs/UploadButton.spec.js
app/react/Uploads/components/UploadDoc.js
app/react/Uploads/components/UploadEntity.js
app/react/Viewer/components/ConnectionsList.js

Needed for #859, but it's a general improve.
PR check list:
QA check list:

Updating classes for button states

---

app/react/App/scss/modules/_settings-translations.scss

Fixes issue #932 
PR check list:
QA check list:

#932 - Fix translation grid

---

app/react/App/scss/elements/_item.scss

Fixes issue #937 
PR check list:
QA check list:

#937 - Remove text highlight on multiselect

---

app/react/App/scss/elements/_protip.scss
app/react/App/scss/fixes.scss
app/react/App/scss/modules/_uploads.scss
app/react/App/scss/styles.scss
app/react/Uploads/components/UploadBox.js

Fixes issue #934 
PR check list:
QA check list:

#934 - Upload tips

---

app/react/App/scss/layout/_content.scss
app/react/App/scss/layout/_header.scss
app/react/App/scss/modules/_entity.scss

Fixes issue #944 
PR check list:
QA check list:

#944 - Critical mobile CSS bugs

---

app/react/Uploads/components/UploadBox.js

Fixes issue #934 
PR check list:
QA check list:

#934 Change protip sentence on uploads

---

app/react/Documents/components/DocumentSidePanel.js
app/react/Viewer/components/Viewer.js
nightmare/paths/publishDocument.spec.js

Fixes issue #713
PR check list:
QA check list:

713 sidepanel open documents

---

app/api/auth/routes.js
package.json
yarn.lock

Fixes issue #22 
PR check list:
QA check list:

added db sessions and fixed deprecation warnings

---

app/react/App/scss/layout/_content.scss
app/react/App/scss/modules/_entity.scss
app/react/App/scss/modules/_search.scss
app/react/Entities/EntityView.js
app/react/Entities/actions/actionTypes.js
app/react/Entities/actions/uiActions.js
app/react/Entities/components/EntityViewer.js
app/react/Entities/components/SearchButton.js
app/react/Entities/reducers/specs/uiReducer.spec.js
app/react/Entities/reducers/uiReducer.js
app/react/Layout/scss/sidepanel.scss
app/react/Library/components/SearchButton.js
app/react/Uploads/UploadsRoute.js
nightmare/helpers/extensions.js
nightmare/helpers/nightmare.js
nightmare/helpers/selectors.js
nightmare/smokes/mobileSidePanels.spec.js
yarn.lock

Fixes issue #947, #948, #949 
PR check list:
QA check list:

Sidepanel fix mobile

---

app/react/App/scss/elements/_item.scss
app/react/App/scss/elements/_protip.scss
app/react/Layout/DocumentsList.js

Fixes issue #909 
PR check list:
QA check list:

#909 Add multiselect tip

---

app/react/App/scss/elements/_item.scss
app/react/Attachments/components/Attachment.js

Fixes issue #966 
PR check list:
QA check list:

#966 Attachments alignment

---

app/react/Metadata/helpers/formater.js

Fixes issue #611 
PR check list:
QA check list:

sorting multiselect values when showing metadata

---

app/react/Entities/containers/EntityForm.js
app/react/Entities/containers/specs/EntityForm.spec.js
app/react/Library/containers/DocumentForm.js
app/react/Library/containers/EntityForm.js
app/react/Metadata/components/MetadataForm.js
app/react/Metadata/components/specs/MetadataForm.spec.js
app/react/Viewer/containers/DocumentForm.js
app/react/Viewer/containers/specs/DocumentForm.spec.js
nightmare/paths/multiEdit.spec.js

Fixes issue #1001 
PR check list:
QA check list:

1001 e2e fix

---

app/react/Layout/Item.js

Fixes issue #943 
PR check list:
QA check list:

prevent the upload entity staus appear on already uploaded documents

---

app/react/Settings/Settings.js
app/react/Settings/specs/Settings.spec.js

Fixes issue #974
PR check list:
QA check list:

Settings secction now requests the settings

---

app/react/DocumentForm/components/FormGroup.js
app/react/DocumentForm/components/specs/FormGroup.spec.js
app/react/Templates/components/MetadataTemplate.js
app/react/Thesauris/components/ThesauriForm.js

Fixes issue #572 
PR check list:
QA check list:

Dictionaries title is now required

---

app/react/Templates/EditTemplate.js
app/react/Templates/NewTemplate.js
app/react/Templates/specs/NewTemplate.spec.js

Fixes issue #994 
PR check list:
QA check list:

fixed error when navigating back and forth to a template form and try to edit a property name

---

app/react/App/scss/modules/_document.scss
app/react/Layout/scss/sidepanel.scss
app/react/Viewer/scss/document.scss

Fixes issue #930 
PR check list:
QA check list:

#930 - Improve text highlight inside Documents

---

app/react/Layout/scss/sidepanel.scss
nightmare/helpers/extensions.js
nightmare/helpers/nightmare.js
nightmare/helpers/selectors.js
nightmare/helpers/tests.css
nightmare/paths/attachments.spec.js
nightmare/paths/filters.spec.js
nightmare/paths/metadata.spec.js
nightmare/paths/multiEdit.spec.js
nightmare/paths/publishDocument.spec.js
nightmare/paths/publish_entity.spec.js
nightmare/paths/references.spec.js
nightmare/paths/toc.spec.js
nightmare/paths/translations.spec.js
nightmare/smokes/loggedin.smoke.spec.js

Fixes issue #1013
PR check list:
QA check list:

E2e isvisible

---

app/react/App/scss/layout/_nav.scss
app/react/Documents/components/DocumentSidePanel.js
nightmare/helpers/selectors.js

Fixes issue #964 
PR check list:
QA check list:

#964 - Reorder tabs on sidepanel

---

app/react/App/scss/modules/_search.scss
app/react/App/scss/styles.scss
app/react/App/scss/vendor/_react-datepicker.scss

Fixes issue #1022 
PR check list:
QA check list:

#1022 - Fix datepicker styles + isolate them in new scss file

---

app/react/App/Menu.js
app/react/Library/Library.js
app/react/Library/actions/filterActions.js
app/react/Library/actions/libraryActions.js
app/react/Library/actions/specs/filterActions.spec.js
app/react/Library/actions/specs/libraryActions.spec.js
app/react/Library/components/SortButtons.js
app/react/Library/components/specs/SortButtons.spec.js
app/react/Library/reducers/reducer.js
app/react/Library/specs/Library.spec.js
app/react/Uploads/UploadsRoute.js
app/react/Uploads/specs/UploadsRoute.spec.js
app/react/utils/prioritySortingCriteria.js
app/react/utils/specs/prioritySortingCriteria.spec.js

Fixes issue #1004
PR check list:
QA check list:

1004 priority sorting

---

app/react/App/scss/elements/_alerts.scss
app/react/Settings/components/CollectionSettings.js
app/react/Settings/components/NavlinksSettings.js

Fixes issue #
PR check list:
QA check list:

Fix settings > menu layout

---

app/react/Users/components/EditUser.js

Fixes issue #1006 
PR check list:
QA check list:

edit user form now displays the name of the user being edited

---

app/react/Layout/Item.js
app/react/Library/components/Doc.js
app/react/Library/components/UploadEntityStatus.js
app/react/Library/components/specs/UploadEntityStatus.spec.js

Fixes issue #48 
PR check list:
QA check list:

Moved UploadStatus to Doc, that passes it to Item

---

app/react/Library/components/FiltersForm.js

Fixes issue #1029 
PR check list:
QA check list:

fixed issue with filters disapearing

---

app/api/documents/routes.js
app/api/entities/routes.js
app/react/App/NoMatch.js
app/react/Router.js
app/react/Routes.js
app/react/utils/api.js
app/react/utils/specs/api.spec.js

Fixes issue #24 
PR check list:
QA check list:

404 redirect for missing entities or documents

---

app/react/Documents/components/SearchText.js
app/react/Entities/components/EntityViewer.js
app/react/I18N/t.js
app/react/Library/components/UploadEntityStatus.js
app/react/Pages/PageView.js
app/react/Pages/specs/PageView.spec.js
app/react/Pages/utils/pageItemLists.js
app/react/Pages/utils/specs/pageItemLists.spec.js
app/react/RelationTypes/actions/specs/relationTypesActions.spec.js
app/react/Viewer/actions/specs/documentActions.spec.js
app/react/utils/markdownEscapedValues.js
app/react/utils/specs/markdownEscapedValues.spec.js

Fixes issue #1056 
PR check list:
QA check list:

1056 escape codes parsing

---

app/react/App/scss/modules/_entity.scss

Fixes issue #915 
PR check list:
QA check list:

#915 - Remove hover styles for cards inside entities

---

app/api/i18n/systemKeys.js
app/react/App/scss/elements/_dropdown.scss
app/react/Library/components/SortButtons.js
app/react/Library/components/specs/SortButtons.spec.js

Fixes issue #954
PR check list:
QA check list:

#954 - Improve sorting dropdown

---

app/react/App/scss/modules/_login.scss
app/react/Users/Login.js
app/react/Users/specs/Login.spec.js

Fixes issue #1017 #1016 
PR check list:
QA check list:

Updated login form

---

app/react/Pages/EditPage.js

Fixes issue #1067 
PR check list:
QA check list:

reseting page form when mounted

---

app/react/Metadata/components/MetadataFormFields.js

Fixes issue #1062 
PR check list:
QA check list:

added prefix to multiselect in metadata form

---

app/react/Forms/components/MultiSelect.js

Fixes issue #1050 
PR check list:
QA check list:

Sorting multiselects filter options by amount of results

---

app/react/App/scss/elements/_dropdown.scss

Fixes issue #1085 
PR check list:
QA check list:

#1085 - Make sort-by all clickable

---

app/react/Library/actions/libraryActions.js
app/react/Library/actions/specs/libraryActions.spec.js

Fixes issue #1084 
PR check list:
QA check list:

fixed bug while editing metadata

---

app/api/search/search.js
app/react/Layout/Item.js
app/react/Library/components/FiltersForm.js
app/react/Metadata/actions/actions.js
app/react/Metadata/components/MetadataFormFields.js
app/react/Metadata/components/specs/MetadataFormFields.spec.js
app/react/Metadata/helpers/formater.js
app/react/Metadata/helpers/specs/validator.spec.js
app/react/Metadata/helpers/validator.js
app/react/Templates/components/Icons.js
app/react/Templates/components/TemplateCreator.js

Fixes issue #1032 
PR check list:
QA check list:

Daterange field

---

app/react/App/scss/elements/_item.scss
app/react/App/scss/modules/_metadata-view.scss
app/react/Layout/Item.js
app/react/Layout/specs/Item.spec.js
app/react/Metadata/components/ShowMetadata.js
app/react/Metadata/helpers/formater.js
app/react/Metadata/helpers/validator.js

Fixes issue #1100
PR check list:
QA check list:

1100 metadata rendering

---

app/react/App/scss/elements/_item.scss
app/react/Layout/Item.js

Fixes issue #1111 
PR check list:
QA check list:

#1111 - Render date titles by default on cards

---

app/react/Pages/PageView.js
app/react/Pages/specs/PageView.spec.js
app/react/Pages/utils/pageItemLists.js
app/react/Pages/utils/specs/pageItemLists.spec.js

Fixes issue #1112
PR check list:
QA check list:

Made the pages list item limit configurable.

---

app/api/entities/entitiesModel.js
app/api/references/connectionsModel.js
app/api/references/references.js
app/api/search/documentQueryBuilder.js
app/api/search/search.js

Fixes issue #1133 
PR check list:
QA check list:

Indexing referenced documents in mongo

---

app/react/App/scss/modules/_document.scss
app/react/App/scss/modules/_search.scss
app/react/Documents/components/SearchText.js

Fixes issue #1149 
PR check list:
QA check list:

#1149 Improve search results on sidepanel

---

app/react/App/scss/modules/_entity.scss
app/react/Metadata/components/SelectMultiplePanel.js

Quick fix related to #1064, but isolated to it's own PR:
PR check list:
QA check list:

Improve how multiple cards are rendered in sidepanel

---

app/react/ConnectionsList/actions/actions.js
app/react/ConnectionsList/actions/specs/actions.spec.js

New implementation is sending storeKey as first parameter.
Fixes issue #1135 
PR check list:
QA check list:

Changed loadMoreReferences to reflect new implementation

---

app/react/App/scss/elements/_item.scss

Hotfix - Snippet colors on cards

---

app/api/references/references.js

Fixes issue #1133 
PR check list:
QA check list:

Improve the load speed when entity has many connections

---

app/api/search/documentQueryBuilder.js
app/api/search/specs/search.spec.js
nightmare/paths/metadata.spec.js
yarn.lock

Fixes issue #1163 
PR check list:
QA check list:

fixed how aggregations are generated for unpublished

---

app/react/App/scss/layout/_content.scss

Fixes issue #1169
PR check list:
QA check list:

#1169 - Fix z-index issue between entity titles and sidepanel

---

app/api/search/documentQueryBuilder.js
app/react/Forms/components/MultiSelect.js
app/react/Forms/components/specs/MultiSelect.spec.js
app/react/Library/actions/filterActions.js
app/react/Library/components/FiltersForm.js
app/react/Library/helpers/libraryFilters.js
nightmare/paths/searchFilters.spec.js

Fixes issue #1129 #1124 #913 
PR check list:
QA check list:

Fix filters

---

app/api/config/elasticIndexes.js
app/api/search/documentQueryBuilder.js
app/api/search/search.js
app/api/search/specs/fixtures_elastic.js
app/api/search/specs/search.spec.js
database/elastic_mapping.js

Fixes issue #1134
Deploying this will require a re-index
PR check list:
QA check list:

1134 elastic ordering

---

app/react/Metadata/actions/actions.js
app/react/Metadata/actions/specs/actions.spec.js
app/react/Metadata/components/SelectMultiplePanel.js
app/react/Metadata/components/specs/SelectMultiplePanel.spec.js

Fixes issue #1141 
PR check list:
QA check list:

	multiple edition default type option works properly

---

app/api/search/search.js
app/api/search/specs/search.spec.js
app/react/Metadata/helpers/formater.js

Fixes issue #1180 
PR check list:
QA check list:

1180 several bugs

---

app/api/i18n/systemKeys.js
app/api/settings/settingsModel.js
app/react/App/App.js
app/react/App/GoogleAnalytics.js
app/react/App/specs/GoogleAnalytics.spec.js
app/react/Routes.js
app/react/Settings/components/CollectionSettings.js
app/react/Settings/components/specs/CollectionSettings.spec.js
nightmare/helpers/selectors.js

Fixes issue #971 
PR check list:
QA check list:

Google Analytics integration

---

app/api/search/documentQueryBuilder.js
app/api/search/specs/fixtures_elastic.js
app/api/search/specs/search.spec.js
app/react/Library/actions/libraryActions.js

Fixes issue #1162
PR check list:
QA check list:

fix for "no type filter"

---

app/react/App/LoadingProgressBar.js
app/react/App/Root.js
app/react/App/specs/LoadingProgressBar.spec.js
app/react/utils/api.js
app/react/utils/specs/api.spec.js
package.json
server.js
yarn.lock

Fixes issue #296 
PR check list:
QA check list:

Progress bar spike

---

app/api/i18n/systemKeys.js
app/api/search/documentQueryBuilder.js
app/api/search/specs/search.spec.js
app/react/App/scss/modules/_search.scss
app/react/Forms/components/MultiSelect.js
app/react/Forms/components/NestedMultiselect.js
app/react/Forms/components/Switcher.js
app/react/Forms/components/specs/Switcher.spec.js
app/react/Forms/index.js
app/react/Library/Library.js
app/react/Library/components/FiltersForm.js
app/react/Library/helpers/libraryFilters.js
app/react/Library/helpers/specs/libraryFilters.spec.js
app/react/ReactReduxForms/index.js
app/react/Viewer/utils/Text.js
nightmare/helpers/extensions.js
nightmare/paths/searchFilters.spec.js

Fixes issue #1119 #1109 
PR check list:
QA check list:

1119 and or

---

app/api/attachments/routes.js
app/api/entities/entities.js
app/api/entities/specs/entities.spec.js

Fixes issue #1205
PR check list:
QA check list:

1205 partial updates indexing

---

app/react/App/scss/config/_colors.scss
app/react/App/scss/elements/_base.scss
app/react/App/scss/elements/_controls.scss
app/react/App/scss/elements/_dropdown.scss
app/react/App/scss/elements/_item.scss
app/react/App/scss/elements/_panel.scss
app/react/App/scss/layout/_header.scss
app/react/App/scss/layout/_nav.scss
app/react/App/scss/modules/_document.scss
app/react/App/scss/modules/_library.scss
app/react/App/scss/modules/_markdown.scss
app/react/App/scss/modules/_search.scss
app/react/App/scss/modules/_settings-metadata.scss
app/react/App/scss/vendor/_react-datepicker.scss
app/react/Layout/scss/sidepanel.scss
app/react/Timeline/scss/_timeline.scss
app/react/Viewer/scss/createmodal.scss
app/react/Viewer/scss/document.scss

Renaming color variables for better use in CSS.
PR check list:
QA check list:

Renaming color variables

---

database/elastic_mapping.js

Fixes issue #1174 
PR check list:
QA check list:

Replaced LONG occurrences with DOUBLE, creationDate is LONG

---

app/api/entities/entities.js
app/api/entities/specs/entities.spec.js
app/api/search/specs/search.spec.js
database/elastic_mapping.js

Fixes issue #1225 
PR check list:
QA check list:

1225 full text indexation

---

app/api/settings/settings.js
app/api/settings/specs/settings.spec.js
app/api/templates/routes.js
app/api/templates/specs/routes.spec.js
app/api/templates/specs/templates.spec.js
app/api/templates/templates.js
app/react/App/scss/modules/_settings-filters.scss
app/react/Library/components/DocumentTypesList.js
app/react/Settings/components/DocumentTypesList.js
app/react/Settings/components/EntityTypesList.js
app/react/Settings/components/FiltersForm.js
app/react/sockets.js

Fixes issue #1195 #1140
PR check list:
QA check list:

Fixed countByTemplate endpoint

---

app/react/App/scss/config/_colors.scss
app/react/App/scss/layout/_hero.scss
app/react/App/scss/modules/_markdown.scss
app/react/App/scss/styles.scss
app/react/App/scss/vendor/_recharts.scss
app/react/Charts/components/LibraryCharts.js
app/react/Charts/components/specs/LibraryCharts.spec.js
app/react/Charts/utils/colorScheme.js
app/react/CustomHooks/components/cejilChart001.js
app/react/CustomHooks/components/cejilChart001Bars.js
app/react/CustomHooks/components/cejilHero.js
app/react/CustomHooks/index.js
app/react/Pages/PageView.js
app/react/Pages/components/PageViewer.js
app/react/Pages/components/specs/PageViewer.spec.js
app/react/Pages/specs/PageView.spec.js

Fixes issue #1231, #1238, #1230
PR check list:
QA check list:

1231 custom graph cejil

---

app/api/search/documentQueryBuilder.js

Fixes issue #1210 
PR check list:
QA check list:

Set fuzziness to 0 in full text search.

---

app/react/App/scss/vendor/_react-datepicker.scss
app/react/Forms/components/MultiDate.js
app/react/Forms/components/MultiDateRange.js
app/react/Forms/components/specs/MultiDate.spec.js
app/react/Forms/components/specs/MultiDateRange.spec.js

Fixes issue #1237
PR check list:
QA check list:

#1237 - Fixing firefox bug when trying to delete multidate values from metadata

---

app/react/App/scss/modules/_search.scss

Fixes issue #1243, #1217
PR check list:
QA check list:

#1243, #1217 Removing truncated text + fixing filter btn position

---

app/react/App/scss/modules/_document.scss
app/react/App/scss/modules/_entity.scss
nightmare/zones/fullTextSearch.spec.js

Fixes issue #1272 
PR check list:
QA check list:

#1272 Fixing item sidepanel paddings

---

app/react/App/scss/elements/_item.scss
nightmare/zones/fullTextSearch.spec.js

Fixes issue #1264 
PR check list:
QA check list:

#1264 Showing labels on cards

---

app/react/Library/helpers/libraryFilters.js
app/react/Library/helpers/specs/libraryFilters.spec.js

Fixes issue #1256 
PR check list:
QA check list:

setted default value for text filters to an empty string

---

app/api/search/documentQueryBuilder.js
app/api/search/specs/search.spec.js

Fixes issue #1220 
PR check list:
QA check list:

Full text search will affect aggregation numbers

---

app/react/App/scss/elements/_item.scss
app/react/utils/marked.js
app/react/utils/specs/marked.spec.js

Fixes issue #1281
PR check list:
QA check list:

1281 vimeo support

---

app/react/Library/components/LibraryFilters.js
app/react/Library/components/SearchButton.js

Fixes issue #1278 
PR check list:
QA check list:

Filters panel opens and closes in mobile

---

app/react/Library/reducers/specs/uiReducer.spec.js
app/react/Library/reducers/uiReducer.js

Fixes issue #1296 
PR check list:
QA check list:

Library filters panel is now close by default in the library

---

app/react/PDF/components/PDF.js
app/react/PDF/components/specs/PDF.spec.js
app/react/Viewer/actions/specs/uiActions.spec.js
app/react/Viewer/actions/uiActions.js
app/react/Viewer/components/Document.js
app/react/Viewer/components/specs/Document.spec.js

Fixes issue #1261
PR check list:
QA check list:

improved performance of snippet higligting

---

app/react/App/scss/modules/_page.scss
app/react/Pages/components/PageViewer.js

Fixes issue #1262 
PR check list:
QA check list:

added footer into custom pages view

---

app/react/App/scss/layout/_footer.scss
app/react/App/scss/modules/_document.scss
app/react/Library/Library.js
app/react/Pages/components/PageViewer.js
app/react/Uploads/UploadsRoute.js

Hotfix.
PR check list:
QA check list:

Fixing footer position inside documents and uploads

---

app/react/App/Footer.js

Fixes issue #1303 
PR check list:
QA check list:

Uploads link in footer will only appear while loggedin

---

app/react/Layout/Item.js

Fixes issue #1290 
PR check list:
QA check list:

Item will show empty sorting properties with the label and a dash

---

app/api/search/documentQueryBuilder.js
app/react/App/scss/modules/_search.scss
app/react/Documents/components/SearchText.js

Fixes issue #1159 
PR check list:
QA check list:

1159 snippet size css

---

app/api/i18n/systemKeys.js
app/api/search/search.js
app/api/search/specs/search.spec.js
app/react/App/scss/elements/_item.scss
app/react/Layout/Item.js
nightmare/helpers/extensions.js
nightmare/zones/fullTextSearch.spec.js

Fixes issue #1161 
PR check list:
QA check list:

show link in card when there are more than one snippet

---

app/api/entities/entities.js
app/api/entities/specs/entities.spec.js
app/api/search/search.js
app/api/search/specs/search.spec.js
app/api/upload/specs/routes.spec.js
database/reset_elastic_index.js

Fixes issue #1294
PR check list:
QA check list:

elastic index errors are now being console.log (this allows to be able to check the journal log for this errors)

---

database/elastic_mapping.js

Fixes issue #1309 
PR check list:
QA check list:

fixed elastic mapping, language analyzers where not properly configured

---

app/api/i18n/systemKeys.js
app/react/Layout/Item.js

Fixes issue #1321 
PR check list:
QA check list:

Clarified messages for lack of sorting property

---

app/api/documents/specs/documents.spec.js
app/api/entities/entities.js
app/api/entities/specs/entities.spec.js
app/api/entities/specs/fixtures.js
app/api/search/search.js

Fixes issue #1189 #1240, also fixed for multidaterange property.
PR check list:
QA check list:

1189 sanitize multidate

---

app/react/Documents/components/DocumentSidePanel.js
app/react/Documents/components/SnippetsTab.js

Fixes issue #1157 
PR check list:
QA check list:

showing number of snippets on the panel tab

---

app/api/users/specs/fixtures.js
app/api/users/specs/users.spec.js
app/api/users/users.js
app/react/Users/ResetPassword.js
app/react/Users/specs/ResetPassword.spec.js

Fixes issue #1292
PR check list:
QA check list:

1292 password process

---

app/api/migrations/users_role_index.js
app/api/users/usersModel.js
run_migration.js

Fixes issue #1325 
PR check list:
QA check list:

User role is no longer unique as intended

---

app/api/i18n/systemKeys.js
app/api/search/documentQueryBuilder.js
app/api/search/search.js
app/react/Library/actions/libraryActions.js
app/react/Library/actions/specs/libraryActions.spec.js
app/react/Library/components/SearchBar.js
app/react/Library/components/SortButtons.js
app/react/Library/components/specs/SortButtons.spec.js
app/react/Library/helpers/libraryFilters.js
app/shared/JSONRequest.js
nightmare/helpers/extensions.js
nightmare/paths/metadata.spec.js

Fixes issue #1116 
PR check list:
QA check list:

1116 sort by relevance

---

app/api/search/documentQueryBuilder.js

Fixes issue #1330 
PR check list:
QA check list:

boosted exact match text search results

---

app/api/entities/entities.js
app/api/entities/specs/entities.spec.js

Fixes issue #1293 
PR check list:
QA check list:

changed order of entity delete processes to reduce the chance of data corruption on error

---

app/react/App/scss/config/_colors.scss
app/react/App/scss/elements/_dropdown.scss
app/react/App/scss/elements/_item.scss
app/react/App/scss/layout/_header.scss
app/react/App/scss/layout/_nav.scss
app/react/App/scss/layout/_sidepanel.scss
app/react/App/scss/modules/_document.scss
app/react/App/scss/modules/_library.scss
app/react/App/scss/modules/_markdown.scss
app/react/App/scss/modules/_search.scss
app/react/App/scss/modules/_settings-metadata.scss
app/react/Timeline/scss/_timeline.scss
app/react/Viewer/scss/createmodal.scss
app/react/Viewer/scss/document.scss

Cleaning CSS colors for better theming through instances

---

app/api/i18n/systemKeys.js
app/react/Library/components/LibraryFilters.js
app/react/Settings/components/FiltersForm.js
app/react/Settings/components/SettingsNavigation.js

Fixes issue #890
PR check list:
QA check list:

#890 - Adding information panel insite Settings > Filters

---

app/api/i18n/systemKeys.js
app/api/search/documentQueryBuilder.js
app/react/App/scss/elements/_dropdown.scss
app/react/App/scss/elements/_item.scss
app/react/App/scss/modules/_entity.scss
app/react/App/scss/modules/_relationships.scss
app/react/App/scss/styles.scss
app/react/ConnectionsList/actions/actions.js
app/react/ConnectionsList/actions/specs/actions.spec.js
app/react/ConnectionsList/components/ConnectionsList.js
app/react/ConnectionsList/components/ToggleStyleButtons.js
app/react/ConnectionsList/components/specs/ConnectionsList.spec.js
app/react/ConnectionsList/components/specs/ToggleStypeButtons.spec.js
app/react/ConnectionsList/reducers/reducer.js
app/react/Entities/EntityView.js
app/react/Entities/specs/EntityView.spec.js
app/react/Layout/DocumentsList.js
app/react/Layout/specs/DocumentsList.spec.js
app/react/Relationships/components/RelationshipsGraph.js
app/react/Relationships/components/specs/RelationshipsGraph.spec.js
package.json
yarn.lock

Fixes issue #1331 
PR check list:
QA check list:

1331 relationships hub stage1

---

app/react/App/scss/modules/_slider.scss
app/react/App/scss/styles.scss
app/react/Pages/components/ItemList.js
app/react/Pages/components/slider.js

Styling slider with h2 support

---

app/api/entities/entities.js
nightmare/helpers/selectors.js
nightmare/paths/toc.spec.js

Fixes issue #855 
PR check list:
QA check list:

Toc fallback for languages

---

app/react/Documents/DocumentsAPI.js
app/react/Documents/specs/DocumentsAPI.spec.js
app/react/Entities/EntitiesAPI.js
app/react/Entities/specs/EntitiesAPI.spec.js

Fixes issue #1345 
PR check list:
QA check list:

delete now sends only the required data on the url

---

app/api/search/search.js
app/api/search/specs/search.spec.js
app/react/Attachments/components/AttachmentForm.js
app/shared/languages.js
app/shared/languagesList.js
app/shared/specs/languages.spec.js

Fixes issue #1337 
PR check list:
QA check list:

added other language option to the list of languages

---

app/react/Charts/components/ListChartToggleButtons.js
app/react/ConnectionsList/reducers/reducer.js
app/react/Entities/EntityView.js
app/react/Entities/components/EntityViewer.js
app/react/Entities/specs/EntityView.spec.js
nightmare/helpers/selectors.js
nightmare/zones/connectionsList.spec.js

Fixes issue #1362 
PR check list:
QA check list:

Graph is now the default view for connections list inside an entity

---

app/react/CustomHooks/components/cejilHero.js
app/react/Pages/components/PageViewer.js
app/react/Pages/components/specs/PageViewer.spec.js

Fixes issue #1368 
PR check list:
QA check list:

Added option to pass links to CejilHero custom hook.

---

app/react/Layout/DocumentsList.js

Fixes issue #1372 
PR check list:
QA check list:

Graph view for connections now has the load more button

---

app/api/relationtypes/relationtypes.js
app/api/relationtypes/specs/relationtypes.spec.js

Fixes issue #1369 
PR check list:
QA check list:

relation types model now generates names and ids for the properties

---

app/react/App/scss/layout/_header.scss

Fixes issue #1070
PR check list:
QA check list:

#1070 - Improving header in mobile

---

app/api/i18n/specs/fixtures.js
app/api/i18n/specs/translations.spec.js
app/api/i18n/translations.js

Fixes issue #
PR check list:
QA check list:

Translations save endpoint now accepts partial updates

---

app/react/App/scss/elements/_item.scss
app/react/App/scss/modules/_library.scss
app/react/App/scss/modules/_page.scss
app/react/App/scss/modules/_search.scss

Fixes issue #1363 
PR check list:
QA check list:

1363 - Expand grid to full width

---

app/api/i18n/translations.js

Fixes issue #1453 
PR check list:
QA check list:

Fix loading current translation data when updating translation

---

app/api/attachments/routes.js
app/api/search/search.js
app/api/templates/templatesModel.js
app/react/Library/helpers/libraryFilters.js
app/react/Templates/components/FormConfigInput.js
app/react/Templates/components/FormConfigSelect.js
app/react/Templates/components/specs/FormConfigInput.spec.js
app/react/Templates/components/specs/FormConfigSelect.spec.js
app/react/Templates/scss/templates.scss
app/shared/comonProperties.js
app/shared/specs/comonProperties.spec.js

Fixes issue #1398 
PR check list:
QA check list:

Default filters for the library

---

app/react/App/scss/modules/_settings.scss

Fixes issue #1408 
PR check list:
QA check list:

#1408 - Fixing safari bug with flexbox wrap on settings

---

app/react/Library/components/FiltersForm.js

Fixes issue #1396 
PR check list:
QA check list:

Updated learn more url link when there is no comon filters

---

.cicrcleci/config.yml

Fixes issue #
PR check list:
QA check list:

circle ci config

---

app/react/App/scss/modules/_page.scss

Fixes issue #1471 
PR check list:
QA check list:

#1471 - Fix graphs width on custom pages

---

app/react/App/scss/modules/_markdown.scss

Fixes issue #1472
PR check list:
QA check list:

#1472 - Fixing Markdown classes

---

app/react/App/scss/layout/_hero.scss
app/react/App/scss/styles.scss

Hotfix hero styles

---

app/react/App/scss/layout/_hero.scss

Fix cejil hero (links and typo)

---

app/react/App/scss/config/_colors.scss
app/react/App/scss/modules/_markdown.scss
app/react/Markdown/components/MarkdownVimeo.js

Fixes issue #1477 
PR check list:
QA check list:

#1477 - Improved styles for timelinks on vimeo

---

app/react/App/scss/layout/_hero.scss
app/react/App/scss/modules/_page.scss

Fixes issue #1459 
PR check list:
QA check list:

1459 - Fix margin on static pages

---

app/react/App/scss/vendor/_nprogress.scss

Fixes issue #1490
PR check list:
QA check list:

#1490 - Remove glitchy shadow on loading bar

---

app/react/Markdown/components/MarkdownYoutube.js

Fixes issue #1491 
PR check list:
QA check list:

1491 - Adding wrapping div to youtube video (as vimeo)

---

app/react/App/scss/elements/_controls.scss
app/react/App/scss/elements/_item.scss
app/react/App/scss/layout/_content.scss
app/react/App/scss/layout/_sidepanel.scss
app/react/App/scss/modules/_attachments.scss
app/react/App/scss/modules/_document.scss
app/react/App/scss/modules/_markdown.scss
app/react/App/scss/modules/_metadata-view.scss
app/react/App/scss/modules/_relationships.scss
app/react/Layout/Item.js
app/react/Layout/TemplateLabel.js
app/react/Layout/specs/Item.spec.js
app/react/Layout/specs/TemplateLabel.spec.js
app/react/Library/components/Doc.js
app/react/Metadata/components/ShowMetadata.js
nightmare/helpers/extensions.js
nightmare/helpers/selectors.js
nightmare/paths/publishDocument.spec.js
nightmare/paths/publishEntity.spec.js
nightmare/zones/entity.spec.js
yarn.lock

Fixes issue #1399  #1400 #1401 #1486
PR check list:
QA check list:

Improve card renderings

---

README.md
app/api/config/ports.js
app/api/documents/specs/fixtures.js
app/api/entities/specs/routes.spec.js
app/api/migrations/fix_multiple_language_state.js
app/api/pages/specs/routes.spec.js
app/api/references/specs/fixtures.js
app/api/references/specs/fixturesForGroup.js
app/api/settings/specs/settings.spec.js
app/api/swagger/swaggerconfig.js
app/api/templates/specs/fixtures.js
app/api/templates/specs/routes.spec.js
app/api/thesauris/specs/fixtures.js
app/api/thesauris/specs/routes.spec.js
app/api/thesauris/specs/thesauris.spec.js
app/api/utils/instrumentRoutes.js
app/api/utils/specs/instrumentRoutes.spec.js
app/shared/JSONUtils.js
app/shared/uniqueID.js
circle.yml

fixed eslint errors and added eslint to circleci

---

database/reindex_elastic.js
database/reset_elastic_index.js

Fixed intermitent error when using reindex script

---

package.json

posintstall download monbo binaries will not happen when installing with --production

---

package.json
yarn.lock

Fixes issue #
PR check list:
QA check list:

added nodemon as devDependency

---

package.json
yarn.lock

downgraded OptimizeCssAssetsWebpackPlugin for the production build with webpack3.6

---

README.md

Fixes issue #
PR checklist:
QA checklist:

commit of shame

---

database/reindex_elastic.js

Fixes issue #
PR checklist:
QA checklist:

properly configured babel reindex_elastic

---

database/blank_state.sh
database/reindex_elastic.js
install_fixtures.sh
nightmare/fixtures/restore.sh
package.json
run.js

Fixes issue #
PR checklist:
QA checklist:

reindex via npm script

---

app/api/migrations/relationships_with_hubs.js

Fixes issue #1540 
PR checklist:
QA checklist:

Added ranges to migrations.

---

app/react/Markdown/MarkdownViewer.js
package.json
yarn.lock

Fixes issue #1380 
PR checklist:
QA checklist:

replaced marked by mark-it

---

app/react/ServerRouter.js
package.json

Fixes issue #1561
PR checklist:
QA checklist:

 ServerRouter properly handles uncaught errors after requestState

---

app/api/i18n/systemKeys.js

Fixes issue #1567 
PR checklist:
QA checklist:

Added missing key Relationship

---

app/react/Forms/components/Select.js
app/react/Forms/components/specs/Select.spec.js

Proper use of proptypes for select component

---

app/react/Users/components/EditUser.js
app/react/Users/components/NewUser.js
app/react/Users/components/UserForm.js
app/react/Users/components/specs/EditUser.spec.js
app/react/Users/components/specs/NewUser.spec.js
app/react/Users/components/specs/UserForm.spec.js

Fixes issue #1439 
PR checklist:
QA checklist:

admins can now edit username and email from other users

---

app/react/Library/helpers/libraryFilters.js
app/react/Library/helpers/specs/libraryFilters.spec.js
app/react/Metadata/components/ValueList.js
app/react/Metadata/components/specs/__snapshots__/ValueList.spec.js.snap

Fixes issue #1585 
PR checklist:
QA checklist:

fix library filters when a relationship field has "any entity or document" selected

---

app/api/upload/routes.js

Fixes issue #1572
PR checklist:
QA checklist:

Added multiple logs to the conversion process to track possible errors

---

app/react/App/scss/elements/_item.scss

Fix video rendering on cards

---

database/reindex_elastic.js

Fixes issue #1592 
PR checklist:
QA checklist:

Using environment variable for elastic search for reindex

---

app/react/Map/Map.js
app/react/Map/specs/Map.spec.js

Fixes issue #
PR checklist:
QA checklist:

Increased default zoom level for maps and function to render markers

---

app/react/Metadata/components/ShowMetadata.js
app/react/Metadata/helpers/formater.js
app/react/Metadata/helpers/specs/formater.spec.js
app/react/Timeline/components/TimelineViewer.js

Fixes issue #
PR checklist:
QA checklist:

formater now assigns markdown type to nested properties

---

app/react/Map/Map.js

Fixes issue #
PR checklist:
QA checklist:

map now accepts size and will respect it

---

package.json

Fixes issue #1591 
PR checklist:
QA checklist:

yarn blank-state now also reindex

---

package.json

Fixes issue #1594 
PR checklist:
QA checklist:

Package version, description and license updated

---

package.json

Fixes issue #
PR checklist:
QA checklist:

added yarn test-debug to execute jest --watch in node --inspect mode

---

app/react/Markdown/CustomHooks/components/CejilChart.js
app/react/Markdown/CustomHooks/components/specs/CejilChart002.spec.js
app/react/Markdown/CustomHooks/components/specs/__snapshots__/CejilChart002.spec.js.snap

Fixes issue #1621 
PR checklist:
QA checklist:

cejilChart now supports "missing" value

---

app/api/auth/privateInstanceMiddleware.js
app/api/auth/specs/privateInstanceMiddleware.spec.js
app/react/Auth/actions.js
app/react/Auth/specs/actions.spec.js
app/react/Users/Login.js
app/react/Users/specs/Login.spec.js

Fixes issue #1626
PR checklist:
QA checklist:

1626 private routes

---

app/api/migrations/migrations/2-sanitize_empty_geolocations/index.js
app/api/migrations/migrations/2-sanitize_empty_geolocations/specs/2-sanitize_empty_geolocations.spec.js
app/api/migrations/migrations/2-sanitize_empty_geolocations/specs/fixtures.js
app/react/Forms/components/Geolocation.js
app/react/Metadata/actions/actions.js
app/react/Metadata/actions/specs/actions.spec.js

Fixes issue #1627 
PR checklist:
QA checklist:

fixed problem when saving geolocation fields empty

---

app/api/migrations/migrations/2-sanitize_empty_geolocations/index.js
app/api/migrations/migrations/2-sanitize_empty_geolocations/specs/2-sanitize_empty_geolocations.spec.js
app/api/migrations/migrations/2-sanitize_empty_geolocations/specs/fixtures.js

Fixes issue #1635 
PR checklist:
QA checklist:

Added case for when entity does not have metadata.

---

app/react/App/Menu.js
app/react/App/specs/Menu.spec.js
app/react/I18N/components/I18NLink.js
app/react/Settings/components/NavlinkForm.js
app/react/Settings/components/NavlinksSettings.js

Fixes issue #447
PR checklist:
QA checklist:

Added support for external URLs in menus

---

app/api/i18n/systemKeys.js
app/react/App/Menu.js
app/react/App/scss/elements/_controls.scss
app/react/App/scss/layout/_header.scss
app/react/App/scss/modules/_library.scss
app/react/Library/components/LibraryModeToggleButtons.js

Fixes issue #1513
PR checklist:
QA checklist:

1513 more tooltips

---

app/react/App/scss/config/_colors.scss

Fixes issue #1547
PR checklist:
QA checklist:

1547 improve color contrast

---

app/react/App/scss/modules/_markdown.scss

Fixes issue #1419
PR checklist:
QA checklist:

Quick tweak for markdown CSS to avoid text and controls overlapping

---

nightmare/helpers/nightmare.js

Fixes issue #
PR checklist:
QA checklist:

Switched nightmare config so its headless by default

---

app/api/entities/entities.js
app/api/entities/specs/entities.spec.js
app/api/templates/specs/fixtures.js
app/api/templates/specs/templates.spec.js
app/api/templates/templates.js
app/react/Templates/actions/templateActions.js
app/react/Templates/actions/templatesActions.js
app/react/Templates/components/MetadataTemplate.js
app/react/Templates/components/specs/MetadataTemplate.spec.js
nightmare/paths/metadata.spec.js

Fixes issue #1608 
PR checklist:
QA checklist:

Entities metadata is now properly updated after modifying the template

---

app/api/pages/routes.js

Fixes issue #1668
PR checklist:
QA checklist:

Reverted changes that, uncomprehensibly, fail.

---

app/react/App/Menu.js
app/react/App/specs/Menu.spec.js
nightmare/paths/entity.spec.js
nightmare/paths/publishDocument.spec.js

Fixes issue #1670
PR checklist:
QA checklist:

1670 empty url bug

---

app/react/Map/Map.js
app/react/Map/specs/Map.spec.js
app/setUpJestClient.js

Fixes issue #
PR checklist:
QA checklist:

hot fix for arabic suport in mapbox

---

app/react/Forms/components/MultiSelect.js

Fixes issue #
PR checklist:
QA checklist:

updated icon class for multiselect checkboxes

---

app/react/Metadata/components/MetadataFormFields.js

Fixes issue #1713 
PR checklist:
QA checklist:

Added options to prevent passing React Elements to select.

---

app/react/Pages/components/PageCreator.js
nightmare/paths/pages.spec.js

Fixes issue #1705
PR checklist:
QA checklist:

removed use of window global variable to prevent crash on server side

---

app/react/Forms/components/MultiSelect.js
app/react/Library/components/FiltersForm.js
app/react/Library/helpers/libraryFilters.js
app/react/Library/helpers/specs/libraryFilters.spec.js

Fixes issue #1716 #1712 #1711 #1671 #1717
PR checklist:
QA checklist:

Fixes to multiselect due to thesauris groups

---

app/react/Markdown/CustomHooks/components/CejilChart.js
database/health_check.js

Fixes issue #1692 
PR checklist:
QA checklist:

1692 fix broken page

---

app/react/Forms/components/MultiSelect.js

Fixes issue #1724
PR checklist:
QA checklist:

fixed bug when folding and unfolding multiselect subgroups

---

app/api/attachments/routes.js
app/api/attachments/specs/routes.spec.js
app/react/Forms/components/MultiSelect.js
app/react/Forms/components/NestedMultiselect.js
app/react/Forms/components/Select.js
app/react/Forms/components/specs/NestedMultiselect.spec.js
app/react/Forms/components/specs/Select.spec.js
app/react/I18N/components/specs/Translate.spec.js
app/react/I18N/components/specs/TranslateForm.spec.js
nightmare/helpers/extensions.js
nightmare/paths/multiEdit.spec.js

Fixes issue #1728
PR checklist:
QA checklist:

1728 multiselect fixes

---

app/api/search/documentQueryBuilder.js
app/api/search/search.js
app/api/search/specs/elasticResult.js
app/api/search/specs/search.spec.js
app/api/templates/specs/utils.spec.js
app/api/templates/utils.js
app/react/Forms/components/MultiSelect.js
app/react/Forms/components/specs/MultiSelect.spec.js
app/react/Library/helpers/libraryFilters.js
app/react/Thesauris/actions/thesauriActions.js
app/react/Thesauris/components/ThesauriForm.js

Fixes issue #1712 
PR checklist:
QA checklist:

query builder now calculates aggregations for dictionary groups

---

app/api/search/search.js
app/api/search/specs/__snapshots__/search.spec.js.snap
app/api/search/specs/search.spec.js
app/react/Markdown/components/BarChart.js
app/react/Markdown/components/Counter.js
app/react/Markdown/components/PieChart.js
app/react/Markdown/components/index.js
app/react/Markdown/components/specs/BarChart.spec.js
app/react/Markdown/components/specs/Counter.spec.js
app/react/Markdown/components/specs/PieChart.spec.js
app/react/Markdown/components/specs/__snapshots__/BarChart.spec.js.snap
app/react/Markdown/components/specs/__snapshots__/Counter.spec.js.snap
app/react/Markdown/components/specs/__snapshots__/PieChart.spec.js.snap
app/react/Markdown/index.js
app/react/Markdown/markdownDatasets.js
app/react/Markdown/markdownToReact.js
app/react/Markdown/specs/MarkdownViewer.spec.js
app/react/Markdown/specs/__snapshots__/MarkdownViewer.spec.js.snap
app/react/Markdown/specs/markdownDatasets.spec.js
app/react/Pages/PageView.js
app/react/Pages/reducers/reducer.js
app/react/Pages/specs/PageView.spec.js
app/react/Thesauris/actions/thesauriActions.js
app/react/reducer.js
app/shared/comonProperties.js
package.json
yarn.lock

Fixes issue #1699 
PR checklist:
QA checklist:

1699 charts components

---

app/react/RelationTypes/components/RelationTypeForm.js
app/react/Templates/components/MetadataTemplate.js

Fixes issue #1710
PR checklist:
QA checklist:

Fix bug relationtypes name checking for duplication on templates instead of relationtypes

---

app/react/App/scss/modules/_settings.scss
app/react/App/scss/modules/_uploads.scss
app/react/Settings/components/CollectionSettings.js
app/react/Settings/components/CustomUploads.js
app/react/Settings/components/Customisation.js
app/react/Settings/components/specs/__snapshots__/CustomUploads.spec.js.snap
app/react/Settings/components/specs/__snapshots__/Customisation.spec.js.snap

Fixes issue #1723 
PR checklist:
QA checklist:

Add buttons to access advanced customizations + styles

---

app/react/App/scss/modules/_search.scss

Fixes issue #1422 
PR checklist:
QA checklist:

Update multiselect searchbox style

---

app/react/App/scss/layout/_sidepanel.scss

Fixes issue #1734 
PR checklist:
QA checklist:

Fix searchbox size on sidepanel

---

app/api/log/errorLog.js
app/api/log/specs/errorLog.spec.js

Graylog transport now receives instance name properly

---

app/react/App/scss/elements/_alerts.scss
app/react/Metadata/components/SelectMultiplePanel.js

Fixes issue #1299 
PR checklist:
QA checklist:

Fix alert when multiple documents are edited at the same time

---

app/react/App/scss/elements/_item.scss

Fixes issue #1289 
PR checklist:
QA checklist:

Improve sorting styles with background color

---

app/api/attachments/routes.js
app/api/attachments/specs/routes.spec.js

Fixes issue #
PR checklist:
QA checklist:

using path.join to properly concatenate attachment download path

---

app/api/entities/entities.js
app/api/entities/specs/entities.spec.js
app/api/entities/specs/fixtures.js
app/react/Forms/components/Select.js
app/react/Forms/components/specs/Select.spec.js

Fixes issue #1772 
PR checklist:
QA checklist:

Select now has a proper blank value for the placeholder option

---

app/react/Library/components/MapView.js
app/react/Library/components/specs/MapView.spec.js
app/react/Library/components/specs/__snapshots__/MapView.spec.js.snap
app/react/Map/Markers.js
app/react/Map/index.js
app/react/Map/specs/Markers.spec.js
app/react/Map/specs/__snapshots__/Markers.spec.js.snap
app/react/Markdown/components/Map.js
app/react/Markdown/components/index.js
app/react/Markdown/components/specs/Map.spec.js
app/react/Markdown/components/specs/__snapshots__/Map.spec.js.snap
app/react/Markdown/markdownDatasets.js
app/react/Markdown/specs/markdownDatasets.spec.js

Fixes issue #1658 
PR checklist:
QA checklist:

Added Map to Markdown components.

---

app/react/Library/helpers/requestState.js
app/react/ServerRouter.js
yarn.lock

Fixes issue #
PR checklist:
QA checklist:

Fix logging 404

---

app/react/Thesauris/components/ThesauriForm.js
app/react/Thesauris/components/specs/ThesauriForm.spec.js

Fixes issue #1793 
PR checklist:
QA checklist:

Fixed error on thesauri form when the thesauri is empty

---

app/react/App/scss/modules/_markdown.scss
app/react/App/scss/modules/_slider.scss

Fixes issue #1749 
PR checklist:
QA checklist:

Improve styling on markdown

---

app/react/Forms/components/MultiSelect.js
app/react/Forms/components/specs/MultiSelect.spec.js
app/react/Forms/utils/optionsUtils.js
app/react/Forms/utils/specs/optionsUtils.spec.js

Fixes issue #1742
PR checklist:
QA checklist:

1742 multiselect nested search

---

app/react/Settings/components/ThesaurisList.js
app/react/Settings/utils/sortThesauri.js
app/react/Settings/utils/specs/sortThesauriList.spec.js

Fixes issue #1709
PR checklist:
QA checklist:

Order thesauri by name in settings

---

app/api/search/documentQueryBuilder.js
app/api/search/routes.js
app/api/search/search.js
app/api/search/specs/routes.spec.js
app/api/search/specs/search.spec.js
database/elastic_mapping.js

Fixes issue #1682 #1475
PR checklist:
QA checklist:

Query String for library search

---

app/react/Entities/EntitiesAPI.js
app/react/Markdown/components/GaugeChart.js
app/react/Markdown/components/ListChart.js
app/react/Markdown/components/PieChart.js
app/react/Markdown/components/index.js
app/react/Markdown/components/specs/GaugeChart.spec.js
app/react/Markdown/components/specs/ListChart.spec.js
app/react/Markdown/components/specs/__snapshots__/GaugeChart.spec.js.snap
app/react/Markdown/components/specs/__snapshots__/ListChart.spec.js.snap
app/react/Markdown/markdownDatasets.js
app/react/Markdown/specs/markdownDatasets.spec.js

Fixes issue #1659
PR checklist:
QA checklist:

1659 markdown list

---

app/react/Markdown/components/GaugeChart.js
app/react/Markdown/components/Value.js
app/react/Markdown/components/index.js
app/react/Markdown/components/specs/GaugeChart.spec.js
app/react/Markdown/components/specs/Value.spec.js
app/react/Markdown/components/specs/__snapshots__/GaugeChart.spec.js.snap
app/react/Markdown/components/specs/__snapshots__/Value.spec.js.snap

Fixes issue #1814 
PR checklist:
QA checklist:

Added suffix to the Gauge Chart component.

---

app/react/ServerRouter.js
nightmare/helpers/config.js
nightmare/helpers/selectors.js
nightmare/paths/smokePrivateInstance.spec.js

Fixes issue #
PR checklist:
QA checklist:

fixed error happening in private instances and smoke e2e tests

---

app/api/search/metadataAggregations.js
app/api/search/specs/__snapshots__/search.spec.js.snap
app/api/search/specs/fixtures_elastic.js
app/api/search/specs/search.spec.js

Fixes issue #
PR checklist:
QA checklist:

fixed grouped dictionaries aggregations query

---

app/api/utils/error_handling_middleware.js
app/api/utils/specs/error_handling_middleware.spec.js

Fixes issue #1810 
PR checklist:
QA checklist:

Tweaked error handling middleware so it only logs 500 or unknown errors

---

app/api/auth/privateInstanceMiddleware.js
app/api/auth/specs/privateInstanceMiddleware.spec.js

Fixes issue #1781 
PR checklist:
QA checklist:

Protected uploaded_documents from being accessed in private instances.

---

app/react/App/scss/modules/_markdown.scss

Fixes issue #1839 
PR checklist:
QA checklist:

Fix markdown font sizes on Sidepanel and Entity Viewer

---

app/react/App/scss/modules/_metadata-view.scss
app/react/Metadata/components/Metadata.js
app/react/Metadata/components/ShowMetadata.js
app/react/Metadata/components/specs/__snapshots__/Metadata.spec.js.snap

Fixes issue #1748 
PR checklist:
QA checklist:

Improve layout on entities

---

app/api/entities/specs/entities.spec.js
app/api/upload/specs/uploads.spec.js
app/react/Settings/components/specs/CustomUploads.spec.js

Fixes issue #
PR checklist:
QA checklist:

Uncomment tests that are preventing others from running.

---

.circleci/config.yml

Fixes issue #
PR checklist:
QA checklist:

CI e2e with production build

---

app/react/Library/Library.js
app/react/Library/LibraryLayout.js
app/react/Library/LibraryMap.js
app/react/Library/components/LibraryModeToggleButtons.js
app/react/Library/components/MapView.js
app/react/Library/components/specs/LibraryModeToggleButtons.spec.js
app/react/Library/specs/Library.spec.js
app/react/Library/specs/LibraryMap.spec.js
app/react/Map/Map.js
app/react/Map/helper.js
app/react/Map/specs/Map.spec.js

Fixes issue #1862 
PR checklist:
QA checklist:

1862 map zoom buttons

---

app/api/migrations/migrations/3-fullText_to_per_page/index.js
app/api/migrations/migrations/3-fullText_to_per_page/specs/3-fullText_to_per_page.spec.js
app/api/migrations/migrations/3-fullText_to_per_page/specs/fixtures.js

Fixes issue #
PR checklist:
QA checklist:

fixed race condition for fulltext migration

---

app/api/migrations/migrations/3-fullText_to_per_page/index.js

Fixes issue #
PR checklist:
QA checklist:

handle errors on migration 3

---

app/react/I18N/components/EditTranslationForm.js
app/react/I18N/components/specs/EditTranslationForm.spec.js

Fixes issue #1874 
PR checklist:
QA checklist:

updated translations form to only send the context beign updated

---

app/react/Uploads/UploadsRoute.js
nightmare/helpers/LibraryDSL.js
nightmare/helpers/extensions.js
nightmare/paths/publishDocument.spec.js
nightmare/paths/uploads.spec.js

Fixes issue #1890 
PR checklist:
QA checklist:

fixed uploads types filters

---

app/react/Forms/components/Geolocation.js

Fixes issue #1843 
PR checklist:
QA checklist:

configured geolocation field inputs as decimal values

---

app/react/App/scss/modules/_library.scss
app/react/App/scss/modules/_search.scss
app/react/Library/components/LibraryModeToggleButtons.js
app/react/Library/components/SearchBar.js
app/react/Library/reducers/specs/uiReducer.spec.js
app/react/Library/reducers/uiReducer.js

- Changed max and min zooms for the zoom function.
- Switched zoom buttons positions so they seem more natural.
- Fixed a CSS glitch in the search bar in mobile.
- Fixed a CSS glitch in the map.
PR checklist:
QA checklist:

Some UI tweaks

---

app/react/App/scss/modules/_document.scss
app/react/Viewer/actions/uiActions.js

Fixes issue #1878 
PR checklist:
QA checklist:

fallback strategy to highlight text snippets when no exact match

---

app/api/upload/PDF.js

Fixes issue #1907 
PR checklist:
QA checklist:

removed unused logFile from PDF.js

---

app/react/Documents/components/DocumentSidePanel.js
app/react/Documents/components/specs/DocumentSidePanel.spec.js
app/react/Pages/PageView.js
app/react/Pages/specs/PageView.spec.js

Fixes issue #1875 
PR checklist:
QA checklist:

initialiClosed sidePanel on pages

---

app/api/search/routes.js
app/api/search/specs/__snapshots__/routes.spec.js.snap

Fixes issue #1913 
PR checklist:
QA checklist:

fixed search endpoint validation for geolocation

---

app/api/socketio/middleware.js
app/api/socketio/specs/middleware.spec.js

Fixes issue #1935 
PR checklist:
QA checklist:

Fixed error when cookie undefined.

---

app/api/search/metadataMatchers.js
app/api/search/search.js
app/api/search/specs/fixtures_elastic.js
app/api/search/specs/search.spec.js
app/react/Library/helpers/libraryFilters.js
app/react/Library/helpers/specs/libraryFilters.spec.js

Fixes issue #1607 
PR checklist:
QA checklist:

make rich text filter work

---

app/api/upload/routes.js
app/api/upload/specs/routes.spec.js

Fixes issue #1915 
PR checklist:
QA checklist:

reupload only deletes file if no more entities using it

---

app/react/Library/helpers/requestState.js

Fixes issue #1930 
PR checklist:
QA checklist:

removed userSelectedSorting from request params on search

---

app/api/upload/specs/routes.spec.js

Fixes issue #1933 
PR checklist:
QA checklist:

fixed flaky tests

---

app/react/Metadata/helpers/specs/validator.spec.js
app/react/Metadata/helpers/validator.js

Fixes issue #1945 
PR checklist:
QA checklist:

fixed bug when required field had a null value
