huridocs/uwazi

app/react/Documents/actions/actions.js
app/react/Documents/actions/specs/actions.spec.js
app/react/Documents/components/DocumentForm.js
app/react/Documents/components/specs/DocumentForm.spec.js
app/react/Modals/index.js
app/react/Viewer/components/ConfirmCloseForm.js
app/react/Viewer/components/ViewMetadataPanel.js
app/react/Viewer/components/Viewer.js
app/react/Viewer/components/specs/ConfirmCloseForm.spec.js
app/react/Viewer/components/specs/ViewMetadataPanel.spec.js

solves #70 
When clicking outside, this panel does not close, the only way to close it is clicking on the close button, this is when the form resets.

document form resets when closing metadata panel

---

app/react/Viewer/components/Document.js
app/react/Viewer/components/SourceDocument.js
app/react/Viewer/components/specs/Document.spec.js
app/react/Viewer/components/specs/SourceDocument.spec.js
app/react/Viewer/scss/document.scss
app/react/Viewer/utils/Text.js
app/react/Viewer/utils/specs/Text.spec.js

solves: #49 
now the fake selection spans are only rendered when the real selection is removed, for instance, when opening the create references panel, so the user can copy the text selected.

be able to copy/paste text on the document viewer

---

app/api/templates/specs/templates.spec.js
app/api/templates/templates.js
app/react/Library/helpers/specs/libraryFilters.spec.js
app/react/Router.js
app/react/Templates/EditTemplate.js
app/react/Templates/NewTemplate.js
app/react/Templates/components/FilterSuggestions.js
app/react/Templates/components/MetadataTemplate.js
app/react/Templates/components/ValidateTemplate.js
app/react/Templates/components/specs/FilterSuggestions.spec.js
app/react/Templates/components/specs/MetadataProperty.spec.js
app/react/Templates/components/specs/MetadataTemplate.spec.js
app/react/Templates/specs/EditTemplate.spec.js
app/react/Templates/specs/NewTemplate.spec.js
app/react/Thesauris/actions/specs/thesaurisActions.spec.js
app/react/Viewer/specs/referencesAPI.spec.js

Now backend returns an error when trying to save a template with a name that already exists, and client side validation
Solves #44

Prevent save duplicated templates

---

app/api/settings/settings.js
app/api/settings/specs/settings.spec.js

When there is no settings in the DB, the model returns an empty object to prevent errors

Returning empty object when there is no settings on the DB

---

app/react/Viewer/components/Document.js

Fixes issue #31 
Fonts are actually converting right when running on linux (on mac the conversions produce large font files, like 1mb or more per font). this task includes generating new fixtures with properly converted documents.
PR check list:
QA check list:

Document renders font styles

---

app/react/Thesauris/NewThesauri.js
app/react/Thesauris/components/ThesauriForm.js
app/react/Thesauris/specs/NewThesauri.spec.js

Fixes issue #274 
PR check list:
QA check list:
…o prevent bad validations

ThesaurisForm now does not render if the thesauri is not yet loaded to prevent bad validations

---

app/react/Library/actions/filterActions.js
app/react/Library/actions/specs/filterActions.spec.js

Fixes issue #723 
PR check list:
QA check list:

Reset button in filters form now also resets the search input

---

app/react/App/scss/fixes.scss
app/react/App/scss/layout/_app.scss
app/react/App/scss/styles.scss

The `#app` padding-top wasn't aligned with the header:
PR check list:
QA check list:

Fix app top padding

---

app/react/App/scss/modules/_search.scss

**hotfix** When editing metadata, the font-family for titles differs from the viewing metadata ones.
PR check list:
QA check list:

Fix edit-metadata font

---

app/api/entities/routes.js
app/api/utils/error_handling_middleware.js
app/api/utils/instrumentRoutes.js
app/api/utils/specs/error_handling_middleware.spec.js
server.js

added error method to response object to use it on routes, the idea is to have the error handling centralized so we can decide later what we will do with different errors, now it responds with error to the client,  formatting correctly if its an unhandled error or a handled one.
PR check list:
QA check list:

Improve api error handling

---

app/react/Metadata/components/ShowMetadata.js
app/react/Timeline/components/TimelineViewer.js
app/react/Timeline/utils/timelineFixedData.js

Fixed timeline ussing label names instead of template properties which are multidate.
Fixes issue #891
PR check list:
QA check list:

Fixed timeline ussing label names instead of template properties

---

app/api/entities/entities.js
app/api/entities/specs/entities.spec.js
app/api/entities/specs/fixtures.js
app/api/utils/files.js

Fixes issue #873 
PR check list:
QA check list:

delete entities files now ignores file do not exist error

---

app/react/Templates/components/FilterSuggestions.js
app/react/Templates/components/specs/FilterSuggestions.spec.js

Fixes issue #995 
PR check list:
QA check list:

FilterSuggestions do not throw an error when thesauri no longer exists

---

app/react/Forms/components/DatePicker.js
app/react/Library/actions/libraryActions.js
app/react/Library/actions/specs/libraryActions.spec.js

Fixes issue #1288 
PR check list:
QA check list:

Emptying a date filter  no longer sends a filter with a null as value

---

app/react/I18N/components/I18NMenu.js
app/react/I18N/components/specs/I18NMenu.spec.js
app/react/I18N/components/specs/__snapshots__/I18NMenu.spec.js.snap

Fixes issue #1841 
PR checklist:
QA checklist:

Inline translation button is now always available

---

app/api/attachments/routes.js
app/api/attachments/specs/routes.spec.js

Fixes issue #1995 
PR checklist:
QA checklist:

Throw 404 error when downloading an attachment file that doesn't exist

---

app/api/utils/files.js
app/api/utils/specs/files.spec.js

Fixes issue #1968 
PR checklist:
QA checklist:

utils delete files ignores error when its a file not found

---

app/api/csv/specs/fixtures.js
app/api/csv/specs/typeParsers.spec.js
app/api/csv/typeParsers.js

fixes #2320
import script basic usage:
yarn import-csv will show help on how to use the script,
csv needs at least a title column, every other field is treated as metadata if configured in the instance, thesauri and template to relate to need to be also created in the instance.
example csv:
```
Title , text label  , select label, 
title1, text value 1, thesauri1   , 
title2, text value 2, thesauri2   , 
title3, text value 3, thesauri2   , 
```

do not duplicate values when value has already a blank space on db

---

app/api/search/search.js
app/api/search/specs/__snapshots__/searchDatesFilters.spec.js.snap
app/api/search/specs/fixtures_elastic.js
app/api/search/specs/searchDatesFilters.spec.js
app/api/utils/date.js
app/api/utils/specs/date.spec.js

for now only implemented: 'last-day-last-month' and 'first-day-last-month'
example: ?q=(filters:(initial_date:(from:first-day-last-month,to:last-day-last-month)))
PR checklist:
QA checklist:

Date filters as string proof of concept

---

app/react/Metadata/containers/FormatMetadata.js
app/react/Metadata/containers/specs/FormatMetadata.spec.js
app/react/Metadata/helpers/formater.js
app/react/Metadata/helpers/specs/fixtures.js
app/react/Metadata/helpers/specs/formater.spec.js
app/react/Metadata/selectors.js

patched a a performmance bug when rendering multiple values of a relationship with lots of entries
PR checklist:
QA checklist:

index thesauri values, improve render performance

---

README.md

as found in https://github.com/fititnt/uwazi-docker/blob/master/docker-compose.yml during investigation of https://github.com/huridocs/uwazi/pull/2559
I'm guessing there may be others, but this is a start of documenting this; perhaps others would like to complete this in follow-up PRs?
@konzz @txau @fititnt

Document environment variables in README

---

app/react/utils/api.js
app/react/utils/specs/api.spec.js

fixes #2503
Displays a "Could not reach server. Please try again later." When a request fails when due failed to connection to the server (the server could be unreachable, or the client could be offline).
PR checklist:
QA checklist:

Display error when saving data while server is down

---

app/api/entities/entities.js
app/api/entities/routes.js
app/api/entities/specs/__snapshots__/routes.spec.js.snap
app/api/entities/specs/entities.spec.js
app/api/entities/specs/fixtures.js
app/api/entities/specs/routes.spec.js

To check if an entity exists, the endpoint 'get entities' now accepts queries like {_id:'34344353453'}. This is useful for avoiding duplications by the Crawler uploads

Get entity by

---

package.json
yarn.lock

this prevents warning error on launching e2e tests on hot
PR checklist:
QA checklist:

using a fork of forms lib to prevent warning e2e

---

package.json

this is a hotfix for an error on deploying production, when migrate is launched babel-dynamic-import-plugin is not available because its set as dev dependency, i think this is correct but right now i do not have a better solution for this and it is not critical.

moved dynamic import babel plugin to dependencies

---

app/api/migrations/migrations/22-files-to-updatelogs/index.js
app/api/migrations/migrations/22-files-to-updatelogs/specs/22-files-to-updatelogs.spec.js
app/api/migrations/migrations/22-files-to-updatelogs/specs/fixtures.js
app/api/migrations/migrations/23-fix_udaptelogs/index.js
app/api/migrations/migrations/23-fix_udaptelogs/specs/23-fix_udaptelogs.spec.js
app/api/migrations/migrations/23-fix_udaptelogs/specs/fixtures.js
app/api/migrations/templates/migration.spec.txt
app/api/migrations/templates/migration.txt
app/api/odm/model.ts
app/api/updatelogs/updatelogsModel.ts

this updates the updatelogs collection to include all files logs that were created on migration 21, this migrations do NOT need a reindex.
@RafaPolit this also includes now migration 23, and a errorLog to try to track an error happening and creating updatelogs without mongoId, we are assuming here that when this happens the document does not get created, all this migration does is remove those bugged updatelogs for the sync to coninue working.
fixes #2779
PR checklist:
QA checklist:

Files to updatelogs migration

---

app/api/migrations/migrations/24-fix_updatelogs_again/index.js
app/api/migrations/migrations/24-fix_updatelogs_again/specs/24-fix_udaptelogs.spec.js
app/api/migrations/migrations/24-fix_updatelogs_again/specs/fixtures.js
app/api/odm/model.ts

in this PR the bug on updatelogs without mongoId its properly fixed, i had to do again migration 23 as migration 24 to remove any other entries with null mongoId created during this period, this was possible even with the guard condition because happened on delete calling updateMany:
https://github.com/huridocs/uwazi/blob/e7bd217dc688e968bbab5422f2c2e0f77fc15f06/app/api/odm/model.ts#L52-L58
whenever an empty array of affectedIds is passed this method, this actually creates an entry with only the $set object properties, this is because of the **upsert: true** that actually makes no sense in this query as it is supposed to update only, i also think this behaviour makes no sense on mongo itself, probably missing some bigger context, anyway this was the cause.
PR checklist:
QA checklist:
- …

Fix updtelogs without mongoid

---

app/api/entities/metadataValidators.js
app/api/entities/specs/entitySchema.spec.js
app/shared/types/entitySchema.js

validation for gelocation fields assume label should be a string, this fails when the label does not exist. most instances have this type of data where geolocation does not have a string.
PR checklist:
QA checklist:

gelocation label now is optional

---

database/reindex_elastic.js

I found some situations where the exceptions do not contain a message but a reason. Since this particular error logging is very well bounded to the scope "uncaught elastic reindexing errors", I think is ok to treat it as a special case and just stringify the whole error object. Otherwise, I was getting an "undefined" message on index mapping misconfigurations.
PR checklist:
QA checklist:

Stringify the error since not always contains a message

---

database/reindex_elastic.js

Fixes previous merge #3057.
this errors that are not instance of Error come from JSONRequest:
https://github.com/huridocs/uwazi/blob/49e93aed0aa0062cf0378380c5d4a0f621825752/app/shared/JSONRequest.js#L98-L109
at some point i think we should rethink this for consistency, but for now a condition on the error print its enough.
PR checklist:
QA checklist:

properly print error when not instanceof Error

---

app/api/config.ts
app/api/log/errorLog.js
app/api/log/formatMessage.js
app/api/log/specs/GrayLogTransport.spec.js
app/api/log/specs/errorLog.spec.js
app/api/socketio/setupSockets.ts
app/api/socketio/specs/socketClusterMode.spec.ts
app/api/tenants/index.ts
app/api/tenants/tenantContext.ts
app/api/utils/handleError.js
app/api/utils/specs/error_handling_middleware.spec.js
app/api/utils/specs/handleError.spec.js
app/server.js
package.json

Error formatter now uses tenant name to identify the error, when tenant name is "default" then the current DB name is used for backwards compatibility.
PR checklist:
QA checklist:

[HOTFIX] formatMessage takes into account current tenant

---

app/api/files/routes.ts
app/api/files/specs/downloadRoute.spec.ts
app/api/files/specs/routes.spec.ts
package.json

fixes #3219 
PR checklist:
QA checklist:

[HOTFIX] support download files with utf8 names

---

package.json

migrate was not working on production, because the script specifies, migrate.TS, this is not true on prod build, all files are .JS after transpilation
PR checklist:
QA checklist:

yarn migrate script now works on prod

---

app/react/socket.js

use only websockets, this way there is no need for sticky session
PR checklist:
QA checklist:

deactivate socket.io fallbacks. [HOTFIX]

---

package.json
yarn.lock

Force resolving lodash and bl to newest version to make sure we are patched regardless of whether we upgrade the dependant modules or not.
PR checklist:
QA checklist:

Forcing resolutions while we update modules

---

e2e/helpers/disableTransitions.ts
e2e/suites/copy-from.test.ts
e2e/suites/default-library-view.test.ts
e2e/suites/entity.test.ts
e2e/suites/graphs.test.ts
e2e/suites/login.test.ts
e2e/suites/tableView.test.ts

Disables CSS transitions during e2e testing to speed up tests and reduce the chances of hidden elements.
PR checklist:
QA checklist:

Trying to disable transiations for copy-from e2e

---

app/api/socketio/specs/socketClusterMode.spec.ts
app/api/sync/specs/uploadRoute.spec.ts
app/api/tenants/tenantContext.ts
app/api/utils/AppContext.ts
app/api/utils/appContextMiddleware.ts
app/api/utils/multitenantMiddleware.ts
app/api/utils/specs/appContext.spec.ts
app/api/utils/specs/appContextMiddleware.spec.ts
app/api/utils/specs/multitenantMiddleware.spec.ts
app/server.js

This refactors separates the multitenant async context management into two different concerns:
- Multitenancy
- Async context management
This is needed in order to use the async context for other functionalities, e.g user permissions.
PR checklist:
QA checklist:

Multitenant context refactor

---

app/api/search/deprecatedRoutes.js
app/api/search/search.js
app/api/search/specs/index.spec.js
app/api/search/specs/routes.spec.js
app/api/search/specs/search.spec.js
package.json

fixes #
PR checklist:
QA checklist:

Hotfix snippets search

---

app/react/Settings/components/SettingsNavigation.js
app/react/UI/Icon/library.js

fixes #3370. Add an external link to the Uwazi documentation in the setting navigation bar. 
PR checklist:
QA checklist:

Added link to documentations in nav menu.

---

app/api/migrations/migrations/34-remove-_id-from-filter-items/index.js
app/api/migrations/migrations/34-remove-_id-from-filter-items/specs/34-remove-_id-from-filter-items.spec.js
app/api/migrations/migrations/34-remove-_id-from-filter-items/specs/fixtures.js

fixes #3485 
PR checklist:
QA checklist:

Adds a migration to remove _id from filter items

---

app/api/search/search.js
app/react/Layout/DocumentCounter.tsx
app/react/Layout/DocumentsList.js
app/react/Layout/specs/DocumentCounter.spec.tsx

fixes #2708
PR checklist:
QA checklist:

2708-Entity-counter-limits

---

webpack/build.sh

fixes #3526 
solution based on https://dougrichardson.us/notes/fail-fast-bash-scripting.html
PR checklist:
QA checklist:

build should exit with 1 on any command fails

---

app/api/auth/specs/captchaMiddleware.spec.js
app/api/csv/specs/csvLoaderLanguages.spec.ts
app/api/csv/specs/csvLoaderZip.spec.ts
app/api/csv/typeParsers.ts
app/api/csv/typeParsers/specs/relationship.spec.js
app/api/files/filesystem.ts
app/api/files/specs/jsRoutes.spec.js
app/api/files/specs/publicRoutes.spec.ts
app/api/files/specs/uploadRoutes.spec.ts
app/api/log/specs/errorLog.spec.js
app/api/migrations/migrations/33-character-count-to-absolute-position/specs/33-character-count-to-absolute-position.spec.js
app/api/migrations/migrations/34-move-attachments/index.js
app/api/migrations/migrations/34-move-attachments/specs/34-move-attachments.spec.js
app/api/search/specs/routes.spec.js
app/api/settings/specs/routes.spec.ts
app/api/socketio/specs/socketClusterMode.spec.ts
app/api/sync/specs/uploadRoute.spec.ts
app/api/templates/specs/templates.spec.js
app/api/templates/specs/utils.spec.ts
app/api/thesauri/specs/routes.spec.ts
app/api/usergroups/specs/userGroups.spec.ts
app/api/utils/async-fs.js
app/api/utils/specs/staticFilesMiddleware.spec.ts
app/api/utils/testing_db.ts
app/jest.client.config.js
app/jest.server.config.js
app/react/Forms/components/specs/Captcha.spec.js
app/setUpJestClient.js

fixes: #3561
PR checklist:
QA checklist:

Testsuite improvements

---

app/react/Documents/components/DocumentSidePanel.js
app/react/Documents/helpers.js
app/react/Layout/Item.js
app/react/Library/components/Doc.js
app/react/Viewer/PDFView.js
app/react/Viewer/actions/routeActions.js
app/react/Viewer/actions/specs/documentActions.spec.js
app/react/Viewer/components/Connection.js
app/react/Viewer/components/Document.js
app/react/Viewer/specs/PDFView.spec.js

fixes #3499 
PR checklist:
QA checklist:

getDocument returns relations.

---

webpack/config.js

fixes #3388
PR checklist:
QA checklist:

3388 - vendor.bundle.js hashing

---

app/api/entities/specs/entitySchema.spec.ts
app/api/templates/specs/fixtures.js
app/api/templates/specs/templateSchema.spec.ts
app/api/templates/specs/templates.spec.js
app/api/templates/specs/validatorFixtures.js
app/shared/types/commonSchemas.ts
app/shared/types/templateSchema.ts

fixes #1003 
PR checklist:
QA checklist:

Added async validation to the templates to check the thesauri exists

---

app/api/entities/entities.js
app/api/entities/specs/entities.spec.js

fixes #3630
PR checklist:
QA checklist:

3630 public form with access levels

---

app/api/entities/specs/entities.spec.js
app/api/migrations/migrations/39-remove_wrong_text_references/index.js
app/api/migrations/migrations/39-remove_wrong_text_references/specs/39-remove_wrong_text_references.spec.js
app/api/migrations/migrations/39-remove_wrong_text_references/specs/fixtures.js
app/api/relationships/model.js
app/api/relationships/relationships.js
app/api/relationships/routes.js
app/api/relationships/specs/__snapshots__/relationships.spec.js.snap
app/api/relationships/specs/relationships.spec.js
app/api/relationships/specs/routes.spec.ts
app/api/relationships/validateConnectionSchema.ts
app/react/Connections/actions/specs/actions.spec.js
app/react/Relationships/actions/actions.js
app/react/Viewer/components/PageReferences.tsx
app/shared/types/connectionSchema.ts
app/shared/types/connectionType.d.ts

fixes #3623 
PR checklist:
QA checklist:

3623 fix broken references

---

app/api/search/entitiesIndex.js

fixes #
PR checklist:
QA checklist:

batch indexing with query that contains _id

---

e2e/suites/share-entities.test.ts

fixes #3682
PR checklist:
QA checklist:

close notification blocking next text click

---

app/server.js
package.json

fixes #3686 
PR checklist:
QA checklist:

HOTFIX, crons now run with permissions command context

---

app/api/csv/specs/csvExporter.spec.ts
app/api/csv/specs/typeFormatters.spec.ts
app/api/csv/typeFormatters.ts
app/react/Forms/components/DatePicker.js
app/react/Forms/components/specs/DatePicker.spec.js
app/react/Metadata/helpers/formater.js
app/react/Metadata/helpers/specs/formater.spec.js

fixes #3509
fixes #3451
PR checklist:
QA checklist:

3509 not utc for dates

---

app/react/App/scss/modules/_ContextMenu.scss
app/react/Entities/components/EntityViewer.js
app/react/Entities/components/ShowSidepanelMenu.js
app/react/Entities/components/specs/EntityViewer.spec.js
app/react/Entities/components/specs/__snapshots__/ShowSidepanelMenu.spec.js.snap
app/react/UI/Icon/library.js

fixes #4013 
PR checklist:
QA checklist:

4013 - Custom entity page starts with sidepanel closed

---

.github/dependabot.yml

@types updates can make our check types steps to fail due to discrepancies with the main dependency.  Ignoring them  and updating the @types whenever a dependency is updated can be a good solution.
PR checklist:
QA checklist:

Don't track @types dependencies on dependabot

---

app/server.js

related to: #4150
When we restart our service, a SIGINT signal is sent.  Listening to that signal allows us to do a graceful shutdown:
- Stop accepting new requests.
- Finish all the ongoing requests.
- Clean up DB connections.
PR checklist:
QA checklist:

Graceful shutdown on SIGINT signal

---

app/api/auth/routes.js
app/api/config.ts
app/api/odm/DB.ts
app/api/odm/MultiTenantMongooseModel.ts
app/api/odm/specs/DB.spec.ts

extra db connection objects (tenant connections mostly) not going to be eventListeners of the original connection to prevent warning messages and potential memory leak.

noListener for db extra connections.

---

webpack/webpack.config.hot.js
webpack/webpack.server.js

`yarn hot` command broke on `webpack-dev-middleware` dependency update due to deprecated property on options.
PR checklist:
QA checklist:

Fix logLevel for webpack-dev-middleware

---

app/api/entities/entities.js

related to #4356 
Improved the number of queries on entity save (post to api/entities), by pre-loading thesauri.
PR checklist:
QA checklist:

Post api entities rework

---

app/react/App/Root.js
app/react/index.js
app/server.js

To be able to track all errors on Sentry.

Remove custom handler on API's Sentry integration
